"""Package-level surface contracts for ``expy.v2gjson`` (ADR-0012, ADR-0013).

Pins four invariants at the package boundary:

1. ``expy/v2gjson/__init__.py`` imports submodules by name; wildcard re-exports that
   silently collide across Namespaces (every Namespace defines
   ``MessageHeaderType``, ``BodyType``, ``V2G_Message``) must not leak through the
   package surface.
2. The single canonical ``__version__`` is re-exported at the package level.
3. Every Namespace module is codegen output (banner present).
4. ``example.py`` runs end-to-end with module-as-namespace imports.

Per-Namespace roundtrips live in ``test_v2gjson_roundtrip.py``.
"""

from __future__ import annotations

from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]


def test_v2gjson_init_does_not_leak_namespace_symbols():
    """`from .iso2 import *` (and friends) silently re-export
    `MessageHeaderType`, `BodyType`, `V2G_Message`, etc. — every Namespace
    defines those names, so wildcards collide on whichever module was imported
    last. The fix is module-as-namespace: import the submodule, then access
    its symbols.
    """
    from expy import v2gjson

    for leaked in ("MessageHeaderType", "BodyType", "V2G_Message"):
        assert not hasattr(v2gjson, leaked), (
            f"expy.v2gjson.{leaked} is exposed at package level — wildcard leak from "
            "`from .iso2 import *` (or sibling). __init__.py should use "
            "`from . import iso2` (module-as-namespace) instead."
        )


def test_v2gjson_exposes_version_at_package_level():
    """Per #29 + ADR-0012, the single canonical version lives in `_version.py`
    and is re-exported by the v2gjson subpackage."""
    from expy import v2gjson

    assert isinstance(v2gjson.__version__, str)
    assert v2gjson.__version__  # non-empty


def test_namespace_modules_are_codegen_output():
    """Per ADR-0012, every Namespace module is emitter output. The banner is
    stamped by `tools/codegen/v2gjson_emitter.py:emit()`.

    `expy/v2gjson/common.py` is also codegen output (per #34) but is excluded
    here because it is a shared helper for the libcbv2g ``exi_unsigned_t`` /
    ``exi_signed_t`` types, not a Namespace — this check scopes to Namespace
    modules only.
    """
    package_dir = REPO_ROOT / "expy" / "v2gjson"
    expected_banner = (
        "Auto-generated by tools/codegen/v2gjson_emitter.py. DO NOT EDIT."
    )
    namespace_modules = [
        "sap.py",
        "din.py",
        "iso2.py",
        "iso20_common.py",
        "iso20_ac.py",
        "iso20_dc.py",
        "iso20_wpt.py",
        "iso20_acdp.py",
    ]
    for name in namespace_modules:
        text = (package_dir / name).read_text()
        assert expected_banner in text, (
            f"expy/v2gjson/{name} is not codegen output (banner missing). "
            f"Run `make expy/v2gjson/{name}` to regenerate."
        )


def test_example_py_runs_with_module_as_namespace_pattern():
    """`example.py` is the publicly-readable demonstration of the v1.0 API
    surface. It must:
      - run end-to-end without errors,
      - use module-as-namespace imports (no `from expy.v2gjson.* import *`),
      - exercise at least one ISO-20 Namespace via V2Gjson (per ADR-0012's
        v1.0 surface coverage).
    """
    import re
    import subprocess

    example_path = REPO_ROOT / "example.py"
    text = example_path.read_text()

    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("from expy.v2gjson.") and stripped.rstrip().endswith("import *"):
            raise AssertionError(
                f"example.py uses wildcard v2gjson import — {line!r}. "
                "Use module-as-namespace (`from expy.v2gjson import <name>`) instead."
            )

    # Crude check that an ISO-20 Namespace is imported. Stays lenient about
    # which one so the example can shift between AC / DC / etc. without test
    # churn.
    iso20_modules = ("iso20_common", "iso20_ac", "iso20_dc", "iso20_wpt", "iso20_acdp")
    iso20_pattern = re.compile(
        r"(?:from\s+expy\.v2gjson\s+import\b[^\n]*\b(" + "|".join(iso20_modules) + r")\b)"
        r"|(?:^\s*import\s+expy\.v2gjson\.(" + "|".join(iso20_modules) + r")\b)",
        re.MULTILINE,
    )
    assert iso20_pattern.search(text), (
        "example.py must exercise at least one ISO-20 Namespace via expy.v2gjson (per ADR-0012)."
    )

    result = subprocess.run(
        ["python3", str(example_path)],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert result.returncode == 0, (
        f"example.py exited {result.returncode}\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )
