"""Smoke tests for the V2Gjson public surface (ADR-0012).

Pins two things at the package boundary:

1. `V2Gjson.__init__.py` imports submodules by name; wildcard re-exports that
   silently collide across Namespaces (every Namespace defines
   `MessageHeaderType`, `BodyType`, `V2G_Message`) must not leak through the
   package surface.

2. A V2Gjson-built ISO-2 message round-trips through its sibling Processor.
   Full 8-Namespace coverage lands in #33; this smoke check pins the contract
   that the codegen migration in #32 must preserve.
"""

from __future__ import annotations

import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))

from conftest import assert_roundtrip  # noqa: E402


def test_v2gjson_init_does_not_leak_namespace_symbols():
    """`from .iso2 import *` (and friends) silently re-export
    `MessageHeaderType`, `BodyType`, `V2G_Message`, etc. — every Namespace
    defines those names, so wildcards collide on whichever module was imported
    last. The fix is module-as-namespace: import the submodule, then access
    its symbols.
    """
    import V2Gjson

    for leaked in ("MessageHeaderType", "BodyType", "V2G_Message"):
        assert not hasattr(V2Gjson, leaked), (
            f"V2Gjson.{leaked} is exposed at package level — wildcard leak from "
            "`from .iso2 import *` (or sibling). __init__.py should use "
            "`from . import iso2` (module-as-namespace) instead."
        )


def test_v2gjson_exposes_version_at_package_level():
    """Per #29 + ADR-0012, the single canonical version lives in `_version.py`
    and is re-exported by the V2Gjson package."""
    import V2Gjson

    assert isinstance(V2Gjson.__version__, str)
    assert V2Gjson.__version__  # non-empty


def test_namespace_modules_are_codegen_output():
    """Per ADR-0012, every Namespace module is emitter output. The banner is
    stamped by `tools/codegen/v2gjson_emitter.py:emit()`.

    `V2Gjson/common.py` is intentionally excluded — it is a shared helper for
    the libcbv2g `exi_unsigned_t` / `exi_signed_t` types, not a Namespace.
    Codegenning it requires parser/emitter extension for anonymous typedef
    structs, tracked in a follow-up issue.
    """
    package_dir = Path(REPO_ROOT) / "V2Gjson"
    expected_banner = (
        "Auto-generated by tools/codegen/v2gjson_emitter.py. DO NOT EDIT."
    )
    namespace_modules = [
        "sap.py",
        "din.py",
        "iso2.py",
        "iso20_common.py",
        "iso20_ac.py",
        "iso20_dc.py",
        "iso20_wpt.py",
        "iso20_acdp.py",
    ]
    for name in namespace_modules:
        text = (package_dir / name).read_text()
        assert expected_banner in text, (
            f"V2Gjson/{name} is not codegen output (banner missing). "
            f"Run `make V2Gjson/{name}` to regenerate."
        )


def test_din_message_header_roundtrips_via_module_namespace():
    """DIN smoke: matches the ISO-2 smoke check, on DIN. Catches drift if the
    DIN codegen output diverges from what its sibling Processor accepts.
    """
    from V2Gjson import din

    header = din.MessageHeaderType(SessionID=bytearray(b"DECAFBAD"))
    # DIN's SessionStopReq is typed `SessionStopType` upstream (not
    # `SessionStopReqType` like ISO-2). The codegen constructor name tracks
    # the libcbv2g struct name verbatim.
    body = din.BodyType(SessionStopReq=din.SessionStopType())
    payload = {"Header": header, "Body": body}
    assert_roundtrip("DIN", payload)


def test_sap_request_roundtrips_via_module_namespace():
    """SAP smoke: build a minimal `supportedAppProtocolReq` via V2Gjson
    constructors. The codegen-emitted ``supportedAppProtocolReq`` takes a
    pre-wrapped ``list[dict]`` and wraps it into the ``{"arrayLen", "array"}``
    envelope the marshaler reads.
    """
    from V2Gjson import sap

    protocols = [
        sap.AppProtocolType(
            ProtocolNamespace="urn:din:70121:2012:MsgDef",
            VersionNumberMajor=2,
            VersionNumberMinor=0,
            SchemaID=1,
            Priority=1,
        ),
    ]
    payload = {"supportedAppProtocolReq": sap.supportedAppProtocolReq(AppProtocol=protocols)}
    assert_roundtrip("SAP", payload)


def test_example_py_runs_with_module_as_namespace_pattern():
    """`example.py` is the publicly-readable demonstration of the v1.0 API
    surface. It must:
      - run end-to-end without errors,
      - use module-as-namespace imports (no `from V2Gjson.* import *`),
      - exercise at least one ISO-20 Namespace via V2Gjson (per ADR-0012's
        v1.0 surface coverage).
    """
    import subprocess

    example_path = Path(REPO_ROOT) / "example.py"
    text = example_path.read_text()

    forbidden = "from V2Gjson."
    for line in text.splitlines():
        if line.strip().startswith(forbidden) and line.rstrip().endswith("import *"):
            raise AssertionError(
                f"example.py uses wildcard V2Gjson import — {line!r}. "
                "Use module-as-namespace (`from V2Gjson import <name>`) instead."
            )

    # Crude check that an ISO-20 Namespace is imported. Stays lenient about
    # which one so the example can shift between AC / DC / etc. without test
    # churn.
    import re

    iso20_modules = ("iso20_common", "iso20_ac", "iso20_dc", "iso20_wpt", "iso20_acdp")
    iso20_pattern = re.compile(
        r"(?:from\s+V2Gjson\s+import\b[^\n]*\b(" + "|".join(iso20_modules) + r")\b)"
        r"|(?:^\s*import\s+V2Gjson\.(" + "|".join(iso20_modules) + r")\b)",
        re.MULTILINE,
    )
    assert iso20_pattern.search(text), (
        "example.py must exercise at least one ISO-20 Namespace via V2Gjson (per ADR-0012)."
    )

    result = subprocess.run(
        ["python3", str(example_path)],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        timeout=30,
    )
    assert result.returncode == 0, (
        f"example.py exited {result.returncode}\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )


def test_iso2_message_header_roundtrips_via_module_namespace():
    """The headline ADR-0012 smoke check: a Header built with V2Gjson
    constructors round-trips through `EXIProcessor(ProtocolEnum.ISO2)`.

    Uses `from V2Gjson import iso2; iso2.MessageHeaderType(...)` — the
    module-as-namespace pattern — not wildcard imports.
    """
    from V2Gjson import iso2

    header = iso2.MessageHeaderType(SessionID=bytearray(b"DECAFBAD"))
    body = iso2.BodyType(
        SessionStopReq=iso2.SessionStopReqType(
            ChargingSession=iso2.chargingSessionType.Terminate
        )
    )
    payload = {"Header": header, "Body": body}
    assert_roundtrip("ISO2", payload)
