"""
Constructors and enum tables for the DIN 70121 Namespace.

Auto-generated by tools/codegen/v2gjson_emitter.py. DO NOT EDIT.
"""

from enum import Enum
from typing import Any


# skipped din_generatedFunctionNumbersType: enum din_generatedFunctionNumbersType member 'din_AC_EVChargeParameter' does not start with expected prefix 'din_generatedFunctionNumbersType_'

class costKindType(Enum):
    relativePricePercentage = 0
    RenewableGenerationPercentage = 1
    CarbonDioxideEmission = 2


class isolationLevelType(Enum):
    Invalid = 0
    Valid = 1
    Warning = 2
    Fault = 3


class paymentOptionType(Enum):
    Contract = 0
    ExternalPayment = 1


class DC_EVSEStatusCodeType(Enum):
    EVSE_NotReady = 0
    EVSE_Ready = 1
    EVSE_Shutdown = 2
    EVSE_UtilityInterruptEvent = 3
    EVSE_IsolationMonitoringActive = 4
    EVSE_EmergencyShutdown = 5
    EVSE_Malfunction = 6
    Reserved_8 = 7
    Reserved_9 = 8
    Reserved_A = 9
    Reserved_B = 10
    Reserved_C = 11


class unitSymbolType(Enum):
    h = 0
    m = 1
    s = 2
    A = 3
    Ah = 4
    V = 5
    VA = 6
    W = 7
    W_s = 8
    Wh = 9


class EVSESupportedEnergyTransferType(Enum):
    AC_single_phase_core = 0
    AC_three_phase_core = 1
    DC_core = 2
    DC_extended = 3
    DC_combo_core = 4
    DC_dual = 5
    AC_core1p_DC_extended = 6
    AC_single_DC_core = 7
    AC_single_phase_three_phase_core_DC_extended = 8
    AC_core3p_DC_extended = 9


class DC_EVErrorCodeType(Enum):
    NO_ERROR = 0
    FAILED_RESSTemperatureInhibit = 1
    FAILED_EVShiftPosition = 2
    FAILED_ChargerConnectorLockFault = 3
    FAILED_EVRESSMalfunction = 4
    FAILED_ChargingCurrentdifferential = 5
    FAILED_ChargingVoltageOutOfRange = 6
    Reserved_A = 7
    Reserved_B = 8
    Reserved_C = 9
    FAILED_ChargingSystemIncompatibility = 10
    NoData = 11


class EVSENotificationType(Enum):
    None_ = 0
    StopCharging = 1
    ReNegotiation = 2


class faultCodeType(Enum):
    ParsingError = 0
    NoTLSRootCertificatAvailable = 1
    UnknownError = 2


class responseCodeType(Enum):
    OK = 0
    OK_NewSessionEstablished = 1
    OK_OldSessionJoined = 2
    OK_CertificateExpiresSoon = 3
    FAILED = 4
    FAILED_SequenceError = 5
    FAILED_ServiceIDInvalid = 6
    FAILED_UnknownSession = 7
    FAILED_ServiceSelectionInvalid = 8
    FAILED_PaymentSelectionInvalid = 9
    FAILED_CertificateExpired = 10
    FAILED_SignatureError = 11
    FAILED_NoCertificateAvailable = 12
    FAILED_CertChainError = 13
    FAILED_ChallengeInvalid = 14
    FAILED_ContractCanceled = 15
    FAILED_WrongChargeParameter = 16
    FAILED_PowerDeliveryNotApplied = 17
    FAILED_TariffSelectionInvalid = 18
    FAILED_ChargingProfileInvalid = 19
    FAILED_EVSEPresentVoltageToLow = 20
    FAILED_MeteringSignatureNotValid = 21
    FAILED_WrongEnergyTransferType = 22


class EVRequestedEnergyTransferType(Enum):
    AC_single_phase_core = 0
    AC_three_phase_core = 1
    DC_core = 2
    DC_extended = 3
    DC_combo_core = 4
    DC_unique = 5


class serviceCategoryType(Enum):
    EVCharging = 0
    Internet = 1
    ContractCertificate = 2
    OtherCustom = 3


class EVSEProcessingType(Enum):
    Finished = 0
    Ongoing = 1


class valueType(Enum):
    bool = 0
    byte = 1
    short = 2
    int = 3
    physicalValue = 4
    string = 5


def CostType(costKind:costKindType, amount:int, *, amountMultiplier:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "costKind": costKind.value,
        "amount": amount
    }
    if amountMultiplier is not None:
        j["amountMultiplier"] = amountMultiplier
    return j

def RelativeTimeIntervalType(start:int, *, duration:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "start": start
    }
    if duration is not None:
        j["duration"] = duration
    return j

def IntervalType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def ConsumptionCostType(startValue:int, *, Cost:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "startValue": startValue
    }
    if Cost is not None:
        j["Cost"] = Cost
    return j

def TransformType(Algorithm:str, *, ANY:bytearray|None=None, XPath:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    if XPath is not None:
        j["XPath"] = {"characters": [ord(c) for c in XPath], "charactersLen": len(XPath)}
    return j

def PMaxScheduleEntryType(PMax:int, *, RelativeTimeInterval:int|None=None, TimeInterval:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "PMax": PMax
    }
    if RelativeTimeInterval is not None:
        j["RelativeTimeInterval"] = RelativeTimeInterval
    if TimeInterval is not None:
        j["TimeInterval"] = TimeInterval
    return j

def SalesTariffEntryType(EPriceLevel:int, *, RelativeTimeInterval:int|None=None, TimeInterval:int|None=None, ConsumptionCost:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EPriceLevel": EPriceLevel
    }
    if RelativeTimeInterval is not None:
        j["RelativeTimeInterval"] = RelativeTimeInterval
    if TimeInterval is not None:
        j["TimeInterval"] = TimeInterval
    if ConsumptionCost is not None:
        j["ConsumptionCost"] = ConsumptionCost
    return j

def TransformsType(Transform:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Transform": Transform
    }
    return j

def DSAKeyValueType(Y:bytearray, *, P:bytearray|None=None, Q:bytearray|None=None, G:bytearray|None=None, J:bytearray|None=None, Seed:bytearray|None=None, PgenCounter:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Y": {"bytes": list(Y), "bytesLen": len(Y)}
    }
    if P is not None:
        j["P"] = {"bytes": list(P), "bytesLen": len(P)}
    if Q is not None:
        j["Q"] = {"bytes": list(Q), "bytesLen": len(Q)}
    if G is not None:
        j["G"] = {"bytes": list(G), "bytesLen": len(G)}
    if J is not None:
        j["J"] = {"bytes": list(J), "bytesLen": len(J)}
    if Seed is not None:
        j["Seed"] = {"bytes": list(Seed), "bytesLen": len(Seed)}
    if PgenCounter is not None:
        j["PgenCounter"] = {"bytes": list(PgenCounter), "bytesLen": len(PgenCounter)}
    return j

def X509IssuerSerialType(X509IssuerName:str, X509SerialNumber:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "X509IssuerName": {"characters": [ord(c) for c in X509IssuerName], "charactersLen": len(X509IssuerName)},
        "X509SerialNumber": X509SerialNumber
    }
    return j

def DigestMethodType(Algorithm:str, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def RSAKeyValueType(Modulus:bytearray, Exponent:bytearray)->dict[str, Any]:
    j:dict[str, Any] = {
        "Modulus": {"bytes": list(Modulus), "bytesLen": len(Modulus)},
        "Exponent": {"bytes": list(Exponent), "bytesLen": len(Exponent)}
    }
    return j

def PMaxScheduleType(PMaxScheduleID:int, PMaxScheduleEntry:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "PMaxScheduleID": PMaxScheduleID,
        "PMaxScheduleEntry": {"arrayLen": len(PMaxScheduleEntry), "array": PMaxScheduleEntry}
    }
    return j

def SalesTariffType(Id:str, SalesTariffID:int, NumEPriceLevels:int, SalesTariffEntry:list[dict[str, Any]], *, SalesTariffDescription:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Id": {"characters": [ord(c) for c in Id], "charactersLen": len(Id)},
        "SalesTariffID": SalesTariffID,
        "NumEPriceLevels": NumEPriceLevels,
        "SalesTariffEntry": {"arrayLen": len(SalesTariffEntry), "array": SalesTariffEntry}
    }
    if SalesTariffDescription is not None:
        j["SalesTariffDescription"] = {"characters": [ord(c) for c in SalesTariffDescription], "charactersLen": len(SalesTariffDescription)}
    return j

def CanonicalizationMethodType(Algorithm:str, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def ServiceTagType(ServiceID:int, ServiceCategory:serviceCategoryType, *, ServiceName:str|None=None, ServiceScope:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ServiceID": ServiceID,
        "ServiceCategory": ServiceCategory.value
    }
    if ServiceName is not None:
        j["ServiceName"] = {"characters": [ord(c) for c in ServiceName], "charactersLen": len(ServiceName)}
    if ServiceScope is not None:
        j["ServiceScope"] = {"characters": [ord(c) for c in ServiceScope], "charactersLen": len(ServiceScope)}
    return j

def ServiceType(ServiceTag:int, FreeService:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "ServiceTag": ServiceTag,
        "FreeService": FreeService
    }
    return j

def SelectedServiceType(ServiceID:int, *, ParameterSetID:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ServiceID": ServiceID
    }
    if ParameterSetID is not None:
        j["ParameterSetID"] = ParameterSetID
    return j

def SAScheduleTupleType(SAScheduleTupleID:int, PMaxSchedule:int, *, SalesTariff:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SAScheduleTupleID": SAScheduleTupleID,
        "PMaxSchedule": PMaxSchedule
    }
    if SalesTariff is not None:
        j["SalesTariff"] = SalesTariff
    return j

def AC_EVSEStatusType(PowerSwitchClosed:int, RCD:int, NotificationMaxDelay:int, EVSENotification:EVSENotificationType)->dict[str, Any]:
    j:dict[str, Any] = {
        "PowerSwitchClosed": PowerSwitchClosed,
        "RCD": RCD,
        "NotificationMaxDelay": NotificationMaxDelay,
        "EVSENotification": EVSENotification.value
    }
    return j

def SignatureMethodType(Algorithm:str, *, HMACOutputLength:int|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if HMACOutputLength is not None:
        j["HMACOutputLength"] = HMACOutputLength
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def KeyValueType(*, DSAKeyValue:int|None=None, RSAKeyValue:int|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if DSAKeyValue is not None:
        j["DSAKeyValue"] = DSAKeyValue
    if RSAKeyValue is not None:
        j["RSAKeyValue"] = RSAKeyValue
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def SubCertificatesType(Certificate:bytearray)->dict[str, Any]:
    j:dict[str, Any] = {
        "Certificate": {"bytes": list(Certificate), "bytesLen": len(Certificate)}
    }
    return j

def ProfileEntryType(ChargingProfileEntryStart:int, ChargingProfileEntryMaxPower:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "ChargingProfileEntryStart": ChargingProfileEntryStart,
        "ChargingProfileEntryMaxPower": ChargingProfileEntryMaxPower
    }
    return j

def ReferenceType(DigestMethod:int, DigestValue:bytearray, *, Id:str|None=None, Type:str|None=None, URI:str|None=None, Transforms:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "DigestMethod": DigestMethod,
        "DigestValue": {"bytes": list(DigestValue), "bytesLen": len(DigestValue)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if Type is not None:
        j["Type"] = {"characters": [ord(c) for c in Type], "charactersLen": len(Type)}
    if URI is not None:
        j["URI"] = {"characters": [ord(c) for c in URI], "charactersLen": len(URI)}
    if Transforms is not None:
        j["Transforms"] = Transforms
    return j

def RetrievalMethodType(*, Type:str|None=None, URI:str|None=None, Transforms:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Type is not None:
        j["Type"] = {"characters": [ord(c) for c in Type], "charactersLen": len(Type)}
    if URI is not None:
        j["URI"] = {"characters": [ord(c) for c in URI], "charactersLen": len(URI)}
    if Transforms is not None:
        j["Transforms"] = Transforms
    return j

def X509DataType(*, X509IssuerSerial:int|None=None, X509SKI:bytearray|None=None, X509SubjectName:str|None=None, X509Certificate:bytearray|None=None, X509CRL:bytearray|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if X509IssuerSerial is not None:
        j["X509IssuerSerial"] = X509IssuerSerial
    if X509SKI is not None:
        j["X509SKI"] = {"bytes": list(X509SKI), "bytesLen": len(X509SKI)}
    if X509SubjectName is not None:
        j["X509SubjectName"] = {"characters": [ord(c) for c in X509SubjectName], "charactersLen": len(X509SubjectName)}
    if X509Certificate is not None:
        j["X509Certificate"] = {"bytes": list(X509Certificate), "bytesLen": len(X509Certificate)}
    if X509CRL is not None:
        j["X509CRL"] = {"bytes": list(X509CRL), "bytesLen": len(X509CRL)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def PGPDataType(*, choice_1:int|None=None, choice_2:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if choice_1 is not None:
        j["choice_1"] = choice_1
    if choice_2 is not None:
        j["choice_2"] = choice_2
    return j

def SPKIDataType(SPKISexp:bytearray, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SPKISexp": {"bytes": list(SPKISexp), "bytesLen": len(SPKISexp)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def SignedInfoType(CanonicalizationMethod:int, SignatureMethod:int, Reference:int, *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "CanonicalizationMethod": CanonicalizationMethod,
        "SignatureMethod": SignatureMethod,
        "Reference": Reference
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def DC_EVStatusType(EVReady:int, EVErrorCode:DC_EVErrorCodeType, EVRESSSOC:int, *, EVCabinConditioning:int|None=None, EVRESSConditioning:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVReady": EVReady,
        "EVErrorCode": EVErrorCode.value,
        "EVRESSSOC": EVRESSSOC
    }
    if EVCabinConditioning is not None:
        j["EVCabinConditioning"] = EVCabinConditioning
    if EVRESSConditioning is not None:
        j["EVRESSConditioning"] = EVRESSConditioning
    return j

def SignatureValueType(CONTENT:bytearray, *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "CONTENT": {"bytes": list(CONTENT), "bytesLen": len(CONTENT)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def CertificateChainType(Certificate:bytearray, *, SubCertificates:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Certificate": {"bytes": list(Certificate), "bytesLen": len(Certificate)}
    }
    if SubCertificates is not None:
        j["SubCertificates"] = SubCertificates
    return j

def DC_EVSEStatusType(EVSEStatusCode:DC_EVSEStatusCodeType, NotificationMaxDelay:int, EVSENotification:EVSENotificationType, *, EVSEIsolationStatus:isolationLevelType|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVSEStatusCode": EVSEStatusCode.value,
        "NotificationMaxDelay": NotificationMaxDelay,
        "EVSENotification": EVSENotification.value
    }
    if EVSEIsolationStatus is not None:
        j["EVSEIsolationStatus"] = EVSEIsolationStatus.value
    return j

def PhysicalValueType(Multiplier:int, Value:int, *, Unit:unitSymbolType|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Multiplier": Multiplier,
        "Value": Value
    }
    if Unit is not None:
        j["Unit"] = Unit.value
    return j

def ParameterType(Name:str, ValueType:valueType, *, boolValue:int|None=None, byteValue:int|None=None, shortValue:int|None=None, intValue:int|None=None, physicalValue:int|None=None, stringValue:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Name": {"characters": [ord(c) for c in Name], "charactersLen": len(Name)},
        "ValueType": ValueType.value
    }
    if boolValue is not None:
        j["boolValue"] = boolValue
    if byteValue is not None:
        j["byteValue"] = byteValue
    if shortValue is not None:
        j["shortValue"] = shortValue
    if intValue is not None:
        j["intValue"] = intValue
    if physicalValue is not None:
        j["physicalValue"] = physicalValue
    if stringValue is not None:
        j["stringValue"] = {"characters": [ord(c) for c in stringValue], "charactersLen": len(stringValue)}
    return j

def ParameterSetType(ParameterSetID:int, Parameter:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "ParameterSetID": ParameterSetID,
        "Parameter": Parameter
    }
    return j

def ListOfRootCertificateIDsType(RootCertificateID:list[str])->dict[str, Any]:
    j:dict[str, Any] = {
        "RootCertificateID": {"arrayLen": len(RootCertificateID), "array": [{"characters": [ord(_c) for _c in _s], "charactersLen": len(_s)} for _s in RootCertificateID]}
    }
    return j

def PaymentOptionsType(PaymentOption:list[paymentOptionType])->dict[str, Any]:
    j:dict[str, Any] = {
        "PaymentOption": {"arrayLen": len(PaymentOption), "array": [_v.value for _v in PaymentOption]}
    }
    return j

def SelectedServiceListType(SelectedService:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "SelectedService": {"arrayLen": len(SelectedService), "array": SelectedService}
    }
    return j

def AC_EVChargeParameterType(DepartureTime:int, EAmount:int, EVMaxVoltage:int, EVMaxCurrent:int, EVMinCurrent:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "DepartureTime": DepartureTime,
        "EAmount": EAmount,
        "EVMaxVoltage": EVMaxVoltage,
        "EVMaxCurrent": EVMaxCurrent,
        "EVMinCurrent": EVMinCurrent
    }
    return j

def DC_EVChargeParameterType(DC_EVStatus:int, EVMaximumCurrentLimit:int, EVMaximumVoltageLimit:int, *, EVMaximumPowerLimit:int|None=None, EVEnergyCapacity:int|None=None, EVEnergyRequest:int|None=None, FullSOC:int|None=None, BulkSOC:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "DC_EVStatus": DC_EVStatus,
        "EVMaximumCurrentLimit": EVMaximumCurrentLimit,
        "EVMaximumVoltageLimit": EVMaximumVoltageLimit
    }
    if EVMaximumPowerLimit is not None:
        j["EVMaximumPowerLimit"] = EVMaximumPowerLimit
    if EVEnergyCapacity is not None:
        j["EVEnergyCapacity"] = EVEnergyCapacity
    if EVEnergyRequest is not None:
        j["EVEnergyRequest"] = EVEnergyRequest
    if FullSOC is not None:
        j["FullSOC"] = FullSOC
    if BulkSOC is not None:
        j["BulkSOC"] = BulkSOC
    return j

def EVChargeParameterType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def ChargingProfileType(SAScheduleTupleID:int, ProfileEntry:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "SAScheduleTupleID": SAScheduleTupleID,
        "ProfileEntry": {"arrayLen": len(ProfileEntry), "array": ProfileEntry}
    }
    return j

def EVSEStatusType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def KeyInfoType(*, Id:str|None=None, KeyName:str|None=None, KeyValue:int|None=None, RetrievalMethod:int|None=None, X509Data:int|None=None, PGPData:int|None=None, SPKIData:int|None=None, MgmtData:str|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if KeyName is not None:
        j["KeyName"] = {"characters": [ord(c) for c in KeyName], "charactersLen": len(KeyName)}
    if KeyValue is not None:
        j["KeyValue"] = KeyValue
    if RetrievalMethod is not None:
        j["RetrievalMethod"] = RetrievalMethod
    if X509Data is not None:
        j["X509Data"] = X509Data
    if PGPData is not None:
        j["PGPData"] = PGPData
    if SPKIData is not None:
        j["SPKIData"] = SPKIData
    if MgmtData is not None:
        j["MgmtData"] = {"characters": [ord(c) for c in MgmtData], "charactersLen": len(MgmtData)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def ServiceChargeType(ServiceTag:int, FreeService:int, EnergyTransferType:EVSESupportedEnergyTransferType)->dict[str, Any]:
    j:dict[str, Any] = {
        "ServiceTag": ServiceTag,
        "FreeService": FreeService,
        "EnergyTransferType": EnergyTransferType.value
    }
    return j

def ServiceParameterListType(ParameterSet:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "ParameterSet": {"arrayLen": len(ParameterSet), "array": ParameterSet}
    }
    return j

def SAScheduleListType(SAScheduleTuple:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "SAScheduleTuple": {"arrayLen": len(SAScheduleTuple), "array": SAScheduleTuple}
    }
    return j

def SASchedulesType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def DC_EVPowerDeliveryParameterType(DC_EVStatus:int, ChargingComplete:int, *, BulkChargingComplete:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "DC_EVStatus": DC_EVStatus,
        "ChargingComplete": ChargingComplete
    }
    if BulkChargingComplete is not None:
        j["BulkChargingComplete"] = BulkChargingComplete
    return j

def EVPowerDeliveryParameterType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def ObjectType(*, Encoding:str|None=None, Id:str|None=None, MimeType:str|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Encoding is not None:
        j["Encoding"] = {"characters": [ord(c) for c in Encoding], "charactersLen": len(Encoding)}
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if MimeType is not None:
        j["MimeType"] = {"characters": [ord(c) for c in MimeType], "charactersLen": len(MimeType)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def ServiceTagListType(Service:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Service": Service
    }
    return j

def DC_EVSEChargeParameterType(DC_EVSEStatus:int, EVSEMaximumCurrentLimit:int, EVSEMaximumVoltageLimit:int, EVSEMinimumCurrentLimit:int, EVSEMinimumVoltageLimit:int, EVSEPeakCurrentRipple:int, *, EVSEMaximumPowerLimit:int|None=None, EVSECurrentRegulationTolerance:int|None=None, EVSEEnergyToBeDelivered:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "DC_EVSEStatus": DC_EVSEStatus,
        "EVSEMaximumCurrentLimit": EVSEMaximumCurrentLimit,
        "EVSEMaximumVoltageLimit": EVSEMaximumVoltageLimit,
        "EVSEMinimumCurrentLimit": EVSEMinimumCurrentLimit,
        "EVSEMinimumVoltageLimit": EVSEMinimumVoltageLimit,
        "EVSEPeakCurrentRipple": EVSEPeakCurrentRipple
    }
    if EVSEMaximumPowerLimit is not None:
        j["EVSEMaximumPowerLimit"] = EVSEMaximumPowerLimit
    if EVSECurrentRegulationTolerance is not None:
        j["EVSECurrentRegulationTolerance"] = EVSECurrentRegulationTolerance
    if EVSEEnergyToBeDelivered is not None:
        j["EVSEEnergyToBeDelivered"] = EVSEEnergyToBeDelivered
    return j

def AC_EVSEChargeParameterType(AC_EVSEStatus:int, EVSEMaxVoltage:int, EVSEMaxCurrent:int, EVSEMinCurrent:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "AC_EVSEStatus": AC_EVSEStatus,
        "EVSEMaxVoltage": EVSEMaxVoltage,
        "EVSEMaxCurrent": EVSEMaxCurrent,
        "EVSEMinCurrent": EVSEMinCurrent
    }
    return j

def EVSEChargeParameterType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def MeterInfoType(MeterID:str, *, MeterReading:int|None=None, SigMeterReading:bytearray|None=None, MeterStatus:int|None=None, TMeter:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "MeterID": {"characters": [ord(c) for c in MeterID], "charactersLen": len(MeterID)}
    }
    if MeterReading is not None:
        j["MeterReading"] = MeterReading
    if SigMeterReading is not None:
        j["SigMeterReading"] = {"bytes": list(SigMeterReading), "bytesLen": len(SigMeterReading)}
    if MeterStatus is not None:
        j["MeterStatus"] = MeterStatus
    if TMeter is not None:
        j["TMeter"] = TMeter
    return j

def CertificateInstallationResType(Id:str, ResponseCode:responseCodeType, ContractSignatureCertChain:int, ContractSignatureEncryptedPrivateKey:bytearray, DHParams:bytearray, ContractID:str)->dict[str, Any]:
    j:dict[str, Any] = {
        "Id": {"characters": [ord(c) for c in Id], "charactersLen": len(Id)},
        "ResponseCode": ResponseCode.value,
        "ContractSignatureCertChain": ContractSignatureCertChain,
        "ContractSignatureEncryptedPrivateKey": {"bytes": list(ContractSignatureEncryptedPrivateKey), "bytesLen": len(ContractSignatureEncryptedPrivateKey)},
        "DHParams": {"bytes": list(DHParams), "bytesLen": len(DHParams)},
        "ContractID": {"characters": [ord(c) for c in ContractID], "charactersLen": len(ContractID)}
    }
    return j

def CableCheckReqType(DC_EVStatus:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "DC_EVStatus": DC_EVStatus
    }
    return j

def CableCheckResType(ResponseCode:responseCodeType, DC_EVSEStatus:int, EVSEProcessing:EVSEProcessingType)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "DC_EVSEStatus": DC_EVSEStatus,
        "EVSEProcessing": EVSEProcessing.value
    }
    return j

def PreChargeReqType(DC_EVStatus:int, EVTargetVoltage:int, EVTargetCurrent:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "DC_EVStatus": DC_EVStatus,
        "EVTargetVoltage": EVTargetVoltage,
        "EVTargetCurrent": EVTargetCurrent
    }
    return j

def PreChargeResType(ResponseCode:responseCodeType, DC_EVSEStatus:int, EVSEPresentVoltage:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "DC_EVSEStatus": DC_EVSEStatus,
        "EVSEPresentVoltage": EVSEPresentVoltage
    }
    return j

def CurrentDemandReqType(DC_EVStatus:int, EVTargetCurrent:int, ChargingComplete:int, EVTargetVoltage:int, *, EVMaximumVoltageLimit:int|None=None, EVMaximumCurrentLimit:int|None=None, EVMaximumPowerLimit:int|None=None, BulkChargingComplete:int|None=None, RemainingTimeToFullSoC:int|None=None, RemainingTimeToBulkSoC:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "DC_EVStatus": DC_EVStatus,
        "EVTargetCurrent": EVTargetCurrent,
        "ChargingComplete": ChargingComplete,
        "EVTargetVoltage": EVTargetVoltage
    }
    if EVMaximumVoltageLimit is not None:
        j["EVMaximumVoltageLimit"] = EVMaximumVoltageLimit
    if EVMaximumCurrentLimit is not None:
        j["EVMaximumCurrentLimit"] = EVMaximumCurrentLimit
    if EVMaximumPowerLimit is not None:
        j["EVMaximumPowerLimit"] = EVMaximumPowerLimit
    if BulkChargingComplete is not None:
        j["BulkChargingComplete"] = BulkChargingComplete
    if RemainingTimeToFullSoC is not None:
        j["RemainingTimeToFullSoC"] = RemainingTimeToFullSoC
    if RemainingTimeToBulkSoC is not None:
        j["RemainingTimeToBulkSoC"] = RemainingTimeToBulkSoC
    return j

def CurrentDemandResType(ResponseCode:responseCodeType, DC_EVSEStatus:int, EVSEPresentVoltage:int, EVSEPresentCurrent:int, EVSECurrentLimitAchieved:int, EVSEVoltageLimitAchieved:int, EVSEPowerLimitAchieved:int, *, EVSEMaximumVoltageLimit:int|None=None, EVSEMaximumCurrentLimit:int|None=None, EVSEMaximumPowerLimit:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "DC_EVSEStatus": DC_EVSEStatus,
        "EVSEPresentVoltage": EVSEPresentVoltage,
        "EVSEPresentCurrent": EVSEPresentCurrent,
        "EVSECurrentLimitAchieved": EVSECurrentLimitAchieved,
        "EVSEVoltageLimitAchieved": EVSEVoltageLimitAchieved,
        "EVSEPowerLimitAchieved": EVSEPowerLimitAchieved
    }
    if EVSEMaximumVoltageLimit is not None:
        j["EVSEMaximumVoltageLimit"] = EVSEMaximumVoltageLimit
    if EVSEMaximumCurrentLimit is not None:
        j["EVSEMaximumCurrentLimit"] = EVSEMaximumCurrentLimit
    if EVSEMaximumPowerLimit is not None:
        j["EVSEMaximumPowerLimit"] = EVSEMaximumPowerLimit
    return j

def WeldingDetectionReqType(DC_EVStatus:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "DC_EVStatus": DC_EVStatus
    }
    return j

def WeldingDetectionResType(ResponseCode:responseCodeType, DC_EVSEStatus:int, EVSEPresentVoltage:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "DC_EVSEStatus": DC_EVSEStatus,
        "EVSEPresentVoltage": EVSEPresentVoltage
    }
    return j

def SessionSetupReqType(EVCCID:bytearray)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVCCID": {"bytes": list(EVCCID), "bytesLen": len(EVCCID)}
    }
    return j

def CertificateInstallationReqType(OEMProvisioningCert:bytearray, ListOfRootCertificateIDs:int, DHParams:bytearray, *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "OEMProvisioningCert": {"bytes": list(OEMProvisioningCert), "bytesLen": len(OEMProvisioningCert)},
        "ListOfRootCertificateIDs": ListOfRootCertificateIDs,
        "DHParams": {"bytes": list(DHParams), "bytesLen": len(DHParams)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def SessionSetupResType(ResponseCode:responseCodeType, EVSEID:bytearray, *, DateTimeNow:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "EVSEID": {"bytes": list(EVSEID), "bytesLen": len(EVSEID)}
    }
    if DateTimeNow is not None:
        j["DateTimeNow"] = DateTimeNow
    return j

def ServiceDiscoveryReqType(*, ServiceScope:str|None=None, ServiceCategory:serviceCategoryType|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if ServiceScope is not None:
        j["ServiceScope"] = {"characters": [ord(c) for c in ServiceScope], "charactersLen": len(ServiceScope)}
    if ServiceCategory is not None:
        j["ServiceCategory"] = ServiceCategory.value
    return j

def ServiceDiscoveryResType(ResponseCode:responseCodeType, PaymentOptions:int, ChargeService:int, *, ServiceList:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "PaymentOptions": PaymentOptions,
        "ChargeService": ChargeService
    }
    if ServiceList is not None:
        j["ServiceList"] = ServiceList
    return j

def ServiceDetailReqType(ServiceID:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "ServiceID": ServiceID
    }
    return j

def ServiceDetailResType(ResponseCode:responseCodeType, ServiceID:int, *, ServiceParameterList:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "ServiceID": ServiceID
    }
    if ServiceParameterList is not None:
        j["ServiceParameterList"] = ServiceParameterList
    return j

def ServicePaymentSelectionReqType(SelectedPaymentOption:paymentOptionType, SelectedServiceList:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "SelectedPaymentOption": SelectedPaymentOption.value,
        "SelectedServiceList": SelectedServiceList
    }
    return j

def ServicePaymentSelectionResType(ResponseCode:responseCodeType)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value
    }
    return j

def PaymentDetailsReqType(ContractID:str, ContractSignatureCertChain:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "ContractID": {"characters": [ord(c) for c in ContractID], "charactersLen": len(ContractID)},
        "ContractSignatureCertChain": ContractSignatureCertChain
    }
    return j

def PaymentDetailsResType(ResponseCode:responseCodeType, GenChallenge:str, DateTimeNow:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "GenChallenge": {"characters": [ord(c) for c in GenChallenge], "charactersLen": len(GenChallenge)},
        "DateTimeNow": DateTimeNow
    }
    return j

def ContractAuthenticationReqType(*, Id:str|None=None, GenChallenge:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if GenChallenge is not None:
        j["GenChallenge"] = {"characters": [ord(c) for c in GenChallenge], "charactersLen": len(GenChallenge)}
    return j

def ContractAuthenticationResType(ResponseCode:responseCodeType, EVSEProcessing:EVSEProcessingType)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "EVSEProcessing": EVSEProcessing.value
    }
    return j

def ChargeParameterDiscoveryReqType(EVRequestedEnergyTransferType:EVRequestedEnergyTransferType, *, AC_EVChargeParameter:int|None=None, DC_EVChargeParameter:int|None=None, EVChargeParameter:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVRequestedEnergyTransferType": EVRequestedEnergyTransferType.value
    }
    if AC_EVChargeParameter is not None:
        j["AC_EVChargeParameter"] = AC_EVChargeParameter
    if DC_EVChargeParameter is not None:
        j["DC_EVChargeParameter"] = DC_EVChargeParameter
    if EVChargeParameter is not None:
        j["EVChargeParameter"] = EVChargeParameter
    return j

def ChargeParameterDiscoveryResType(ResponseCode:responseCodeType, EVSEProcessing:EVSEProcessingType, *, SAScheduleList:int|None=None, SASchedules:int|None=None, AC_EVSEChargeParameter:int|None=None, DC_EVSEChargeParameter:int|None=None, EVSEChargeParameter:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "EVSEProcessing": EVSEProcessing.value
    }
    if SAScheduleList is not None:
        j["SAScheduleList"] = SAScheduleList
    if SASchedules is not None:
        j["SASchedules"] = SASchedules
    if AC_EVSEChargeParameter is not None:
        j["AC_EVSEChargeParameter"] = AC_EVSEChargeParameter
    if DC_EVSEChargeParameter is not None:
        j["DC_EVSEChargeParameter"] = DC_EVSEChargeParameter
    if EVSEChargeParameter is not None:
        j["EVSEChargeParameter"] = EVSEChargeParameter
    return j

def PowerDeliveryReqType(ReadyToChargeState:int, *, ChargingProfile:int|None=None, DC_EVPowerDeliveryParameter:int|None=None, EVPowerDeliveryParameter:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ReadyToChargeState": ReadyToChargeState
    }
    if ChargingProfile is not None:
        j["ChargingProfile"] = ChargingProfile
    if DC_EVPowerDeliveryParameter is not None:
        j["DC_EVPowerDeliveryParameter"] = DC_EVPowerDeliveryParameter
    if EVPowerDeliveryParameter is not None:
        j["EVPowerDeliveryParameter"] = EVPowerDeliveryParameter
    return j

def PowerDeliveryResType(ResponseCode:responseCodeType, *, AC_EVSEStatus:int|None=None, DC_EVSEStatus:int|None=None, EVSEStatus:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value
    }
    if AC_EVSEStatus is not None:
        j["AC_EVSEStatus"] = AC_EVSEStatus
    if DC_EVSEStatus is not None:
        j["DC_EVSEStatus"] = DC_EVSEStatus
    if EVSEStatus is not None:
        j["EVSEStatus"] = EVSEStatus
    return j

def ChargingStatusReqType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def ChargingStatusResType(ResponseCode:responseCodeType, EVSEID:bytearray, SAScheduleTupleID:int, ReceiptRequired:int, AC_EVSEStatus:int, *, EVSEMaxCurrent:int|None=None, MeterInfo:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "EVSEID": {"bytes": list(EVSEID), "bytesLen": len(EVSEID)},
        "SAScheduleTupleID": SAScheduleTupleID,
        "ReceiptRequired": ReceiptRequired,
        "AC_EVSEStatus": AC_EVSEStatus
    }
    if EVSEMaxCurrent is not None:
        j["EVSEMaxCurrent"] = EVSEMaxCurrent
    if MeterInfo is not None:
        j["MeterInfo"] = MeterInfo
    return j

def MeteringReceiptReqType(SessionID:bytearray, MeterInfo:int, *, Id:str|None=None, SAScheduleTupleID:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SessionID": {"bytes": list(SessionID), "bytesLen": len(SessionID)},
        "MeterInfo": MeterInfo
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if SAScheduleTupleID is not None:
        j["SAScheduleTupleID"] = SAScheduleTupleID
    return j

def MeteringReceiptResType(ResponseCode:responseCodeType, AC_EVSEStatus:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "AC_EVSEStatus": AC_EVSEStatus
    }
    return j

def SessionStopType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def SessionStopResType(ResponseCode:responseCodeType)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value
    }
    return j

def CertificateUpdateReqType(ContractSignatureCertChain:int, ContractID:str, ListOfRootCertificateIDs:int, DHParams:bytearray, *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ContractSignatureCertChain": ContractSignatureCertChain,
        "ContractID": {"characters": [ord(c) for c in ContractID], "charactersLen": len(ContractID)},
        "ListOfRootCertificateIDs": ListOfRootCertificateIDs,
        "DHParams": {"bytes": list(DHParams), "bytesLen": len(DHParams)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def CertificateUpdateResType(Id:str, ResponseCode:responseCodeType, ContractSignatureCertChain:int, ContractSignatureEncryptedPrivateKey:bytearray, DHParams:bytearray, ContractID:str, RetryCounter:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Id": {"characters": [ord(c) for c in Id], "charactersLen": len(Id)},
        "ResponseCode": ResponseCode.value,
        "ContractSignatureCertChain": ContractSignatureCertChain,
        "ContractSignatureEncryptedPrivateKey": {"bytes": list(ContractSignatureEncryptedPrivateKey), "bytesLen": len(ContractSignatureEncryptedPrivateKey)},
        "DHParams": {"bytes": list(DHParams), "bytesLen": len(DHParams)},
        "ContractID": {"characters": [ord(c) for c in ContractID], "charactersLen": len(ContractID)},
        "RetryCounter": RetryCounter
    }
    return j

def BodyBaseType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def NotificationType(FaultCode:faultCodeType, *, FaultMsg:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "FaultCode": FaultCode.value
    }
    if FaultMsg is not None:
        j["FaultMsg"] = {"characters": [ord(c) for c in FaultMsg], "charactersLen": len(FaultMsg)}
    return j

def SignatureType(SignedInfo:int, SignatureValue:int, *, Id:str|None=None, KeyInfo:int|None=None, Object:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SignedInfo": SignedInfo,
        "SignatureValue": SignatureValue
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if KeyInfo is not None:
        j["KeyInfo"] = KeyInfo
    if Object is not None:
        j["Object"] = Object
    return j

def MessageHeaderType(SessionID:bytearray, *, Notification:int|None=None, Signature:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SessionID": {"bytes": list(SessionID), "bytesLen": len(SessionID)}
    }
    if Notification is not None:
        j["Notification"] = Notification
    if Signature is not None:
        j["Signature"] = Signature
    return j

def BodyType(*, BodyElement:int|None=None, CableCheckReq:int|None=None, CableCheckRes:int|None=None, CertificateInstallationReq:int|None=None, CertificateInstallationRes:int|None=None, CertificateUpdateReq:int|None=None, CertificateUpdateRes:int|None=None, ChargeParameterDiscoveryReq:int|None=None, ChargeParameterDiscoveryRes:int|None=None, ChargingStatusReq:int|None=None, ChargingStatusRes:int|None=None, ContractAuthenticationReq:int|None=None, ContractAuthenticationRes:int|None=None, CurrentDemandReq:int|None=None, CurrentDemandRes:int|None=None, MeteringReceiptReq:int|None=None, MeteringReceiptRes:int|None=None, PaymentDetailsReq:int|None=None, PaymentDetailsRes:int|None=None, PowerDeliveryReq:int|None=None, PowerDeliveryRes:int|None=None, PreChargeReq:int|None=None, PreChargeRes:int|None=None, ServiceDetailReq:int|None=None, ServiceDetailRes:int|None=None, ServiceDiscoveryReq:int|None=None, ServiceDiscoveryRes:int|None=None, ServicePaymentSelectionReq:int|None=None, ServicePaymentSelectionRes:int|None=None, SessionSetupReq:int|None=None, SessionSetupRes:int|None=None, SessionStopReq:int|None=None, SessionStopRes:int|None=None, WeldingDetectionReq:int|None=None, WeldingDetectionRes:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if BodyElement is not None:
        j["BodyElement"] = BodyElement
    if CableCheckReq is not None:
        j["CableCheckReq"] = CableCheckReq
    if CableCheckRes is not None:
        j["CableCheckRes"] = CableCheckRes
    if CertificateInstallationReq is not None:
        j["CertificateInstallationReq"] = CertificateInstallationReq
    if CertificateInstallationRes is not None:
        j["CertificateInstallationRes"] = CertificateInstallationRes
    if CertificateUpdateReq is not None:
        j["CertificateUpdateReq"] = CertificateUpdateReq
    if CertificateUpdateRes is not None:
        j["CertificateUpdateRes"] = CertificateUpdateRes
    if ChargeParameterDiscoveryReq is not None:
        j["ChargeParameterDiscoveryReq"] = ChargeParameterDiscoveryReq
    if ChargeParameterDiscoveryRes is not None:
        j["ChargeParameterDiscoveryRes"] = ChargeParameterDiscoveryRes
    if ChargingStatusReq is not None:
        j["ChargingStatusReq"] = ChargingStatusReq
    if ChargingStatusRes is not None:
        j["ChargingStatusRes"] = ChargingStatusRes
    if ContractAuthenticationReq is not None:
        j["ContractAuthenticationReq"] = ContractAuthenticationReq
    if ContractAuthenticationRes is not None:
        j["ContractAuthenticationRes"] = ContractAuthenticationRes
    if CurrentDemandReq is not None:
        j["CurrentDemandReq"] = CurrentDemandReq
    if CurrentDemandRes is not None:
        j["CurrentDemandRes"] = CurrentDemandRes
    if MeteringReceiptReq is not None:
        j["MeteringReceiptReq"] = MeteringReceiptReq
    if MeteringReceiptRes is not None:
        j["MeteringReceiptRes"] = MeteringReceiptRes
    if PaymentDetailsReq is not None:
        j["PaymentDetailsReq"] = PaymentDetailsReq
    if PaymentDetailsRes is not None:
        j["PaymentDetailsRes"] = PaymentDetailsRes
    if PowerDeliveryReq is not None:
        j["PowerDeliveryReq"] = PowerDeliveryReq
    if PowerDeliveryRes is not None:
        j["PowerDeliveryRes"] = PowerDeliveryRes
    if PreChargeReq is not None:
        j["PreChargeReq"] = PreChargeReq
    if PreChargeRes is not None:
        j["PreChargeRes"] = PreChargeRes
    if ServiceDetailReq is not None:
        j["ServiceDetailReq"] = ServiceDetailReq
    if ServiceDetailRes is not None:
        j["ServiceDetailRes"] = ServiceDetailRes
    if ServiceDiscoveryReq is not None:
        j["ServiceDiscoveryReq"] = ServiceDiscoveryReq
    if ServiceDiscoveryRes is not None:
        j["ServiceDiscoveryRes"] = ServiceDiscoveryRes
    if ServicePaymentSelectionReq is not None:
        j["ServicePaymentSelectionReq"] = ServicePaymentSelectionReq
    if ServicePaymentSelectionRes is not None:
        j["ServicePaymentSelectionRes"] = ServicePaymentSelectionRes
    if SessionSetupReq is not None:
        j["SessionSetupReq"] = SessionSetupReq
    if SessionSetupRes is not None:
        j["SessionSetupRes"] = SessionSetupRes
    if SessionStopReq is not None:
        j["SessionStopReq"] = SessionStopReq
    if SessionStopRes is not None:
        j["SessionStopRes"] = SessionStopRes
    if WeldingDetectionReq is not None:
        j["WeldingDetectionReq"] = WeldingDetectionReq
    if WeldingDetectionRes is not None:
        j["WeldingDetectionRes"] = WeldingDetectionRes
    return j

def V2G_Message(Header:int, Body:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "Body": Body
    }
    return j
