"""
Enum tables for the ISO 15118-20 Common Messages Namespace (consumed by tools/codegen/fixture_emitter).

Auto-generated by tools/codegen/v2gjson_emitter.py. DO NOT EDIT.
"""

from enum import Enum


# skipped iso20_generatedFunctionNumbersType: enum iso20_generatedFunctionNumbersType member 'iso20_AuthorizationReq' does not start with expected prefix 'iso20_generatedFunctionNumbersType_'

class powerToleranceAcceptanceType(Enum):
    PowerToleranceNotConfirmed = 0
    PowerToleranceConfirmed = 1


class evseNotificationType(Enum):
    Pause = 0
    ExitStandby = 1
    Terminate = 2
    ScheduleRenegotiation = 3
    ServiceRenegotiation = 4
    MeteringConfirmation = 5


class ecdhCurveType(Enum):
    SECP521 = 0
    X448 = 1


class responseCodeType(Enum):
    OK = 0
    OK_CertificateExpiresSoon = 1
    OK_NewSessionEstablished = 2
    OK_OldSessionJoined = 3
    OK_PowerToleranceConfirmed = 4
    WARNING_AuthorizationSelectionInvalid = 5
    WARNING_CertificateExpired = 6
    WARNING_CertificateNotYetValid = 7
    WARNING_CertificateRevoked = 8
    WARNING_CertificateValidationError = 9
    WARNING_ChallengeInvalid = 10
    WARNING_EIMAuthorizationFailure = 11
    WARNING_eMSPUnknown = 12
    WARNING_EVPowerProfileViolation = 13
    WARNING_GeneralPnCAuthorizationError = 14
    WARNING_NoCertificateAvailable = 15
    WARNING_NoContractMatchingPCIDFound = 16
    WARNING_PowerToleranceNotConfirmed = 17
    WARNING_ScheduleRenegotiationFailed = 18
    WARNING_StandbyNotAllowed = 19
    WARNING_WPT = 20
    FAILED = 21
    FAILED_AssociationError = 22
    FAILED_ContactorError = 23
    FAILED_EVPowerProfileInvalid = 24
    FAILED_EVPowerProfileViolation = 25
    FAILED_MeteringSignatureNotValid = 26
    FAILED_NoEnergyTransferServiceSelected = 27
    FAILED_NoServiceRenegotiationSupported = 28
    FAILED_PauseNotAllowed = 29
    FAILED_PowerDeliveryNotApplied = 30
    FAILED_PowerToleranceNotConfirmed = 31
    FAILED_ScheduleRenegotiation = 32
    FAILED_ScheduleSelectionInvalid = 33
    FAILED_SequenceError = 34
    FAILED_ServiceIDInvalid = 35
    FAILED_ServiceSelectionInvalid = 36
    FAILED_SignatureError = 37
    FAILED_UnknownSession = 38
    FAILED_WrongChargeParameter = 39


class chargingSessionType(Enum):
    Pause = 0
    Terminate = 1
    ServiceRenegotiation = 2


class evCheckInStatusType(Enum):
    CheckIn = 0
    Processing = 1
    Completed = 2


class evCheckOutStatusType(Enum):
    CheckOut = 0
    Processing = 1
    Completed = 2


class authorizationType(Enum):
    EIM = 0
    PnC = 1


class processingType(Enum):
    Finished = 0
    Ongoing = 1
    Ongoing_WaitingForCustomerInteraction = 2


class chargeProgressType(Enum):
    Start = 0
    Stop = 1
    Standby = 2
    ScheduleRenegotiation = 3


class parkingMethodType(Enum):
    AutoParking = 0
    MVGuideManual = 1
    Manual = 2


class evseCheckOutStatusType(Enum):
    Scheduled = 0
    Completed = 1


class channelSelectionType(Enum):
    Charge = 0
    Discharge = 1
