"""
Constructors and enum tables for the ISO 15118-2 Namespace.

Auto-generated by tools/codegen/v2gjson_emitter.py. DO NOT EDIT.
"""

from enum import Enum
from typing import Any


# skipped iso2_generatedFunctionNumbersType: enum iso2_generatedFunctionNumbersType member 'iso2_AC_EVChargeParameter' does not start with expected prefix 'iso2_generatedFunctionNumbersType_'

class costKindType(Enum):
    relativePricePercentage = 0
    RenewableGenerationPercentage = 1
    CarbonDioxideEmission = 2


class unitSymbolType(Enum):
    h = 0
    m = 1
    s = 2
    A = 3
    V = 4
    W = 5
    Wh = 6


class DC_EVErrorCodeType(Enum):
    NO_ERROR = 0
    FAILED_RESSTemperatureInhibit = 1
    FAILED_EVShiftPosition = 2
    FAILED_ChargerConnectorLockFault = 3
    FAILED_EVRESSMalfunction = 4
    FAILED_ChargingCurrentdifferential = 5
    FAILED_ChargingVoltageOutOfRange = 6
    Reserved_A = 7
    Reserved_B = 8
    Reserved_C = 9
    FAILED_ChargingSystemIncompatibility = 10
    NoData = 11


class faultCodeType(Enum):
    ParsingError = 0
    NoTLSRootCertificatAvailable = 1
    UnknownError = 2


class EVSENotificationType(Enum):
    None_ = 0
    StopCharging = 1
    ReNegotiation = 2


class isolationLevelType(Enum):
    Invalid = 0
    Valid = 1
    Warning = 2
    Fault = 3
    No_IMD = 4


class serviceCategoryType(Enum):
    EVCharging = 0
    Internet = 1
    ContractCertificate = 2
    OtherCustom = 3


class DC_EVSEStatusCodeType(Enum):
    EVSE_NotReady = 0
    EVSE_Ready = 1
    EVSE_Shutdown = 2
    EVSE_UtilityInterruptEvent = 3
    EVSE_IsolationMonitoringActive = 4
    EVSE_EmergencyShutdown = 5
    EVSE_Malfunction = 6
    Reserved_8 = 7
    Reserved_9 = 8
    Reserved_A = 9
    Reserved_B = 10
    Reserved_C = 11


class chargeProgressType(Enum):
    Start = 0
    Stop = 1
    Renegotiate = 2


class responseCodeType(Enum):
    OK = 0
    OK_NewSessionEstablished = 1
    OK_OldSessionJoined = 2
    OK_CertificateExpiresSoon = 3
    FAILED = 4
    FAILED_SequenceError = 5
    FAILED_ServiceIDInvalid = 6
    FAILED_UnknownSession = 7
    FAILED_ServiceSelectionInvalid = 8
    FAILED_PaymentSelectionInvalid = 9
    FAILED_CertificateExpired = 10
    FAILED_SignatureError = 11
    FAILED_NoCertificateAvailable = 12
    FAILED_CertChainError = 13
    FAILED_ChallengeInvalid = 14
    FAILED_ContractCanceled = 15
    FAILED_WrongChargeParameter = 16
    FAILED_PowerDeliveryNotApplied = 17
    FAILED_TariffSelectionInvalid = 18
    FAILED_ChargingProfileInvalid = 19
    FAILED_MeteringSignatureNotValid = 20
    FAILED_NoChargeServiceSelected = 21
    FAILED_WrongEnergyTransferMode = 22
    FAILED_ContactorError = 23
    FAILED_CertificateNotAllowedAtThisEVSE = 24
    FAILED_CertificateRevoked = 25


class paymentOptionType(Enum):
    Contract = 0
    ExternalPayment = 1


class chargingSessionType(Enum):
    Terminate = 0
    Pause = 1


class EnergyTransferModeType(Enum):
    AC_single_phase_core = 0
    AC_three_phase_core = 1
    DC_core = 2
    DC_extended = 3
    DC_combo_core = 4
    DC_unique = 5


class EVSEProcessingType(Enum):
    Finished = 0
    Ongoing = 1
    Ongoing_WaitingForCustomerInteraction = 2


def CostType(costKind:costKindType, amount:int, *, amountMultiplier:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "costKind": costKind.value,
        "amount": amount
    }
    if amountMultiplier is not None:
        j["amountMultiplier"] = amountMultiplier
    return j

def TransformType(Algorithm:str, *, ANY:bytearray|None=None, XPath:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    if XPath is not None:
        j["XPath"] = {"characters": [ord(c) for c in XPath], "charactersLen": len(XPath)}
    return j

def IntervalType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def TransformsType(Transform:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "Transform": Transform
    }
    return j

def DSAKeyValueType(Y:bytearray, *, P:bytearray|None=None, Q:bytearray|None=None, G:bytearray|None=None, J:bytearray|None=None, Seed:bytearray|None=None, PgenCounter:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Y": {"bytes": list(Y), "bytesLen": len(Y)}
    }
    if P is not None:
        j["P"] = {"bytes": list(P), "bytesLen": len(P)}
    if Q is not None:
        j["Q"] = {"bytes": list(Q), "bytesLen": len(Q)}
    if G is not None:
        j["G"] = {"bytes": list(G), "bytesLen": len(G)}
    if J is not None:
        j["J"] = {"bytes": list(J), "bytesLen": len(J)}
    if Seed is not None:
        j["Seed"] = {"bytes": list(Seed), "bytesLen": len(Seed)}
    if PgenCounter is not None:
        j["PgenCounter"] = {"bytes": list(PgenCounter), "bytesLen": len(PgenCounter)}
    return j

def X509IssuerSerialType(X509IssuerName:str, X509SerialNumber:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "X509IssuerName": {"characters": [ord(c) for c in X509IssuerName], "charactersLen": len(X509IssuerName)},
        "X509SerialNumber": X509SerialNumber
    }
    return j

def RelativeTimeIntervalType(start:int, *, duration:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "start": start
    }
    if duration is not None:
        j["duration"] = duration
    return j

def DigestMethodType(Algorithm:str, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def RSAKeyValueType(Modulus:bytearray, Exponent:bytearray)->dict[str, Any]:
    j:dict[str, Any] = {
        "Modulus": {"bytes": list(Modulus), "bytesLen": len(Modulus)},
        "Exponent": {"bytes": list(Exponent), "bytesLen": len(Exponent)}
    }
    return j

def CanonicalizationMethodType(Algorithm:str, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def SignatureMethodType(Algorithm:str, *, HMACOutputLength:dict[str, Any]|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if HMACOutputLength is not None:
        j["HMACOutputLength"] = HMACOutputLength
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def KeyValueType(*, DSAKeyValue:dict[str, Any]|None=None, RSAKeyValue:dict[str, Any]|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if DSAKeyValue is not None:
        j["DSAKeyValue"] = DSAKeyValue
    if RSAKeyValue is not None:
        j["RSAKeyValue"] = RSAKeyValue
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def PhysicalValueType(Multiplier:int, Unit:unitSymbolType, Value:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Multiplier": Multiplier,
        "Unit": Unit.value,
        "Value": Value
    }
    return j

def ConsumptionCostType(startValue:dict[str, Any], Cost:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "startValue": startValue,
        "Cost": {"arrayLen": len(Cost), "array": Cost}
    }
    return j

def PMaxScheduleEntryType(PMax:dict[str, Any], *, RelativeTimeInterval:dict[str, Any]|None=None, TimeInterval:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "PMax": PMax
    }
    if RelativeTimeInterval is not None:
        j["RelativeTimeInterval"] = RelativeTimeInterval
    if TimeInterval is not None:
        j["TimeInterval"] = TimeInterval
    return j

def SalesTariffEntryType(ConsumptionCost:list[dict[str, Any]], *, RelativeTimeInterval:dict[str, Any]|None=None, TimeInterval:dict[str, Any]|None=None, EPriceLevel:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ConsumptionCost": {"arrayLen": len(ConsumptionCost), "array": ConsumptionCost}
    }
    if RelativeTimeInterval is not None:
        j["RelativeTimeInterval"] = RelativeTimeInterval
    if TimeInterval is not None:
        j["TimeInterval"] = TimeInterval
    if EPriceLevel is not None:
        j["EPriceLevel"] = EPriceLevel
    return j

def ParameterType(Name:str, *, boolValue:int|None=None, byteValue:int|None=None, shortValue:int|None=None, intValue:int|None=None, physicalValue:dict[str, Any]|None=None, stringValue:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Name": {"characters": [ord(c) for c in Name], "charactersLen": len(Name)}
    }
    if boolValue is not None:
        j["boolValue"] = boolValue
    if byteValue is not None:
        j["byteValue"] = byteValue
    if shortValue is not None:
        j["shortValue"] = shortValue
    if intValue is not None:
        j["intValue"] = intValue
    if physicalValue is not None:
        j["physicalValue"] = physicalValue
    if stringValue is not None:
        j["stringValue"] = {"characters": [ord(c) for c in stringValue], "charactersLen": len(stringValue)}
    return j

def PMaxScheduleType(PMaxScheduleEntry:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "PMaxScheduleEntry": {"arrayLen": len(PMaxScheduleEntry), "array": PMaxScheduleEntry}
    }
    return j

def ReferenceType(DigestMethod:dict[str, Any], DigestValue:bytearray, *, Id:str|None=None, Type:str|None=None, URI:str|None=None, Transforms:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "DigestMethod": DigestMethod,
        "DigestValue": {"bytes": list(DigestValue), "bytesLen": len(DigestValue)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if Type is not None:
        j["Type"] = {"characters": [ord(c) for c in Type], "charactersLen": len(Type)}
    if URI is not None:
        j["URI"] = {"characters": [ord(c) for c in URI], "charactersLen": len(URI)}
    if Transforms is not None:
        j["Transforms"] = Transforms
    return j

def RetrievalMethodType(*, Type:str|None=None, URI:str|None=None, Transforms:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Type is not None:
        j["Type"] = {"characters": [ord(c) for c in Type], "charactersLen": len(Type)}
    if URI is not None:
        j["URI"] = {"characters": [ord(c) for c in URI], "charactersLen": len(URI)}
    if Transforms is not None:
        j["Transforms"] = Transforms
    return j

def SalesTariffType(SalesTariffID:int, SalesTariffEntry:list[dict[str, Any]], *, Id:str|None=None, SalesTariffDescription:str|None=None, NumEPriceLevels:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SalesTariffID": SalesTariffID,
        "SalesTariffEntry": {"arrayLen": len(SalesTariffEntry), "array": SalesTariffEntry}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if SalesTariffDescription is not None:
        j["SalesTariffDescription"] = {"characters": [ord(c) for c in SalesTariffDescription], "charactersLen": len(SalesTariffDescription)}
    if NumEPriceLevels is not None:
        j["NumEPriceLevels"] = NumEPriceLevels
    return j

def X509DataType(*, X509IssuerSerial:dict[str, Any]|None=None, X509SKI:bytearray|None=None, X509SubjectName:str|None=None, X509Certificate:bytearray|None=None, X509CRL:bytearray|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if X509IssuerSerial is not None:
        j["X509IssuerSerial"] = X509IssuerSerial
    if X509SKI is not None:
        j["X509SKI"] = {"bytes": list(X509SKI), "bytesLen": len(X509SKI)}
    if X509SubjectName is not None:
        j["X509SubjectName"] = {"characters": [ord(c) for c in X509SubjectName], "charactersLen": len(X509SubjectName)}
    if X509Certificate is not None:
        j["X509Certificate"] = {"bytes": list(X509Certificate), "bytesLen": len(X509Certificate)}
    if X509CRL is not None:
        j["X509CRL"] = {"bytes": list(X509CRL), "bytesLen": len(X509CRL)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def PGPDataType(*, choice_1:int|None=None, choice_2:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if choice_1 is not None:
        j["choice_1"] = choice_1
    if choice_2 is not None:
        j["choice_2"] = choice_2
    return j

def SPKIDataType(SPKISexp:bytearray, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SPKISexp": {"bytes": list(SPKISexp), "bytesLen": len(SPKISexp)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def SignedInfoType(CanonicalizationMethod:dict[str, Any], SignatureMethod:dict[str, Any], Reference:list[dict[str, Any]], *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "CanonicalizationMethod": CanonicalizationMethod,
        "SignatureMethod": SignatureMethod,
        "Reference": {"arrayLen": len(Reference), "array": Reference}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def ProfileEntryType(ChargingProfileEntryStart:int, ChargingProfileEntryMaxPower:dict[str, Any], *, ChargingProfileEntryMaxNumberOfPhasesInUse:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ChargingProfileEntryStart": ChargingProfileEntryStart,
        "ChargingProfileEntryMaxPower": ChargingProfileEntryMaxPower
    }
    if ChargingProfileEntryMaxNumberOfPhasesInUse is not None:
        j["ChargingProfileEntryMaxNumberOfPhasesInUse"] = ChargingProfileEntryMaxNumberOfPhasesInUse
    return j

def DC_EVStatusType(EVReady:int, EVErrorCode:DC_EVErrorCodeType, EVRESSSOC:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVReady": EVReady,
        "EVErrorCode": EVErrorCode.value,
        "EVRESSSOC": EVRESSSOC
    }
    return j

def ParameterSetType(ParameterSetID:int, Parameter:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "ParameterSetID": ParameterSetID,
        "Parameter": {"arrayLen": len(Parameter), "array": Parameter}
    }
    return j

def SAScheduleTupleType(SAScheduleTupleID:int, PMaxSchedule:dict[str, Any], *, SalesTariff:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SAScheduleTupleID": SAScheduleTupleID,
        "PMaxSchedule": PMaxSchedule
    }
    if SalesTariff is not None:
        j["SalesTariff"] = SalesTariff
    return j

def SelectedServiceType(ServiceID:int, *, ParameterSetID:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ServiceID": ServiceID
    }
    if ParameterSetID is not None:
        j["ParameterSetID"] = ParameterSetID
    return j

def ServiceType(ServiceID:int, ServiceCategory:serviceCategoryType, FreeService:int, *, ServiceName:str|None=None, ServiceScope:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ServiceID": ServiceID,
        "ServiceCategory": ServiceCategory.value,
        "FreeService": FreeService
    }
    if ServiceName is not None:
        j["ServiceName"] = {"characters": [ord(c) for c in ServiceName], "charactersLen": len(ServiceName)}
    if ServiceScope is not None:
        j["ServiceScope"] = {"characters": [ord(c) for c in ServiceScope], "charactersLen": len(ServiceScope)}
    return j

def SignatureValueType(CONTENT:bytearray, *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "CONTENT": {"bytes": list(CONTENT), "bytesLen": len(CONTENT)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def SubCertificatesType(Certificate:list[bytearray])->dict[str, Any]:
    j:dict[str, Any] = {
        "Certificate": {"arrayLen": len(Certificate), "array": [{"bytes": list(_b), "bytesLen": len(_b)} for _b in Certificate]}
    }
    return j

def KeyInfoType(*, Id:str|None=None, KeyName:str|None=None, KeyValue:dict[str, Any]|None=None, RetrievalMethod:dict[str, Any]|None=None, X509Data:dict[str, Any]|None=None, PGPData:dict[str, Any]|None=None, SPKIData:dict[str, Any]|None=None, MgmtData:str|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if KeyName is not None:
        j["KeyName"] = {"characters": [ord(c) for c in KeyName], "charactersLen": len(KeyName)}
    if KeyValue is not None:
        j["KeyValue"] = KeyValue
    if RetrievalMethod is not None:
        j["RetrievalMethod"] = RetrievalMethod
    if X509Data is not None:
        j["X509Data"] = X509Data
    if PGPData is not None:
        j["PGPData"] = PGPData
    if SPKIData is not None:
        j["SPKIData"] = SPKIData
    if MgmtData is not None:
        j["MgmtData"] = {"characters": [ord(c) for c in MgmtData], "charactersLen": len(MgmtData)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def ObjectType(*, Encoding:str|None=None, Id:str|None=None, MimeType:str|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Encoding is not None:
        j["Encoding"] = {"characters": [ord(c) for c in Encoding], "charactersLen": len(Encoding)}
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if MimeType is not None:
        j["MimeType"] = {"characters": [ord(c) for c in MimeType], "charactersLen": len(MimeType)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def SupportedEnergyTransferModeType(EnergyTransferMode:list[EnergyTransferModeType])->dict[str, Any]:
    j:dict[str, Any] = {
        "EnergyTransferMode": {"arrayLen": len(EnergyTransferMode), "array": [_v.value for _v in EnergyTransferMode]}
    }
    return j

def CertificateChainType(Certificate:bytearray, *, Id:str|None=None, SubCertificates:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Certificate": {"bytes": list(Certificate), "bytesLen": len(Certificate)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if SubCertificates is not None:
        j["SubCertificates"] = SubCertificates
    return j

def BodyBaseType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def NotificationType(FaultCode:faultCodeType, *, FaultMsg:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "FaultCode": FaultCode.value
    }
    if FaultMsg is not None:
        j["FaultMsg"] = {"characters": [ord(c) for c in FaultMsg], "charactersLen": len(FaultMsg)}
    return j

def DC_EVSEStatusType(NotificationMaxDelay:int, EVSENotification:EVSENotificationType, EVSEStatusCode:DC_EVSEStatusCodeType, *, EVSEIsolationStatus:isolationLevelType|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "NotificationMaxDelay": NotificationMaxDelay,
        "EVSENotification": EVSENotification.value,
        "EVSEStatusCode": EVSEStatusCode.value
    }
    if EVSEIsolationStatus is not None:
        j["EVSEIsolationStatus"] = EVSEIsolationStatus.value
    return j

def SelectedServiceListType(SelectedService:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "SelectedService": {"arrayLen": len(SelectedService), "array": SelectedService}
    }
    return j

def PaymentOptionListType(PaymentOption:list[paymentOptionType])->dict[str, Any]:
    j:dict[str, Any] = {
        "PaymentOption": {"arrayLen": len(PaymentOption), "array": [_v.value for _v in PaymentOption]}
    }
    return j

def SignatureType(SignedInfo:dict[str, Any], SignatureValue:dict[str, Any], *, Id:str|None=None, KeyInfo:dict[str, Any]|None=None, Object:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SignedInfo": SignedInfo,
        "SignatureValue": SignatureValue
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if KeyInfo is not None:
        j["KeyInfo"] = KeyInfo
    if Object is not None:
        j["Object"] = Object
    return j

def ChargingProfileType(ProfileEntry:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "ProfileEntry": {"arrayLen": len(ProfileEntry), "array": ProfileEntry}
    }
    return j

def ServiceParameterListType(ParameterSet:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "ParameterSet": {"arrayLen": len(ParameterSet), "array": ParameterSet}
    }
    return j

def ListOfRootCertificateIDsType(RootCertificateID:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "RootCertificateID": {"arrayLen": len(RootCertificateID), "array": RootCertificateID}
    }
    return j

def AC_EVChargeParameterType(EAmount:dict[str, Any], EVMaxVoltage:dict[str, Any], EVMaxCurrent:dict[str, Any], EVMinCurrent:dict[str, Any], *, DepartureTime:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EAmount": EAmount,
        "EVMaxVoltage": EVMaxVoltage,
        "EVMaxCurrent": EVMaxCurrent,
        "EVMinCurrent": EVMinCurrent
    }
    if DepartureTime is not None:
        j["DepartureTime"] = DepartureTime
    return j

def DC_EVChargeParameterType(DC_EVStatus:dict[str, Any], EVMaximumCurrentLimit:dict[str, Any], EVMaximumVoltageLimit:dict[str, Any], *, DepartureTime:int|None=None, EVMaximumPowerLimit:dict[str, Any]|None=None, EVEnergyCapacity:dict[str, Any]|None=None, EVEnergyRequest:dict[str, Any]|None=None, FullSOC:int|None=None, BulkSOC:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "DC_EVStatus": DC_EVStatus,
        "EVMaximumCurrentLimit": EVMaximumCurrentLimit,
        "EVMaximumVoltageLimit": EVMaximumVoltageLimit
    }
    if DepartureTime is not None:
        j["DepartureTime"] = DepartureTime
    if EVMaximumPowerLimit is not None:
        j["EVMaximumPowerLimit"] = EVMaximumPowerLimit
    if EVEnergyCapacity is not None:
        j["EVEnergyCapacity"] = EVEnergyCapacity
    if EVEnergyRequest is not None:
        j["EVEnergyRequest"] = EVEnergyRequest
    if FullSOC is not None:
        j["FullSOC"] = FullSOC
    if BulkSOC is not None:
        j["BulkSOC"] = BulkSOC
    return j

def EVChargeParameterType(AC_EVChargeParameter:dict[str, Any], DC_EVChargeParameter:dict[str, Any], *, DepartureTime:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "AC_EVChargeParameter": AC_EVChargeParameter,
        "DC_EVChargeParameter": DC_EVChargeParameter
    }
    if DepartureTime is not None:
        j["DepartureTime"] = DepartureTime
    return j

def SASchedulesType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def SAScheduleListType(SAScheduleTuple:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "SAScheduleTuple": {"arrayLen": len(SAScheduleTuple), "array": SAScheduleTuple}
    }
    return j

def ChargeServiceType(ServiceID:int, ServiceCategory:serviceCategoryType, FreeService:int, SupportedEnergyTransferMode:dict[str, Any], *, ServiceName:str|None=None, ServiceScope:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ServiceID": ServiceID,
        "ServiceCategory": ServiceCategory.value,
        "FreeService": FreeService,
        "SupportedEnergyTransferMode": SupportedEnergyTransferMode
    }
    if ServiceName is not None:
        j["ServiceName"] = {"characters": [ord(c) for c in ServiceName], "charactersLen": len(ServiceName)}
    if ServiceScope is not None:
        j["ServiceScope"] = {"characters": [ord(c) for c in ServiceScope], "charactersLen": len(ServiceScope)}
    return j

def EVPowerDeliveryParameterType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def DC_EVPowerDeliveryParameterType(DC_EVStatus:dict[str, Any], ChargingComplete:int, *, BulkChargingComplete:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "DC_EVStatus": DC_EVStatus,
        "ChargingComplete": ChargingComplete
    }
    if BulkChargingComplete is not None:
        j["BulkChargingComplete"] = BulkChargingComplete
    return j

def ContractSignatureEncryptedPrivateKeyType(Id:str, CONTENT:bytearray)->dict[str, Any]:
    j:dict[str, Any] = {
        "Id": {"characters": [ord(c) for c in Id], "charactersLen": len(Id)},
        "CONTENT": {"bytes": list(CONTENT), "bytesLen": len(CONTENT)}
    }
    return j

def EVSEChargeParameterType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def DC_EVSEChargeParameterType(DC_EVSEStatus:dict[str, Any], EVSEMaximumCurrentLimit:dict[str, Any], EVSEMaximumPowerLimit:dict[str, Any], EVSEMaximumVoltageLimit:dict[str, Any], EVSEMinimumCurrentLimit:dict[str, Any], EVSEMinimumVoltageLimit:dict[str, Any], EVSEPeakCurrentRipple:dict[str, Any], *, EVSECurrentRegulationTolerance:dict[str, Any]|None=None, EVSEEnergyToBeDelivered:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "DC_EVSEStatus": DC_EVSEStatus,
        "EVSEMaximumCurrentLimit": EVSEMaximumCurrentLimit,
        "EVSEMaximumPowerLimit": EVSEMaximumPowerLimit,
        "EVSEMaximumVoltageLimit": EVSEMaximumVoltageLimit,
        "EVSEMinimumCurrentLimit": EVSEMinimumCurrentLimit,
        "EVSEMinimumVoltageLimit": EVSEMinimumVoltageLimit,
        "EVSEPeakCurrentRipple": EVSEPeakCurrentRipple
    }
    if EVSECurrentRegulationTolerance is not None:
        j["EVSECurrentRegulationTolerance"] = EVSECurrentRegulationTolerance
    if EVSEEnergyToBeDelivered is not None:
        j["EVSEEnergyToBeDelivered"] = EVSEEnergyToBeDelivered
    return j

def ServiceListType(Service:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "Service": {"arrayLen": len(Service), "array": Service}
    }
    return j

def DiffieHellmanPublickeyType(Id:str, CONTENT:bytearray)->dict[str, Any]:
    j:dict[str, Any] = {
        "Id": {"characters": [ord(c) for c in Id], "charactersLen": len(Id)},
        "CONTENT": {"bytes": list(CONTENT), "bytesLen": len(CONTENT)}
    }
    return j

def EMAIDType(Id:str, CONTENT:str)->dict[str, Any]:
    j:dict[str, Any] = {
        "Id": {"characters": [ord(c) for c in Id], "charactersLen": len(Id)},
        "CONTENT": {"characters": [ord(c) for c in CONTENT], "charactersLen": len(CONTENT)}
    }
    return j

def AC_EVSEStatusType(NotificationMaxDelay:int, EVSENotification:EVSENotificationType, RCD:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "NotificationMaxDelay": NotificationMaxDelay,
        "EVSENotification": EVSENotification.value,
        "RCD": RCD
    }
    return j

def EVSEStatusType(NotificationMaxDelay:int, EVSENotification:EVSENotificationType, AC_EVSEStatus:dict[str, Any], DC_EVSEStatus:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "NotificationMaxDelay": NotificationMaxDelay,
        "EVSENotification": EVSENotification.value,
        "AC_EVSEStatus": AC_EVSEStatus,
        "DC_EVSEStatus": DC_EVSEStatus
    }
    return j

def AC_EVSEChargeParameterType(AC_EVSEStatus:dict[str, Any], EVSENominalVoltage:dict[str, Any], EVSEMaxCurrent:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "AC_EVSEStatus": AC_EVSEStatus,
        "EVSENominalVoltage": EVSENominalVoltage,
        "EVSEMaxCurrent": EVSEMaxCurrent
    }
    return j

def MeterInfoType(MeterID:str, *, MeterReading:int|None=None, SigMeterReading:bytearray|None=None, MeterStatus:int|None=None, TMeter:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "MeterID": {"characters": [ord(c) for c in MeterID], "charactersLen": len(MeterID)}
    }
    if MeterReading is not None:
        j["MeterReading"] = MeterReading
    if SigMeterReading is not None:
        j["SigMeterReading"] = {"bytes": list(SigMeterReading), "bytesLen": len(SigMeterReading)}
    if MeterStatus is not None:
        j["MeterStatus"] = MeterStatus
    if TMeter is not None:
        j["TMeter"] = TMeter
    return j

def MessageHeaderType(SessionID:bytearray, *, Notification:dict[str, Any]|None=None, Signature:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SessionID": {"bytes": list(SessionID), "bytesLen": len(SessionID)}
    }
    if Notification is not None:
        j["Notification"] = Notification
    if Signature is not None:
        j["Signature"] = Signature
    return j

def PowerDeliveryReqType(ChargeProgress:chargeProgressType, SAScheduleTupleID:int, *, ChargingProfile:dict[str, Any]|None=None, DC_EVPowerDeliveryParameter:dict[str, Any]|None=None, EVPowerDeliveryParameter:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ChargeProgress": ChargeProgress.value,
        "SAScheduleTupleID": SAScheduleTupleID
    }
    if ChargingProfile is not None:
        j["ChargingProfile"] = ChargingProfile
    if DC_EVPowerDeliveryParameter is not None:
        j["DC_EVPowerDeliveryParameter"] = DC_EVPowerDeliveryParameter
    if EVPowerDeliveryParameter is not None:
        j["EVPowerDeliveryParameter"] = EVPowerDeliveryParameter
    return j

def CurrentDemandResType(ResponseCode:responseCodeType, DC_EVSEStatus:dict[str, Any], EVSEPresentVoltage:dict[str, Any], EVSEPresentCurrent:dict[str, Any], EVSECurrentLimitAchieved:int, EVSEVoltageLimitAchieved:int, EVSEPowerLimitAchieved:int, EVSEID:str, SAScheduleTupleID:int, *, EVSEMaximumVoltageLimit:dict[str, Any]|None=None, EVSEMaximumCurrentLimit:dict[str, Any]|None=None, EVSEMaximumPowerLimit:dict[str, Any]|None=None, MeterInfo:dict[str, Any]|None=None, ReceiptRequired:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "DC_EVSEStatus": DC_EVSEStatus,
        "EVSEPresentVoltage": EVSEPresentVoltage,
        "EVSEPresentCurrent": EVSEPresentCurrent,
        "EVSECurrentLimitAchieved": EVSECurrentLimitAchieved,
        "EVSEVoltageLimitAchieved": EVSEVoltageLimitAchieved,
        "EVSEPowerLimitAchieved": EVSEPowerLimitAchieved,
        "EVSEID": {"characters": [ord(c) for c in EVSEID], "charactersLen": len(EVSEID)},
        "SAScheduleTupleID": SAScheduleTupleID
    }
    if EVSEMaximumVoltageLimit is not None:
        j["EVSEMaximumVoltageLimit"] = EVSEMaximumVoltageLimit
    if EVSEMaximumCurrentLimit is not None:
        j["EVSEMaximumCurrentLimit"] = EVSEMaximumCurrentLimit
    if EVSEMaximumPowerLimit is not None:
        j["EVSEMaximumPowerLimit"] = EVSEMaximumPowerLimit
    if MeterInfo is not None:
        j["MeterInfo"] = MeterInfo
    if ReceiptRequired is not None:
        j["ReceiptRequired"] = ReceiptRequired
    return j

def ChargingStatusResType(ResponseCode:responseCodeType, EVSEID:str, SAScheduleTupleID:int, AC_EVSEStatus:dict[str, Any], *, EVSEMaxCurrent:dict[str, Any]|None=None, MeterInfo:dict[str, Any]|None=None, ReceiptRequired:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "EVSEID": {"characters": [ord(c) for c in EVSEID], "charactersLen": len(EVSEID)},
        "SAScheduleTupleID": SAScheduleTupleID,
        "AC_EVSEStatus": AC_EVSEStatus
    }
    if EVSEMaxCurrent is not None:
        j["EVSEMaxCurrent"] = EVSEMaxCurrent
    if MeterInfo is not None:
        j["MeterInfo"] = MeterInfo
    if ReceiptRequired is not None:
        j["ReceiptRequired"] = ReceiptRequired
    return j

def AuthorizationReqType(*, Id:str|None=None, GenChallenge:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if GenChallenge is not None:
        j["GenChallenge"] = {"bytes": list(GenChallenge), "bytesLen": len(GenChallenge)}
    return j

def PreChargeReqType(DC_EVStatus:dict[str, Any], EVTargetVoltage:dict[str, Any], EVTargetCurrent:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "DC_EVStatus": DC_EVStatus,
        "EVTargetVoltage": EVTargetVoltage,
        "EVTargetCurrent": EVTargetCurrent
    }
    return j

def ServiceDetailResType(ResponseCode:responseCodeType, ServiceID:int, *, ServiceParameterList:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "ServiceID": ServiceID
    }
    if ServiceParameterList is not None:
        j["ServiceParameterList"] = ServiceParameterList
    return j

def PaymentServiceSelectionResType(ResponseCode:responseCodeType)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value
    }
    return j

def CertificateUpdateReqType(Id:str, ContractSignatureCertChain:dict[str, Any], eMAID:str, ListOfRootCertificateIDs:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "Id": {"characters": [ord(c) for c in Id], "charactersLen": len(Id)},
        "ContractSignatureCertChain": ContractSignatureCertChain,
        "eMAID": {"characters": [ord(c) for c in eMAID], "charactersLen": len(eMAID)},
        "ListOfRootCertificateIDs": ListOfRootCertificateIDs
    }
    return j

def SessionSetupResType(ResponseCode:responseCodeType, EVSEID:str, *, EVSETimeStamp:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "EVSEID": {"characters": [ord(c) for c in EVSEID], "charactersLen": len(EVSEID)}
    }
    if EVSETimeStamp is not None:
        j["EVSETimeStamp"] = EVSETimeStamp
    return j

def CertificateInstallationReqType(Id:str, OEMProvisioningCert:bytearray, ListOfRootCertificateIDs:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "Id": {"characters": [ord(c) for c in Id], "charactersLen": len(Id)},
        "OEMProvisioningCert": {"bytes": list(OEMProvisioningCert), "bytesLen": len(OEMProvisioningCert)},
        "ListOfRootCertificateIDs": ListOfRootCertificateIDs
    }
    return j

def CertificateInstallationResType(ResponseCode:responseCodeType, SAProvisioningCertificateChain:dict[str, Any], ContractSignatureCertChain:dict[str, Any], ContractSignatureEncryptedPrivateKey:dict[str, Any], DHpublickey:dict[str, Any], eMAID:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "SAProvisioningCertificateChain": SAProvisioningCertificateChain,
        "ContractSignatureCertChain": ContractSignatureCertChain,
        "ContractSignatureEncryptedPrivateKey": ContractSignatureEncryptedPrivateKey,
        "DHpublickey": DHpublickey,
        "eMAID": eMAID
    }
    return j

def WeldingDetectionResType(ResponseCode:responseCodeType, DC_EVSEStatus:dict[str, Any], EVSEPresentVoltage:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "DC_EVSEStatus": DC_EVSEStatus,
        "EVSEPresentVoltage": EVSEPresentVoltage
    }
    return j

def CurrentDemandReqType(DC_EVStatus:dict[str, Any], EVTargetCurrent:dict[str, Any], ChargingComplete:int, EVTargetVoltage:dict[str, Any], *, EVMaximumVoltageLimit:dict[str, Any]|None=None, EVMaximumCurrentLimit:dict[str, Any]|None=None, EVMaximumPowerLimit:dict[str, Any]|None=None, BulkChargingComplete:int|None=None, RemainingTimeToFullSoC:dict[str, Any]|None=None, RemainingTimeToBulkSoC:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "DC_EVStatus": DC_EVStatus,
        "EVTargetCurrent": EVTargetCurrent,
        "ChargingComplete": ChargingComplete,
        "EVTargetVoltage": EVTargetVoltage
    }
    if EVMaximumVoltageLimit is not None:
        j["EVMaximumVoltageLimit"] = EVMaximumVoltageLimit
    if EVMaximumCurrentLimit is not None:
        j["EVMaximumCurrentLimit"] = EVMaximumCurrentLimit
    if EVMaximumPowerLimit is not None:
        j["EVMaximumPowerLimit"] = EVMaximumPowerLimit
    if BulkChargingComplete is not None:
        j["BulkChargingComplete"] = BulkChargingComplete
    if RemainingTimeToFullSoC is not None:
        j["RemainingTimeToFullSoC"] = RemainingTimeToFullSoC
    if RemainingTimeToBulkSoC is not None:
        j["RemainingTimeToBulkSoC"] = RemainingTimeToBulkSoC
    return j

def PreChargeResType(ResponseCode:responseCodeType, DC_EVSEStatus:dict[str, Any], EVSEPresentVoltage:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "DC_EVSEStatus": DC_EVSEStatus,
        "EVSEPresentVoltage": EVSEPresentVoltage
    }
    return j

def CertificateUpdateResType(ResponseCode:responseCodeType, SAProvisioningCertificateChain:dict[str, Any], ContractSignatureCertChain:dict[str, Any], ContractSignatureEncryptedPrivateKey:dict[str, Any], DHpublickey:dict[str, Any], eMAID:dict[str, Any], *, RetryCounter:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "SAProvisioningCertificateChain": SAProvisioningCertificateChain,
        "ContractSignatureCertChain": ContractSignatureCertChain,
        "ContractSignatureEncryptedPrivateKey": ContractSignatureEncryptedPrivateKey,
        "DHpublickey": DHpublickey,
        "eMAID": eMAID
    }
    if RetryCounter is not None:
        j["RetryCounter"] = RetryCounter
    return j

def MeteringReceiptReqType(SessionID:bytearray, MeterInfo:dict[str, Any], *, Id:str|None=None, SAScheduleTupleID:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SessionID": {"bytes": list(SessionID), "bytesLen": len(SessionID)},
        "MeterInfo": MeterInfo
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if SAScheduleTupleID is not None:
        j["SAScheduleTupleID"] = SAScheduleTupleID
    return j

def ChargingStatusReqType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def SessionStopResType(ResponseCode:responseCodeType)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value
    }
    return j

def ChargeParameterDiscoveryReqType(RequestedEnergyTransferMode:EnergyTransferModeType, *, MaxEntriesSAScheduleTuple:int|None=None, AC_EVChargeParameter:dict[str, Any]|None=None, DC_EVChargeParameter:dict[str, Any]|None=None, EVChargeParameter:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "RequestedEnergyTransferMode": RequestedEnergyTransferMode.value
    }
    if MaxEntriesSAScheduleTuple is not None:
        j["MaxEntriesSAScheduleTuple"] = MaxEntriesSAScheduleTuple
    if AC_EVChargeParameter is not None:
        j["AC_EVChargeParameter"] = AC_EVChargeParameter
    if DC_EVChargeParameter is not None:
        j["DC_EVChargeParameter"] = DC_EVChargeParameter
    if EVChargeParameter is not None:
        j["EVChargeParameter"] = EVChargeParameter
    return j

def CableCheckReqType(DC_EVStatus:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "DC_EVStatus": DC_EVStatus
    }
    return j

def WeldingDetectionReqType(DC_EVStatus:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "DC_EVStatus": DC_EVStatus
    }
    return j

def PowerDeliveryResType(ResponseCode:responseCodeType, *, AC_EVSEStatus:dict[str, Any]|None=None, DC_EVSEStatus:dict[str, Any]|None=None, EVSEStatus:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value
    }
    if AC_EVSEStatus is not None:
        j["AC_EVSEStatus"] = AC_EVSEStatus
    if DC_EVSEStatus is not None:
        j["DC_EVSEStatus"] = DC_EVSEStatus
    if EVSEStatus is not None:
        j["EVSEStatus"] = EVSEStatus
    return j

def ChargeParameterDiscoveryResType(ResponseCode:responseCodeType, EVSEProcessing:EVSEProcessingType, *, SAScheduleList:dict[str, Any]|None=None, SASchedules:dict[str, Any]|None=None, AC_EVSEChargeParameter:dict[str, Any]|None=None, DC_EVSEChargeParameter:dict[str, Any]|None=None, EVSEChargeParameter:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "EVSEProcessing": EVSEProcessing.value
    }
    if SAScheduleList is not None:
        j["SAScheduleList"] = SAScheduleList
    if SASchedules is not None:
        j["SASchedules"] = SASchedules
    if AC_EVSEChargeParameter is not None:
        j["AC_EVSEChargeParameter"] = AC_EVSEChargeParameter
    if DC_EVSEChargeParameter is not None:
        j["DC_EVSEChargeParameter"] = DC_EVSEChargeParameter
    if EVSEChargeParameter is not None:
        j["EVSEChargeParameter"] = EVSEChargeParameter
    return j

def PaymentServiceSelectionReqType(SelectedPaymentOption:paymentOptionType, SelectedServiceList:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "SelectedPaymentOption": SelectedPaymentOption.value,
        "SelectedServiceList": SelectedServiceList
    }
    return j

def MeteringReceiptResType(ResponseCode:responseCodeType, *, AC_EVSEStatus:dict[str, Any]|None=None, DC_EVSEStatus:dict[str, Any]|None=None, EVSEStatus:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value
    }
    if AC_EVSEStatus is not None:
        j["AC_EVSEStatus"] = AC_EVSEStatus
    if DC_EVSEStatus is not None:
        j["DC_EVSEStatus"] = DC_EVSEStatus
    if EVSEStatus is not None:
        j["EVSEStatus"] = EVSEStatus
    return j

def CableCheckResType(ResponseCode:responseCodeType, DC_EVSEStatus:dict[str, Any], EVSEProcessing:EVSEProcessingType)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "DC_EVSEStatus": DC_EVSEStatus,
        "EVSEProcessing": EVSEProcessing.value
    }
    return j

def ServiceDiscoveryResType(ResponseCode:responseCodeType, PaymentOptionList:dict[str, Any], ChargeService:dict[str, Any], *, ServiceList:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "PaymentOptionList": PaymentOptionList,
        "ChargeService": ChargeService
    }
    if ServiceList is not None:
        j["ServiceList"] = ServiceList
    return j

def ServiceDetailReqType(ServiceID:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "ServiceID": ServiceID
    }
    return j

def SessionSetupReqType(EVCCID:bytearray)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVCCID": {"bytes": list(EVCCID), "bytesLen": len(EVCCID)}
    }
    return j

def SessionStopReqType(ChargingSession:chargingSessionType)->dict[str, Any]:
    j:dict[str, Any] = {
        "ChargingSession": ChargingSession.value
    }
    return j

def ServiceDiscoveryReqType(*, ServiceScope:str|None=None, ServiceCategory:serviceCategoryType|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if ServiceScope is not None:
        j["ServiceScope"] = {"characters": [ord(c) for c in ServiceScope], "charactersLen": len(ServiceScope)}
    if ServiceCategory is not None:
        j["ServiceCategory"] = ServiceCategory.value
    return j

def AuthorizationResType(ResponseCode:responseCodeType, EVSEProcessing:EVSEProcessingType)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "EVSEProcessing": EVSEProcessing.value
    }
    return j

def PaymentDetailsReqType(eMAID:str, ContractSignatureCertChain:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "eMAID": {"characters": [ord(c) for c in eMAID], "charactersLen": len(eMAID)},
        "ContractSignatureCertChain": ContractSignatureCertChain
    }
    return j

def PaymentDetailsResType(ResponseCode:responseCodeType, GenChallenge:bytearray, EVSETimeStamp:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value,
        "GenChallenge": {"bytes": list(GenChallenge), "bytesLen": len(GenChallenge)},
        "EVSETimeStamp": EVSETimeStamp
    }
    return j

def BodyType(*, AuthorizationReq:dict[str, Any]|None=None, AuthorizationRes:dict[str, Any]|None=None, BodyElement:dict[str, Any]|None=None, CableCheckReq:dict[str, Any]|None=None, CableCheckRes:dict[str, Any]|None=None, CertificateInstallationReq:dict[str, Any]|None=None, CertificateInstallationRes:dict[str, Any]|None=None, CertificateUpdateReq:dict[str, Any]|None=None, CertificateUpdateRes:dict[str, Any]|None=None, ChargeParameterDiscoveryReq:dict[str, Any]|None=None, ChargeParameterDiscoveryRes:dict[str, Any]|None=None, ChargingStatusReq:dict[str, Any]|None=None, ChargingStatusRes:dict[str, Any]|None=None, CurrentDemandReq:dict[str, Any]|None=None, CurrentDemandRes:dict[str, Any]|None=None, MeteringReceiptReq:dict[str, Any]|None=None, MeteringReceiptRes:dict[str, Any]|None=None, PaymentDetailsReq:dict[str, Any]|None=None, PaymentDetailsRes:dict[str, Any]|None=None, PaymentServiceSelectionReq:dict[str, Any]|None=None, PaymentServiceSelectionRes:dict[str, Any]|None=None, PowerDeliveryReq:dict[str, Any]|None=None, PowerDeliveryRes:dict[str, Any]|None=None, PreChargeReq:dict[str, Any]|None=None, PreChargeRes:dict[str, Any]|None=None, ServiceDetailReq:dict[str, Any]|None=None, ServiceDetailRes:dict[str, Any]|None=None, ServiceDiscoveryReq:dict[str, Any]|None=None, ServiceDiscoveryRes:dict[str, Any]|None=None, SessionSetupReq:dict[str, Any]|None=None, SessionSetupRes:dict[str, Any]|None=None, SessionStopReq:dict[str, Any]|None=None, SessionStopRes:dict[str, Any]|None=None, WeldingDetectionReq:dict[str, Any]|None=None, WeldingDetectionRes:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if AuthorizationReq is not None:
        j["AuthorizationReq"] = AuthorizationReq
    if AuthorizationRes is not None:
        j["AuthorizationRes"] = AuthorizationRes
    if BodyElement is not None:
        j["BodyElement"] = BodyElement
    if CableCheckReq is not None:
        j["CableCheckReq"] = CableCheckReq
    if CableCheckRes is not None:
        j["CableCheckRes"] = CableCheckRes
    if CertificateInstallationReq is not None:
        j["CertificateInstallationReq"] = CertificateInstallationReq
    if CertificateInstallationRes is not None:
        j["CertificateInstallationRes"] = CertificateInstallationRes
    if CertificateUpdateReq is not None:
        j["CertificateUpdateReq"] = CertificateUpdateReq
    if CertificateUpdateRes is not None:
        j["CertificateUpdateRes"] = CertificateUpdateRes
    if ChargeParameterDiscoveryReq is not None:
        j["ChargeParameterDiscoveryReq"] = ChargeParameterDiscoveryReq
    if ChargeParameterDiscoveryRes is not None:
        j["ChargeParameterDiscoveryRes"] = ChargeParameterDiscoveryRes
    if ChargingStatusReq is not None:
        j["ChargingStatusReq"] = ChargingStatusReq
    if ChargingStatusRes is not None:
        j["ChargingStatusRes"] = ChargingStatusRes
    if CurrentDemandReq is not None:
        j["CurrentDemandReq"] = CurrentDemandReq
    if CurrentDemandRes is not None:
        j["CurrentDemandRes"] = CurrentDemandRes
    if MeteringReceiptReq is not None:
        j["MeteringReceiptReq"] = MeteringReceiptReq
    if MeteringReceiptRes is not None:
        j["MeteringReceiptRes"] = MeteringReceiptRes
    if PaymentDetailsReq is not None:
        j["PaymentDetailsReq"] = PaymentDetailsReq
    if PaymentDetailsRes is not None:
        j["PaymentDetailsRes"] = PaymentDetailsRes
    if PaymentServiceSelectionReq is not None:
        j["PaymentServiceSelectionReq"] = PaymentServiceSelectionReq
    if PaymentServiceSelectionRes is not None:
        j["PaymentServiceSelectionRes"] = PaymentServiceSelectionRes
    if PowerDeliveryReq is not None:
        j["PowerDeliveryReq"] = PowerDeliveryReq
    if PowerDeliveryRes is not None:
        j["PowerDeliveryRes"] = PowerDeliveryRes
    if PreChargeReq is not None:
        j["PreChargeReq"] = PreChargeReq
    if PreChargeRes is not None:
        j["PreChargeRes"] = PreChargeRes
    if ServiceDetailReq is not None:
        j["ServiceDetailReq"] = ServiceDetailReq
    if ServiceDetailRes is not None:
        j["ServiceDetailRes"] = ServiceDetailRes
    if ServiceDiscoveryReq is not None:
        j["ServiceDiscoveryReq"] = ServiceDiscoveryReq
    if ServiceDiscoveryRes is not None:
        j["ServiceDiscoveryRes"] = ServiceDiscoveryRes
    if SessionSetupReq is not None:
        j["SessionSetupReq"] = SessionSetupReq
    if SessionSetupRes is not None:
        j["SessionSetupRes"] = SessionSetupRes
    if SessionStopReq is not None:
        j["SessionStopReq"] = SessionStopReq
    if SessionStopRes is not None:
        j["SessionStopRes"] = SessionStopRes
    if WeldingDetectionReq is not None:
        j["WeldingDetectionReq"] = WeldingDetectionReq
    if WeldingDetectionRes is not None:
        j["WeldingDetectionRes"] = WeldingDetectionRes
    return j

def V2G_Message(Header:dict[str, Any], Body:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "Body": Body
    }
    return j

def exiFragment(*, AuthorizationReq:dict[str, Any]|None=None, CertificateInstallationReq:dict[str, Any]|None=None, CertificateUpdateReq:dict[str, Any]|None=None, ContractSignatureCertChain:dict[str, Any]|None=None, ContractSignatureEncryptedPrivateKey:dict[str, Any]|None=None, DHpublickey:dict[str, Any]|None=None, MeteringReceiptReq:dict[str, Any]|None=None, SalesTariff:dict[str, Any]|None=None, SignedInfo:dict[str, Any]|None=None, eMAID:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if AuthorizationReq is not None:
        j["AuthorizationReq"] = AuthorizationReq
    if CertificateInstallationReq is not None:
        j["CertificateInstallationReq"] = CertificateInstallationReq
    if CertificateUpdateReq is not None:
        j["CertificateUpdateReq"] = CertificateUpdateReq
    if ContractSignatureCertChain is not None:
        j["ContractSignatureCertChain"] = ContractSignatureCertChain
    if ContractSignatureEncryptedPrivateKey is not None:
        j["ContractSignatureEncryptedPrivateKey"] = ContractSignatureEncryptedPrivateKey
    if DHpublickey is not None:
        j["DHpublickey"] = DHpublickey
    if MeteringReceiptReq is not None:
        j["MeteringReceiptReq"] = MeteringReceiptReq
    if SalesTariff is not None:
        j["SalesTariff"] = SalesTariff
    if SignedInfo is not None:
        j["SignedInfo"] = SignedInfo
    if eMAID is not None:
        j["eMAID"] = eMAID
    return j

def xmldsigFragment(*, CanonicalizationMethod:dict[str, Any]|None=None, DSAKeyValue:dict[str, Any]|None=None, DigestMethod:dict[str, Any]|None=None, KeyInfo:dict[str, Any]|None=None, KeyValue:dict[str, Any]|None=None, Object:dict[str, Any]|None=None, PGPData:dict[str, Any]|None=None, RSAKeyValue:dict[str, Any]|None=None, Reference:dict[str, Any]|None=None, RetrievalMethod:dict[str, Any]|None=None, SPKIData:dict[str, Any]|None=None, Signature:dict[str, Any]|None=None, SignatureMethod:dict[str, Any]|None=None, SignatureValue:dict[str, Any]|None=None, SignedInfo:dict[str, Any]|None=None, Transform:dict[str, Any]|None=None, Transforms:dict[str, Any]|None=None, X509Data:dict[str, Any]|None=None, X509IssuerSerial:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if CanonicalizationMethod is not None:
        j["CanonicalizationMethod"] = CanonicalizationMethod
    if DSAKeyValue is not None:
        j["DSAKeyValue"] = DSAKeyValue
    if DigestMethod is not None:
        j["DigestMethod"] = DigestMethod
    if KeyInfo is not None:
        j["KeyInfo"] = KeyInfo
    if KeyValue is not None:
        j["KeyValue"] = KeyValue
    if Object is not None:
        j["Object"] = Object
    if PGPData is not None:
        j["PGPData"] = PGPData
    if RSAKeyValue is not None:
        j["RSAKeyValue"] = RSAKeyValue
    if Reference is not None:
        j["Reference"] = Reference
    if RetrievalMethod is not None:
        j["RetrievalMethod"] = RetrievalMethod
    if SPKIData is not None:
        j["SPKIData"] = SPKIData
    if Signature is not None:
        j["Signature"] = Signature
    if SignatureMethod is not None:
        j["SignatureMethod"] = SignatureMethod
    if SignatureValue is not None:
        j["SignatureValue"] = SignatureValue
    if SignedInfo is not None:
        j["SignedInfo"] = SignedInfo
    if Transform is not None:
        j["Transform"] = Transform
    if Transforms is not None:
        j["Transforms"] = Transforms
    if X509Data is not None:
        j["X509Data"] = X509Data
    if X509IssuerSerial is not None:
        j["X509IssuerSerial"] = X509IssuerSerial
    return j
