"""
Enum tables for the ISO 15118-20 ACDP Namespace (consumed by tools/codegen/fixture_emitter).

Auto-generated by tools/codegen/v2gjson_emitter.py. DO NOT EDIT.
"""

from enum import Enum


# skipped iso20_acdp_generatedFunctionNumbersType: enum iso20_acdp_generatedFunctionNumbersType member 'iso20_acdp_ACDP_ConnectReq' does not start with expected prefix 'iso20_acdp_generatedFunctionNumbersType_'

class cpStatusType(Enum):
    StateA = 0
    StateB = 1
    StateC = 2
    StateD = 3
    StateE = 4


class errorCodeType(Enum):
    OK_NoEVError = 0
    FAILED = 1
    FAILED_EmergencyEvent = 2
    FAILED_Breaker = 3
    FAILED_RESSTemperatureInhibit = 4
    FAILED_RESS = 5
    FAILED_ChargingCurrentDifferential = 6
    FAILED_ChargingVoltageOutOfRange = 7
    FAILED_Reserved1 = 8
    FAILED_Reserved2 = 9


class responseCodeType(Enum):
    OK = 0
    OK_CertificateExpiresSoon = 1
    OK_NewSessionEstablished = 2
    OK_OldSessionJoined = 3
    OK_PowerToleranceConfirmed = 4
    WARNING_AuthorizationSelectionInvalid = 5
    WARNING_CertificateExpired = 6
    WARNING_CertificateNotYetValid = 7
    WARNING_CertificateRevoked = 8
    WARNING_CertificateValidationError = 9
    WARNING_ChallengeInvalid = 10
    WARNING_EIMAuthorizationFailure = 11
    WARNING_eMSPUnknown = 12
    WARNING_EVPowerProfileViolation = 13
    WARNING_GeneralPnCAuthorizationError = 14
    WARNING_NoCertificateAvailable = 15
    WARNING_NoContractMatchingPCIDFound = 16
    WARNING_PowerToleranceNotConfirmed = 17
    WARNING_ScheduleRenegotiationFailed = 18
    WARNING_StandbyNotAllowed = 19
    WARNING_WPT = 20
    FAILED = 21
    FAILED_AssociationError = 22
    FAILED_ContactorError = 23
    FAILED_EVPowerProfileInvalid = 24
    FAILED_EVPowerProfileViolation = 25
    FAILED_MeteringSignatureNotValid = 26
    FAILED_NoEnergyTransferServiceSelected = 27
    FAILED_NoServiceRenegotiationSupported = 28
    FAILED_PauseNotAllowed = 29
    FAILED_PowerDeliveryNotApplied = 30
    FAILED_PowerToleranceNotConfirmed = 31
    FAILED_ScheduleRenegotiation = 32
    FAILED_ScheduleSelectionInvalid = 33
    FAILED_SequenceError = 34
    FAILED_ServiceIDInvalid = 35
    FAILED_ServiceSelectionInvalid = 36
    FAILED_SignatureError = 37
    FAILED_UnknownSession = 38
    FAILED_WrongChargeParameter = 39


class electricalChargingDeviceStatusType(Enum):
    State_A = 0
    State_B = 1
    State_C = 2
    State_D = 3


class processingType(Enum):
    Finished = 0
    Ongoing = 1
    Ongoing_WaitingForCustomerInteraction = 2


class mechanicalChargingDeviceStatusType(Enum):
    Home = 0
    Moving = 1
    EndPosition = 2


class isolationStatusType(Enum):
    Invalid = 0
    Safe = 1
    Warning = 2
    Fault = 3
