"""
Constructors and enum tables for the ISO 15118-20 ACDP Namespace.

Auto-generated by tools/codegen/v2gjson_emitter.py. DO NOT EDIT.
"""

from enum import Enum
from typing import Any


# skipped iso20_acdp_generatedFunctionNumbersType: enum iso20_acdp_generatedFunctionNumbersType member 'iso20_acdp_ACDP_ConnectReq' does not start with expected prefix 'iso20_acdp_generatedFunctionNumbersType_'

class cpStatusType(Enum):
    StateA = 0
    StateB = 1
    StateC = 2
    StateD = 3
    StateE = 4


class errorCodeType(Enum):
    OK_NoEVError = 0
    FAILED = 1
    FAILED_EmergencyEvent = 2
    FAILED_Breaker = 3
    FAILED_RESSTemperatureInhibit = 4
    FAILED_RESS = 5
    FAILED_ChargingCurrentDifferential = 6
    FAILED_ChargingVoltageOutOfRange = 7
    FAILED_Reserved1 = 8
    FAILED_Reserved2 = 9


class responseCodeType(Enum):
    OK = 0
    OK_CertificateExpiresSoon = 1
    OK_NewSessionEstablished = 2
    OK_OldSessionJoined = 3
    OK_PowerToleranceConfirmed = 4
    WARNING_AuthorizationSelectionInvalid = 5
    WARNING_CertificateExpired = 6
    WARNING_CertificateNotYetValid = 7
    WARNING_CertificateRevoked = 8
    WARNING_CertificateValidationError = 9
    WARNING_ChallengeInvalid = 10
    WARNING_EIMAuthorizationFailure = 11
    WARNING_eMSPUnknown = 12
    WARNING_EVPowerProfileViolation = 13
    WARNING_GeneralPnCAuthorizationError = 14
    WARNING_NoCertificateAvailable = 15
    WARNING_NoContractMatchingPCIDFound = 16
    WARNING_PowerToleranceNotConfirmed = 17
    WARNING_ScheduleRenegotiationFailed = 18
    WARNING_StandbyNotAllowed = 19
    WARNING_WPT = 20
    FAILED = 21
    FAILED_AssociationError = 22
    FAILED_ContactorError = 23
    FAILED_EVPowerProfileInvalid = 24
    FAILED_EVPowerProfileViolation = 25
    FAILED_MeteringSignatureNotValid = 26
    FAILED_NoEnergyTransferServiceSelected = 27
    FAILED_NoServiceRenegotiationSupported = 28
    FAILED_PauseNotAllowed = 29
    FAILED_PowerDeliveryNotApplied = 30
    FAILED_PowerToleranceNotConfirmed = 31
    FAILED_ScheduleRenegotiation = 32
    FAILED_ScheduleSelectionInvalid = 33
    FAILED_SequenceError = 34
    FAILED_ServiceIDInvalid = 35
    FAILED_ServiceSelectionInvalid = 36
    FAILED_SignatureError = 37
    FAILED_UnknownSession = 38
    FAILED_WrongChargeParameter = 39


class electricalChargingDeviceStatusType(Enum):
    State_A = 0
    State_B = 1
    State_C = 2
    State_D = 3


class processingType(Enum):
    Finished = 0
    Ongoing = 1
    Ongoing_WaitingForCustomerInteraction = 2


class mechanicalChargingDeviceStatusType(Enum):
    Home = 0
    Moving = 1
    EndPosition = 2


class isolationStatusType(Enum):
    Invalid = 0
    Safe = 1
    Warning = 2
    Fault = 3


def TransformType(Algorithm:str, *, ANY:bytearray|None=None, XPath:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    if XPath is not None:
        j["XPath"] = {"characters": [ord(c) for c in XPath], "charactersLen": len(XPath)}
    return j

def TransformsType(Transform:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Transform": Transform
    }
    return j

def DSAKeyValueType(Y:bytearray, *, P:bytearray|None=None, Q:bytearray|None=None, G:bytearray|None=None, J:bytearray|None=None, Seed:bytearray|None=None, PgenCounter:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Y": {"bytes": list(Y), "bytesLen": len(Y)}
    }
    if P is not None:
        j["P"] = {"bytes": list(P), "bytesLen": len(P)}
    if Q is not None:
        j["Q"] = {"bytes": list(Q), "bytesLen": len(Q)}
    if G is not None:
        j["G"] = {"bytes": list(G), "bytesLen": len(G)}
    if J is not None:
        j["J"] = {"bytes": list(J), "bytesLen": len(J)}
    if Seed is not None:
        j["Seed"] = {"bytes": list(Seed), "bytesLen": len(Seed)}
    if PgenCounter is not None:
        j["PgenCounter"] = {"bytes": list(PgenCounter), "bytesLen": len(PgenCounter)}
    return j

def X509IssuerSerialType(X509IssuerName:str, X509SerialNumber:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "X509IssuerName": {"characters": [ord(c) for c in X509IssuerName], "charactersLen": len(X509IssuerName)},
        "X509SerialNumber": X509SerialNumber
    }
    return j

def DigestMethodType(Algorithm:str, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def RSAKeyValueType(Modulus:bytearray, Exponent:bytearray)->dict[str, Any]:
    j:dict[str, Any] = {
        "Modulus": {"bytes": list(Modulus), "bytesLen": len(Modulus)},
        "Exponent": {"bytes": list(Exponent), "bytesLen": len(Exponent)}
    }
    return j

def CanonicalizationMethodType(Algorithm:str, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def SignatureMethodType(Algorithm:str, *, HMACOutputLength:int|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if HMACOutputLength is not None:
        j["HMACOutputLength"] = HMACOutputLength
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def KeyValueType(*, DSAKeyValue:int|None=None, RSAKeyValue:int|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if DSAKeyValue is not None:
        j["DSAKeyValue"] = DSAKeyValue
    if RSAKeyValue is not None:
        j["RSAKeyValue"] = RSAKeyValue
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def ReferenceType(DigestMethod:int, DigestValue:bytearray, *, Id:str|None=None, Type:str|None=None, URI:str|None=None, Transforms:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "DigestMethod": DigestMethod,
        "DigestValue": {"bytes": list(DigestValue), "bytesLen": len(DigestValue)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if Type is not None:
        j["Type"] = {"characters": [ord(c) for c in Type], "charactersLen": len(Type)}
    if URI is not None:
        j["URI"] = {"characters": [ord(c) for c in URI], "charactersLen": len(URI)}
    if Transforms is not None:
        j["Transforms"] = Transforms
    return j

def RetrievalMethodType(*, Type:str|None=None, URI:str|None=None, Transforms:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Type is not None:
        j["Type"] = {"characters": [ord(c) for c in Type], "charactersLen": len(Type)}
    if URI is not None:
        j["URI"] = {"characters": [ord(c) for c in URI], "charactersLen": len(URI)}
    if Transforms is not None:
        j["Transforms"] = Transforms
    return j

def X509DataType(*, X509IssuerSerial:int|None=None, X509SKI:bytearray|None=None, X509SubjectName:str|None=None, X509Certificate:bytearray|None=None, X509CRL:bytearray|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if X509IssuerSerial is not None:
        j["X509IssuerSerial"] = X509IssuerSerial
    if X509SKI is not None:
        j["X509SKI"] = {"bytes": list(X509SKI), "bytesLen": len(X509SKI)}
    if X509SubjectName is not None:
        j["X509SubjectName"] = {"characters": [ord(c) for c in X509SubjectName], "charactersLen": len(X509SubjectName)}
    if X509Certificate is not None:
        j["X509Certificate"] = {"bytes": list(X509Certificate), "bytesLen": len(X509Certificate)}
    if X509CRL is not None:
        j["X509CRL"] = {"bytes": list(X509CRL), "bytesLen": len(X509CRL)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def PGPDataType(*, choice_1:int|None=None, choice_2:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if choice_1 is not None:
        j["choice_1"] = choice_1
    if choice_2 is not None:
        j["choice_2"] = choice_2
    return j

def SPKIDataType(SPKISexp:bytearray, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SPKISexp": {"bytes": list(SPKISexp), "bytesLen": len(SPKISexp)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def SignedInfoType(CanonicalizationMethod:int, SignatureMethod:int, Reference:list[dict[str, Any]], *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "CanonicalizationMethod": CanonicalizationMethod,
        "SignatureMethod": SignatureMethod,
        "Reference": {"arrayLen": len(Reference), "array": Reference}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def SignatureValueType(CONTENT:bytearray, *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "CONTENT": {"bytes": list(CONTENT), "bytesLen": len(CONTENT)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def KeyInfoType(*, Id:str|None=None, KeyName:str|None=None, KeyValue:int|None=None, RetrievalMethod:int|None=None, X509Data:int|None=None, PGPData:int|None=None, SPKIData:int|None=None, MgmtData:str|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if KeyName is not None:
        j["KeyName"] = {"characters": [ord(c) for c in KeyName], "charactersLen": len(KeyName)}
    if KeyValue is not None:
        j["KeyValue"] = KeyValue
    if RetrievalMethod is not None:
        j["RetrievalMethod"] = RetrievalMethod
    if X509Data is not None:
        j["X509Data"] = X509Data
    if PGPData is not None:
        j["PGPData"] = PGPData
    if SPKIData is not None:
        j["SPKIData"] = SPKIData
    if MgmtData is not None:
        j["MgmtData"] = {"characters": [ord(c) for c in MgmtData], "charactersLen": len(MgmtData)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def ObjectType(*, Encoding:str|None=None, Id:str|None=None, MimeType:str|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Encoding is not None:
        j["Encoding"] = {"characters": [ord(c) for c in Encoding], "charactersLen": len(Encoding)}
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if MimeType is not None:
        j["MimeType"] = {"characters": [ord(c) for c in MimeType], "charactersLen": len(MimeType)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def SignatureType(SignedInfo:int, SignatureValue:int, *, Id:str|None=None, KeyInfo:int|None=None, Object:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SignedInfo": SignedInfo,
        "SignatureValue": SignatureValue
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if KeyInfo is not None:
        j["KeyInfo"] = KeyInfo
    if Object is not None:
        j["Object"] = Object
    return j

def RationalNumberType(Exponent:int, Value:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Exponent": Exponent,
        "Value": Value
    }
    return j

def MessageHeaderType(SessionID:bytearray, TimeStamp:int, *, Signature:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SessionID": {"bytes": list(SessionID), "bytesLen": len(SessionID)},
        "TimeStamp": TimeStamp
    }
    if Signature is not None:
        j["Signature"] = Signature
    return j

def SignaturePropertyType(Target:str, *, Id:str|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Target": {"characters": [ord(c) for c in Target], "charactersLen": len(Target)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def EVTechnicalStatusType(EVReadyToCharge:int, EVImmobilizationRequest:int, *, EVImmobilized:int|None=None, EVWLANStrength:int|None=None, EVCPStatus:cpStatusType|None=None, EVSOC:int|None=None, EVErrorCode:errorCodeType|None=None, EVTimeout:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVReadyToCharge": EVReadyToCharge,
        "EVImmobilizationRequest": EVImmobilizationRequest
    }
    if EVImmobilized is not None:
        j["EVImmobilized"] = EVImmobilized
    if EVWLANStrength is not None:
        j["EVWLANStrength"] = EVWLANStrength
    if EVCPStatus is not None:
        j["EVCPStatus"] = EVCPStatus.value
    if EVSOC is not None:
        j["EVSOC"] = EVSOC
    if EVErrorCode is not None:
        j["EVErrorCode"] = EVErrorCode.value
    if EVTimeout is not None:
        j["EVTimeout"] = EVTimeout
    return j

def ACDP_VehiclePositioningReqType(Header:int, EVMobilityStatus:int, EVPositioningSupport:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "EVMobilityStatus": EVMobilityStatus,
        "EVPositioningSupport": EVPositioningSupport
    }
    return j

def ACDP_VehiclePositioningResType(Header:int, ResponseCode:responseCodeType, EVSEProcessing:processingType, EVSEPositioningSupport:int, EVRelativeXDeviation:int, EVRelativeYDeviation:int, ContactWindowXc:int, ContactWindowYc:int, EVInChargePosition:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "EVSEProcessing": EVSEProcessing.value,
        "EVSEPositioningSupport": EVSEPositioningSupport,
        "EVRelativeXDeviation": EVRelativeXDeviation,
        "EVRelativeYDeviation": EVRelativeYDeviation,
        "ContactWindowXc": ContactWindowXc,
        "ContactWindowYc": ContactWindowYc,
        "EVInChargePosition": EVInChargePosition
    }
    return j

def ACDP_ConnectReqType(Header:int, EVElectricalChargingDeviceStatus:electricalChargingDeviceStatusType)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "EVElectricalChargingDeviceStatus": EVElectricalChargingDeviceStatus.value
    }
    return j

def ACDP_ConnectResType(Header:int, ResponseCode:responseCodeType, EVSEProcessing:processingType, EVSEElectricalChargingDeviceStatus:electricalChargingDeviceStatusType, EVSEMechanicalChargingDeviceStatus:mechanicalChargingDeviceStatusType)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "EVSEProcessing": EVSEProcessing.value,
        "EVSEElectricalChargingDeviceStatus": EVSEElectricalChargingDeviceStatus.value,
        "EVSEMechanicalChargingDeviceStatus": EVSEMechanicalChargingDeviceStatus.value
    }
    return j

def ACDP_SystemStatusReqType(Header:int, EVTechnicalStatus:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "EVTechnicalStatus": EVTechnicalStatus
    }
    return j

def ACDP_SystemStatusResType(Header:int, ResponseCode:responseCodeType, EVSEMechanicalChargingDeviceStatus:mechanicalChargingDeviceStatusType, EVSEReadyToCharge:int, EVSEIsolationStatus:isolationStatusType, EVSEDisabled:int, EVSEUtilityInterruptEvent:int, EVSEEmergencyShutdown:int, EVSEMalfunction:int, EVInChargePosition:int, EVAssociationStatus:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "EVSEMechanicalChargingDeviceStatus": EVSEMechanicalChargingDeviceStatus.value,
        "EVSEReadyToCharge": EVSEReadyToCharge,
        "EVSEIsolationStatus": EVSEIsolationStatus.value,
        "EVSEDisabled": EVSEDisabled,
        "EVSEUtilityInterruptEvent": EVSEUtilityInterruptEvent,
        "EVSEEmergencyShutdown": EVSEEmergencyShutdown,
        "EVSEMalfunction": EVSEMalfunction,
        "EVInChargePosition": EVInChargePosition,
        "EVAssociationStatus": EVAssociationStatus
    }
    return j

def CLReqControlModeType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def CLResControlModeType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def ManifestType(Reference:list[dict[str, Any]], *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Reference": {"arrayLen": len(Reference), "array": Reference}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def SignaturePropertiesType(SignatureProperty:int, *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SignatureProperty": SignatureProperty
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j
