"""
Enum tables for the ISO 15118-20 WPT Namespace (consumed by tools/codegen/fixture_emitter).

Auto-generated by tools/codegen/v2gjson_emitter.py. DO NOT EDIT.
"""

from enum import Enum


# skipped iso20_wpt_generatedFunctionNumbersType: enum iso20_wpt_generatedFunctionNumbersType member 'iso20_wpt_CLReqControlMode' does not start with expected prefix 'iso20_wpt_generatedFunctionNumbersType_'

class WPT_FinePositioningMethodType(Enum):
    Manual = 0
    LF_TxEV = 1
    LF_TxPrimaryDevice = 2
    LPE = 3
    Proprietary = 4


class WPT_PairingMethodType(Enum):
    External_confirmation = 0
    LPE = 1
    LF_TxEV = 2
    LF_TxPrimaryDevice = 3
    Optical = 4
    Proprietary = 5


class WPT_AlignmentCheckMethodType(Enum):
    PowerCheck = 0
    LPE = 1
    Proprietary = 2


class evseNotificationType(Enum):
    Pause = 0
    ExitStandby = 1
    Terminate = 2
    ScheduleRenegotiation = 3
    ServiceRenegotiation = 4
    MeteringConfirmation = 5


class processingType(Enum):
    Finished = 0
    Ongoing = 1
    Ongoing_WaitingForCustomerInteraction = 2


class responseCodeType(Enum):
    OK = 0
    OK_CertificateExpiresSoon = 1
    OK_NewSessionEstablished = 2
    OK_OldSessionJoined = 3
    OK_PowerToleranceConfirmed = 4
    WARNING_AuthorizationSelectionInvalid = 5
    WARNING_CertificateExpired = 6
    WARNING_CertificateNotYetValid = 7
    WARNING_CertificateRevoked = 8
    WARNING_CertificateValidationError = 9
    WARNING_ChallengeInvalid = 10
    WARNING_EIMAuthorizationFailure = 11
    WARNING_eMSPUnknown = 12
    WARNING_EVPowerProfileViolation = 13
    WARNING_GeneralPnCAuthorizationError = 14
    WARNING_NoCertificateAvailable = 15
    WARNING_NoContractMatchingPCIDFound = 16
    WARNING_PowerToleranceNotConfirmed = 17
    WARNING_ScheduleRenegotiationFailed = 18
    WARNING_StandbyNotAllowed = 19
    WARNING_WPT = 20
    FAILED = 21
    FAILED_AssociationError = 22
    FAILED_ContactorError = 23
    FAILED_EVPowerProfileInvalid = 24
    FAILED_EVPowerProfileViolation = 25
    FAILED_MeteringSignatureNotValid = 26
    FAILED_NoEnergyTransferServiceSelected = 27
    FAILED_NoServiceRenegotiationSupported = 28
    FAILED_PauseNotAllowed = 29
    FAILED_PowerDeliveryNotApplied = 30
    FAILED_PowerToleranceNotConfirmed = 31
    FAILED_ScheduleRenegotiation = 32
    FAILED_ScheduleSelectionInvalid = 33
    FAILED_SequenceError = 34
    FAILED_ServiceIDInvalid = 35
    FAILED_ServiceSelectionInvalid = 36
    FAILED_SignatureError = 37
    FAILED_UnknownSession = 38
    FAILED_WrongChargeParameter = 39


class WPT_EVResultType(Enum):
    EVResultUnknown = 0
    EVResultSuccess = 1
    EVResultFailed = 2


class WPT_PowerClassType(Enum):
    MF_WPT1 = 0
    MF_WPT2 = 1
    MF_WPT3 = 2
    MF_WPT4 = 3


class WPT_EVPCChargeDiagnosticsType(Enum):
    EVPCNoIssue = 0
    EVPCTempOverheatDetected = 1
    EVPCPowerTransferAnomalyDetected = 2
    EVPCAnomalyDetected = 3


class WPT_SPCChargeDiagnosticsType(Enum):
    SPCNoIssue = 0
    SPCFODDetected = 1
    SPCLOPDetected = 2
    SPCTempOverheatDetected = 3
    SPCPowerTransferAnomalyDetected = 4
    SPCAnomalyDetected = 5
