"""
Constructors and enum tables for the SAP (Supported App Protocol) Namespace.

Auto-generated by tools/codegen/v2gjson_emitter.py. DO NOT EDIT.
"""

from enum import Enum
from typing import Any


# skipped appHand_generatedFunctionNumbersType: enum appHand_generatedFunctionNumbersType member 'appHand_supportedAppProtocolReq' does not start with expected prefix 'appHand_generatedFunctionNumbersType_'

class responseCodeType(Enum):
    OK_SuccessfulNegotiation = 0
    OK_SuccessfulNegotiationWithMinorDeviation = 1
    Failed_NoNegotiation = 2


def AppProtocolType(ProtocolNamespace:str, VersionNumberMajor:int, VersionNumberMinor:int, SchemaID:int, Priority:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "ProtocolNamespace": {"characters": [ord(c) for c in ProtocolNamespace], "charactersLen": len(ProtocolNamespace)},
        "VersionNumberMajor": VersionNumberMajor,
        "VersionNumberMinor": VersionNumberMinor,
        "SchemaID": SchemaID,
        "Priority": Priority
    }
    return j

def supportedAppProtocolReq(AppProtocol:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "AppProtocol": {"arrayLen": len(AppProtocol), "array": AppProtocol}
    }
    return j

def supportedAppProtocolRes(ResponseCode:responseCodeType, *, SchemaID:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "ResponseCode": ResponseCode.value
    }
    if SchemaID is not None:
        j["SchemaID"] = SchemaID
    return j
