"""
Constructors for the libcbv2g exi_basetypes shared helper types.

Auto-generated by tools/codegen/v2gjson_emitter.py. DO NOT EDIT.
"""

from enum import Enum
from typing import Any


def exi_signed_t(data:dict[str, Any], is_negative:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "data": data,
        "is_negative": is_negative
    }
    return j

def exi_unsigned_t(octets:bytearray, octets_count:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "octets": list(octets),
        "octets_count": octets_count
    }
    return j
