"""
Constructors and enum tables for the ISO 15118-20 AC Namespace.

Auto-generated by tools/codegen/v2gjson_emitter.py. DO NOT EDIT.
"""

from enum import Enum
from typing import Any


# skipped iso20_ac_generatedFunctionNumbersType: enum iso20_ac_generatedFunctionNumbersType member 'iso20_ac_AC_CPDReqEnergyTransferMode' does not start with expected prefix 'iso20_ac_generatedFunctionNumbersType_'

class evseNotificationType(Enum):
    Pause = 0
    ExitStandby = 1
    Terminate = 2
    ScheduleRenegotiation = 3
    ServiceRenegotiation = 4
    MeteringConfirmation = 5


class responseCodeType(Enum):
    OK = 0
    OK_CertificateExpiresSoon = 1
    OK_NewSessionEstablished = 2
    OK_OldSessionJoined = 3
    OK_PowerToleranceConfirmed = 4
    WARNING_AuthorizationSelectionInvalid = 5
    WARNING_CertificateExpired = 6
    WARNING_CertificateNotYetValid = 7
    WARNING_CertificateRevoked = 8
    WARNING_CertificateValidationError = 9
    WARNING_ChallengeInvalid = 10
    WARNING_EIMAuthorizationFailure = 11
    WARNING_eMSPUnknown = 12
    WARNING_EVPowerProfileViolation = 13
    WARNING_GeneralPnCAuthorizationError = 14
    WARNING_NoCertificateAvailable = 15
    WARNING_NoContractMatchingPCIDFound = 16
    WARNING_PowerToleranceNotConfirmed = 17
    WARNING_ScheduleRenegotiationFailed = 18
    WARNING_StandbyNotAllowed = 19
    WARNING_WPT = 20
    FAILED = 21
    FAILED_AssociationError = 22
    FAILED_ContactorError = 23
    FAILED_EVPowerProfileInvalid = 24
    FAILED_EVPowerProfileViolation = 25
    FAILED_MeteringSignatureNotValid = 26
    FAILED_NoEnergyTransferServiceSelected = 27
    FAILED_NoServiceRenegotiationSupported = 28
    FAILED_PauseNotAllowed = 29
    FAILED_PowerDeliveryNotApplied = 30
    FAILED_PowerToleranceNotConfirmed = 31
    FAILED_ScheduleRenegotiation = 32
    FAILED_ScheduleSelectionInvalid = 33
    FAILED_SequenceError = 34
    FAILED_ServiceIDInvalid = 35
    FAILED_ServiceSelectionInvalid = 36
    FAILED_SignatureError = 37
    FAILED_UnknownSession = 38
    FAILED_WrongChargeParameter = 39


def TransformType(Algorithm:str, *, ANY:bytearray|None=None, XPath:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    if XPath is not None:
        j["XPath"] = {"characters": [ord(c) for c in XPath], "charactersLen": len(XPath)}
    return j

def TransformsType(Transform:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "Transform": Transform
    }
    return j

def DSAKeyValueType(Y:bytearray, *, P:bytearray|None=None, Q:bytearray|None=None, G:bytearray|None=None, J:bytearray|None=None, Seed:bytearray|None=None, PgenCounter:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Y": {"bytes": list(Y), "bytesLen": len(Y)}
    }
    if P is not None:
        j["P"] = {"bytes": list(P), "bytesLen": len(P)}
    if Q is not None:
        j["Q"] = {"bytes": list(Q), "bytesLen": len(Q)}
    if G is not None:
        j["G"] = {"bytes": list(G), "bytesLen": len(G)}
    if J is not None:
        j["J"] = {"bytes": list(J), "bytesLen": len(J)}
    if Seed is not None:
        j["Seed"] = {"bytes": list(Seed), "bytesLen": len(Seed)}
    if PgenCounter is not None:
        j["PgenCounter"] = {"bytes": list(PgenCounter), "bytesLen": len(PgenCounter)}
    return j

def X509IssuerSerialType(X509IssuerName:str, X509SerialNumber:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "X509IssuerName": {"characters": [ord(c) for c in X509IssuerName], "charactersLen": len(X509IssuerName)},
        "X509SerialNumber": X509SerialNumber
    }
    return j

def DigestMethodType(Algorithm:str, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def RSAKeyValueType(Modulus:bytearray, Exponent:bytearray)->dict[str, Any]:
    j:dict[str, Any] = {
        "Modulus": {"bytes": list(Modulus), "bytesLen": len(Modulus)},
        "Exponent": {"bytes": list(Exponent), "bytesLen": len(Exponent)}
    }
    return j

def CanonicalizationMethodType(Algorithm:str, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def SignatureMethodType(Algorithm:str, *, HMACOutputLength:dict[str, Any]|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if HMACOutputLength is not None:
        j["HMACOutputLength"] = HMACOutputLength
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def KeyValueType(*, DSAKeyValue:dict[str, Any]|None=None, RSAKeyValue:dict[str, Any]|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if DSAKeyValue is not None:
        j["DSAKeyValue"] = DSAKeyValue
    if RSAKeyValue is not None:
        j["RSAKeyValue"] = RSAKeyValue
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def ReferenceType(DigestMethod:dict[str, Any], DigestValue:bytearray, *, Id:str|None=None, Type:str|None=None, URI:str|None=None, Transforms:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "DigestMethod": DigestMethod,
        "DigestValue": {"bytes": list(DigestValue), "bytesLen": len(DigestValue)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if Type is not None:
        j["Type"] = {"characters": [ord(c) for c in Type], "charactersLen": len(Type)}
    if URI is not None:
        j["URI"] = {"characters": [ord(c) for c in URI], "charactersLen": len(URI)}
    if Transforms is not None:
        j["Transforms"] = Transforms
    return j

def RetrievalMethodType(*, Type:str|None=None, URI:str|None=None, Transforms:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Type is not None:
        j["Type"] = {"characters": [ord(c) for c in Type], "charactersLen": len(Type)}
    if URI is not None:
        j["URI"] = {"characters": [ord(c) for c in URI], "charactersLen": len(URI)}
    if Transforms is not None:
        j["Transforms"] = Transforms
    return j

def X509DataType(*, X509IssuerSerial:dict[str, Any]|None=None, X509SKI:bytearray|None=None, X509SubjectName:str|None=None, X509Certificate:bytearray|None=None, X509CRL:bytearray|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if X509IssuerSerial is not None:
        j["X509IssuerSerial"] = X509IssuerSerial
    if X509SKI is not None:
        j["X509SKI"] = {"bytes": list(X509SKI), "bytesLen": len(X509SKI)}
    if X509SubjectName is not None:
        j["X509SubjectName"] = {"characters": [ord(c) for c in X509SubjectName], "charactersLen": len(X509SubjectName)}
    if X509Certificate is not None:
        j["X509Certificate"] = {"bytes": list(X509Certificate), "bytesLen": len(X509Certificate)}
    if X509CRL is not None:
        j["X509CRL"] = {"bytes": list(X509CRL), "bytesLen": len(X509CRL)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def PGPDataType(*, choice_1:int|None=None, choice_2:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if choice_1 is not None:
        j["choice_1"] = choice_1
    if choice_2 is not None:
        j["choice_2"] = choice_2
    return j

def SPKIDataType(SPKISexp:bytearray, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SPKISexp": {"bytes": list(SPKISexp), "bytesLen": len(SPKISexp)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def SignedInfoType(CanonicalizationMethod:dict[str, Any], SignatureMethod:dict[str, Any], Reference:list[dict[str, Any]], *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "CanonicalizationMethod": CanonicalizationMethod,
        "SignatureMethod": SignatureMethod,
        "Reference": {"arrayLen": len(Reference), "array": Reference}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def SignatureValueType(CONTENT:bytearray, *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "CONTENT": {"bytes": list(CONTENT), "bytesLen": len(CONTENT)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def KeyInfoType(*, Id:str|None=None, KeyName:str|None=None, KeyValue:dict[str, Any]|None=None, RetrievalMethod:dict[str, Any]|None=None, X509Data:dict[str, Any]|None=None, PGPData:dict[str, Any]|None=None, SPKIData:dict[str, Any]|None=None, MgmtData:str|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if KeyName is not None:
        j["KeyName"] = {"characters": [ord(c) for c in KeyName], "charactersLen": len(KeyName)}
    if KeyValue is not None:
        j["KeyValue"] = KeyValue
    if RetrievalMethod is not None:
        j["RetrievalMethod"] = RetrievalMethod
    if X509Data is not None:
        j["X509Data"] = X509Data
    if PGPData is not None:
        j["PGPData"] = PGPData
    if SPKIData is not None:
        j["SPKIData"] = SPKIData
    if MgmtData is not None:
        j["MgmtData"] = {"characters": [ord(c) for c in MgmtData], "charactersLen": len(MgmtData)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def ObjectType(*, Encoding:str|None=None, Id:str|None=None, MimeType:str|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Encoding is not None:
        j["Encoding"] = {"characters": [ord(c) for c in Encoding], "charactersLen": len(Encoding)}
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if MimeType is not None:
        j["MimeType"] = {"characters": [ord(c) for c in MimeType], "charactersLen": len(MimeType)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def RationalNumberType(Exponent:int, Value:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Exponent": Exponent,
        "Value": Value
    }
    return j

def DetailedCostType(Amount:dict[str, Any], CostPerUnit:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "Amount": Amount,
        "CostPerUnit": CostPerUnit
    }
    return j

def SignatureType(SignedInfo:dict[str, Any], SignatureValue:dict[str, Any], *, Id:str|None=None, KeyInfo:dict[str, Any]|None=None, Object:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SignedInfo": SignedInfo,
        "SignatureValue": SignatureValue
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if KeyInfo is not None:
        j["KeyInfo"] = KeyInfo
    if Object is not None:
        j["Object"] = Object
    return j

def DetailedTaxType(TaxRuleID:int, Amount:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "TaxRuleID": TaxRuleID,
        "Amount": Amount
    }
    return j

def MessageHeaderType(SessionID:bytearray, TimeStamp:int, *, Signature:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SessionID": {"bytes": list(SessionID), "bytesLen": len(SessionID)},
        "TimeStamp": TimeStamp
    }
    if Signature is not None:
        j["Signature"] = Signature
    return j

def SignaturePropertyType(Target:str, *, Id:str|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Target": {"characters": [ord(c) for c in Target], "charactersLen": len(Target)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def AC_CPDReqEnergyTransferModeType(EVMaximumChargePower:dict[str, Any], EVMinimumChargePower:dict[str, Any], *, EVMaximumChargePower_L2:dict[str, Any]|None=None, EVMaximumChargePower_L3:dict[str, Any]|None=None, EVMinimumChargePower_L2:dict[str, Any]|None=None, EVMinimumChargePower_L3:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVMaximumChargePower": EVMaximumChargePower,
        "EVMinimumChargePower": EVMinimumChargePower
    }
    if EVMaximumChargePower_L2 is not None:
        j["EVMaximumChargePower_L2"] = EVMaximumChargePower_L2
    if EVMaximumChargePower_L3 is not None:
        j["EVMaximumChargePower_L3"] = EVMaximumChargePower_L3
    if EVMinimumChargePower_L2 is not None:
        j["EVMinimumChargePower_L2"] = EVMinimumChargePower_L2
    if EVMinimumChargePower_L3 is not None:
        j["EVMinimumChargePower_L3"] = EVMinimumChargePower_L3
    return j

def DisplayParametersType(*, PresentSOC:int|None=None, MinimumSOC:int|None=None, TargetSOC:int|None=None, MaximumSOC:int|None=None, RemainingTimeToMinimumSOC:int|None=None, RemainingTimeToTargetSOC:int|None=None, RemainingTimeToMaximumSOC:int|None=None, ChargingComplete:int|None=None, BatteryEnergyCapacity:dict[str, Any]|None=None, InletHot:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if PresentSOC is not None:
        j["PresentSOC"] = PresentSOC
    if MinimumSOC is not None:
        j["MinimumSOC"] = MinimumSOC
    if TargetSOC is not None:
        j["TargetSOC"] = TargetSOC
    if MaximumSOC is not None:
        j["MaximumSOC"] = MaximumSOC
    if RemainingTimeToMinimumSOC is not None:
        j["RemainingTimeToMinimumSOC"] = RemainingTimeToMinimumSOC
    if RemainingTimeToTargetSOC is not None:
        j["RemainingTimeToTargetSOC"] = RemainingTimeToTargetSOC
    if RemainingTimeToMaximumSOC is not None:
        j["RemainingTimeToMaximumSOC"] = RemainingTimeToMaximumSOC
    if ChargingComplete is not None:
        j["ChargingComplete"] = ChargingComplete
    if BatteryEnergyCapacity is not None:
        j["BatteryEnergyCapacity"] = BatteryEnergyCapacity
    if InletHot is not None:
        j["InletHot"] = InletHot
    return j

def AC_CPDResEnergyTransferModeType(EVSEMaximumChargePower:dict[str, Any], EVSEMinimumChargePower:dict[str, Any], EVSENominalFrequency:dict[str, Any], *, EVSEMaximumChargePower_L2:dict[str, Any]|None=None, EVSEMaximumChargePower_L3:dict[str, Any]|None=None, EVSEMinimumChargePower_L2:dict[str, Any]|None=None, EVSEMinimumChargePower_L3:dict[str, Any]|None=None, MaximumPowerAsymmetry:dict[str, Any]|None=None, EVSEPowerRampLimitation:dict[str, Any]|None=None, EVSEPresentActivePower:dict[str, Any]|None=None, EVSEPresentActivePower_L2:dict[str, Any]|None=None, EVSEPresentActivePower_L3:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVSEMaximumChargePower": EVSEMaximumChargePower,
        "EVSEMinimumChargePower": EVSEMinimumChargePower,
        "EVSENominalFrequency": EVSENominalFrequency
    }
    if EVSEMaximumChargePower_L2 is not None:
        j["EVSEMaximumChargePower_L2"] = EVSEMaximumChargePower_L2
    if EVSEMaximumChargePower_L3 is not None:
        j["EVSEMaximumChargePower_L3"] = EVSEMaximumChargePower_L3
    if EVSEMinimumChargePower_L2 is not None:
        j["EVSEMinimumChargePower_L2"] = EVSEMinimumChargePower_L2
    if EVSEMinimumChargePower_L3 is not None:
        j["EVSEMinimumChargePower_L3"] = EVSEMinimumChargePower_L3
    if MaximumPowerAsymmetry is not None:
        j["MaximumPowerAsymmetry"] = MaximumPowerAsymmetry
    if EVSEPowerRampLimitation is not None:
        j["EVSEPowerRampLimitation"] = EVSEPowerRampLimitation
    if EVSEPresentActivePower is not None:
        j["EVSEPresentActivePower"] = EVSEPresentActivePower
    if EVSEPresentActivePower_L2 is not None:
        j["EVSEPresentActivePower_L2"] = EVSEPresentActivePower_L2
    if EVSEPresentActivePower_L3 is not None:
        j["EVSEPresentActivePower_L3"] = EVSEPresentActivePower_L3
    return j

def EVSEStatusType(NotificationMaxDelay:int, EVSENotification:evseNotificationType)->dict[str, Any]:
    j:dict[str, Any] = {
        "NotificationMaxDelay": NotificationMaxDelay,
        "EVSENotification": EVSENotification.value
    }
    return j

def Dynamic_AC_CLReqControlModeType(EVTargetEnergyRequest:dict[str, Any], EVMaximumEnergyRequest:dict[str, Any], EVMinimumEnergyRequest:dict[str, Any], EVMaximumChargePower:dict[str, Any], EVMinimumChargePower:dict[str, Any], EVPresentActivePower:dict[str, Any], EVPresentReactivePower:dict[str, Any], *, DepartureTime:int|None=None, EVMaximumChargePower_L2:dict[str, Any]|None=None, EVMaximumChargePower_L3:dict[str, Any]|None=None, EVMinimumChargePower_L2:dict[str, Any]|None=None, EVMinimumChargePower_L3:dict[str, Any]|None=None, EVPresentActivePower_L2:dict[str, Any]|None=None, EVPresentActivePower_L3:dict[str, Any]|None=None, EVPresentReactivePower_L2:dict[str, Any]|None=None, EVPresentReactivePower_L3:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVTargetEnergyRequest": EVTargetEnergyRequest,
        "EVMaximumEnergyRequest": EVMaximumEnergyRequest,
        "EVMinimumEnergyRequest": EVMinimumEnergyRequest,
        "EVMaximumChargePower": EVMaximumChargePower,
        "EVMinimumChargePower": EVMinimumChargePower,
        "EVPresentActivePower": EVPresentActivePower,
        "EVPresentReactivePower": EVPresentReactivePower
    }
    if DepartureTime is not None:
        j["DepartureTime"] = DepartureTime
    if EVMaximumChargePower_L2 is not None:
        j["EVMaximumChargePower_L2"] = EVMaximumChargePower_L2
    if EVMaximumChargePower_L3 is not None:
        j["EVMaximumChargePower_L3"] = EVMaximumChargePower_L3
    if EVMinimumChargePower_L2 is not None:
        j["EVMinimumChargePower_L2"] = EVMinimumChargePower_L2
    if EVMinimumChargePower_L3 is not None:
        j["EVMinimumChargePower_L3"] = EVMinimumChargePower_L3
    if EVPresentActivePower_L2 is not None:
        j["EVPresentActivePower_L2"] = EVPresentActivePower_L2
    if EVPresentActivePower_L3 is not None:
        j["EVPresentActivePower_L3"] = EVPresentActivePower_L3
    if EVPresentReactivePower_L2 is not None:
        j["EVPresentReactivePower_L2"] = EVPresentReactivePower_L2
    if EVPresentReactivePower_L3 is not None:
        j["EVPresentReactivePower_L3"] = EVPresentReactivePower_L3
    return j

def Scheduled_AC_CLReqControlModeType(EVPresentActivePower:dict[str, Any], *, EVTargetEnergyRequest:dict[str, Any]|None=None, EVMaximumEnergyRequest:dict[str, Any]|None=None, EVMinimumEnergyRequest:dict[str, Any]|None=None, EVMaximumChargePower:dict[str, Any]|None=None, EVMaximumChargePower_L2:dict[str, Any]|None=None, EVMaximumChargePower_L3:dict[str, Any]|None=None, EVMinimumChargePower:dict[str, Any]|None=None, EVMinimumChargePower_L2:dict[str, Any]|None=None, EVMinimumChargePower_L3:dict[str, Any]|None=None, EVPresentActivePower_L2:dict[str, Any]|None=None, EVPresentActivePower_L3:dict[str, Any]|None=None, EVPresentReactivePower:dict[str, Any]|None=None, EVPresentReactivePower_L2:dict[str, Any]|None=None, EVPresentReactivePower_L3:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVPresentActivePower": EVPresentActivePower
    }
    if EVTargetEnergyRequest is not None:
        j["EVTargetEnergyRequest"] = EVTargetEnergyRequest
    if EVMaximumEnergyRequest is not None:
        j["EVMaximumEnergyRequest"] = EVMaximumEnergyRequest
    if EVMinimumEnergyRequest is not None:
        j["EVMinimumEnergyRequest"] = EVMinimumEnergyRequest
    if EVMaximumChargePower is not None:
        j["EVMaximumChargePower"] = EVMaximumChargePower
    if EVMaximumChargePower_L2 is not None:
        j["EVMaximumChargePower_L2"] = EVMaximumChargePower_L2
    if EVMaximumChargePower_L3 is not None:
        j["EVMaximumChargePower_L3"] = EVMaximumChargePower_L3
    if EVMinimumChargePower is not None:
        j["EVMinimumChargePower"] = EVMinimumChargePower
    if EVMinimumChargePower_L2 is not None:
        j["EVMinimumChargePower_L2"] = EVMinimumChargePower_L2
    if EVMinimumChargePower_L3 is not None:
        j["EVMinimumChargePower_L3"] = EVMinimumChargePower_L3
    if EVPresentActivePower_L2 is not None:
        j["EVPresentActivePower_L2"] = EVPresentActivePower_L2
    if EVPresentActivePower_L3 is not None:
        j["EVPresentActivePower_L3"] = EVPresentActivePower_L3
    if EVPresentReactivePower is not None:
        j["EVPresentReactivePower"] = EVPresentReactivePower
    if EVPresentReactivePower_L2 is not None:
        j["EVPresentReactivePower_L2"] = EVPresentReactivePower_L2
    if EVPresentReactivePower_L3 is not None:
        j["EVPresentReactivePower_L3"] = EVPresentReactivePower_L3
    return j

def CLReqControlModeType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def MeterInfoType(MeterID:str, ChargedEnergyReadingWh:int, *, BPT_DischargedEnergyReadingWh:int|None=None, CapacitiveEnergyReadingVARh:int|None=None, BPT_InductiveEnergyReadingVARh:int|None=None, MeterSignature:bytearray|None=None, MeterStatus:int|None=None, MeterTimestamp:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "MeterID": {"characters": [ord(c) for c in MeterID], "charactersLen": len(MeterID)},
        "ChargedEnergyReadingWh": ChargedEnergyReadingWh
    }
    if BPT_DischargedEnergyReadingWh is not None:
        j["BPT_DischargedEnergyReadingWh"] = BPT_DischargedEnergyReadingWh
    if CapacitiveEnergyReadingVARh is not None:
        j["CapacitiveEnergyReadingVARh"] = CapacitiveEnergyReadingVARh
    if BPT_InductiveEnergyReadingVARh is not None:
        j["BPT_InductiveEnergyReadingVARh"] = BPT_InductiveEnergyReadingVARh
    if MeterSignature is not None:
        j["MeterSignature"] = {"bytes": list(MeterSignature), "bytesLen": len(MeterSignature)}
    if MeterStatus is not None:
        j["MeterStatus"] = MeterStatus
    if MeterTimestamp is not None:
        j["MeterTimestamp"] = MeterTimestamp
    return j

def ReceiptType(TimeAnchor:int, TaxCosts:list[dict[str, Any]], *, EnergyCosts:dict[str, Any]|None=None, OccupancyCosts:dict[str, Any]|None=None, AdditionalServicesCosts:dict[str, Any]|None=None, OverstayCosts:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "TimeAnchor": TimeAnchor,
        "TaxCosts": {"arrayLen": len(TaxCosts), "array": TaxCosts}
    }
    if EnergyCosts is not None:
        j["EnergyCosts"] = EnergyCosts
    if OccupancyCosts is not None:
        j["OccupancyCosts"] = OccupancyCosts
    if AdditionalServicesCosts is not None:
        j["AdditionalServicesCosts"] = AdditionalServicesCosts
    if OverstayCosts is not None:
        j["OverstayCosts"] = OverstayCosts
    return j

def Scheduled_AC_CLResControlModeType(*, EVSETargetActivePower:dict[str, Any]|None=None, EVSETargetActivePower_L2:dict[str, Any]|None=None, EVSETargetActivePower_L3:dict[str, Any]|None=None, EVSETargetReactivePower:dict[str, Any]|None=None, EVSETargetReactivePower_L2:dict[str, Any]|None=None, EVSETargetReactivePower_L3:dict[str, Any]|None=None, EVSEPresentActivePower:dict[str, Any]|None=None, EVSEPresentActivePower_L2:dict[str, Any]|None=None, EVSEPresentActivePower_L3:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if EVSETargetActivePower is not None:
        j["EVSETargetActivePower"] = EVSETargetActivePower
    if EVSETargetActivePower_L2 is not None:
        j["EVSETargetActivePower_L2"] = EVSETargetActivePower_L2
    if EVSETargetActivePower_L3 is not None:
        j["EVSETargetActivePower_L3"] = EVSETargetActivePower_L3
    if EVSETargetReactivePower is not None:
        j["EVSETargetReactivePower"] = EVSETargetReactivePower
    if EVSETargetReactivePower_L2 is not None:
        j["EVSETargetReactivePower_L2"] = EVSETargetReactivePower_L2
    if EVSETargetReactivePower_L3 is not None:
        j["EVSETargetReactivePower_L3"] = EVSETargetReactivePower_L3
    if EVSEPresentActivePower is not None:
        j["EVSEPresentActivePower"] = EVSEPresentActivePower
    if EVSEPresentActivePower_L2 is not None:
        j["EVSEPresentActivePower_L2"] = EVSEPresentActivePower_L2
    if EVSEPresentActivePower_L3 is not None:
        j["EVSEPresentActivePower_L3"] = EVSEPresentActivePower_L3
    return j

def Dynamic_AC_CLResControlModeType(EVSETargetActivePower:dict[str, Any], *, DepartureTime:int|None=None, MinimumSOC:int|None=None, TargetSOC:int|None=None, AckMaxDelay:int|None=None, EVSETargetActivePower_L2:dict[str, Any]|None=None, EVSETargetActivePower_L3:dict[str, Any]|None=None, EVSETargetReactivePower:dict[str, Any]|None=None, EVSETargetReactivePower_L2:dict[str, Any]|None=None, EVSETargetReactivePower_L3:dict[str, Any]|None=None, EVSEPresentActivePower:dict[str, Any]|None=None, EVSEPresentActivePower_L2:dict[str, Any]|None=None, EVSEPresentActivePower_L3:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVSETargetActivePower": EVSETargetActivePower
    }
    if DepartureTime is not None:
        j["DepartureTime"] = DepartureTime
    if MinimumSOC is not None:
        j["MinimumSOC"] = MinimumSOC
    if TargetSOC is not None:
        j["TargetSOC"] = TargetSOC
    if AckMaxDelay is not None:
        j["AckMaxDelay"] = AckMaxDelay
    if EVSETargetActivePower_L2 is not None:
        j["EVSETargetActivePower_L2"] = EVSETargetActivePower_L2
    if EVSETargetActivePower_L3 is not None:
        j["EVSETargetActivePower_L3"] = EVSETargetActivePower_L3
    if EVSETargetReactivePower is not None:
        j["EVSETargetReactivePower"] = EVSETargetReactivePower
    if EVSETargetReactivePower_L2 is not None:
        j["EVSETargetReactivePower_L2"] = EVSETargetReactivePower_L2
    if EVSETargetReactivePower_L3 is not None:
        j["EVSETargetReactivePower_L3"] = EVSETargetReactivePower_L3
    if EVSEPresentActivePower is not None:
        j["EVSEPresentActivePower"] = EVSEPresentActivePower
    if EVSEPresentActivePower_L2 is not None:
        j["EVSEPresentActivePower_L2"] = EVSEPresentActivePower_L2
    if EVSEPresentActivePower_L3 is not None:
        j["EVSEPresentActivePower_L3"] = EVSEPresentActivePower_L3
    return j

def CLResControlModeType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def BPT_AC_CPDReqEnergyTransferModeType(EVMaximumChargePower:dict[str, Any], EVMinimumChargePower:dict[str, Any], EVMaximumDischargePower:dict[str, Any], EVMinimumDischargePower:dict[str, Any], *, EVMaximumChargePower_L2:dict[str, Any]|None=None, EVMaximumChargePower_L3:dict[str, Any]|None=None, EVMinimumChargePower_L2:dict[str, Any]|None=None, EVMinimumChargePower_L3:dict[str, Any]|None=None, EVMaximumDischargePower_L2:dict[str, Any]|None=None, EVMaximumDischargePower_L3:dict[str, Any]|None=None, EVMinimumDischargePower_L2:dict[str, Any]|None=None, EVMinimumDischargePower_L3:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVMaximumChargePower": EVMaximumChargePower,
        "EVMinimumChargePower": EVMinimumChargePower,
        "EVMaximumDischargePower": EVMaximumDischargePower,
        "EVMinimumDischargePower": EVMinimumDischargePower
    }
    if EVMaximumChargePower_L2 is not None:
        j["EVMaximumChargePower_L2"] = EVMaximumChargePower_L2
    if EVMaximumChargePower_L3 is not None:
        j["EVMaximumChargePower_L3"] = EVMaximumChargePower_L3
    if EVMinimumChargePower_L2 is not None:
        j["EVMinimumChargePower_L2"] = EVMinimumChargePower_L2
    if EVMinimumChargePower_L3 is not None:
        j["EVMinimumChargePower_L3"] = EVMinimumChargePower_L3
    if EVMaximumDischargePower_L2 is not None:
        j["EVMaximumDischargePower_L2"] = EVMaximumDischargePower_L2
    if EVMaximumDischargePower_L3 is not None:
        j["EVMaximumDischargePower_L3"] = EVMaximumDischargePower_L3
    if EVMinimumDischargePower_L2 is not None:
        j["EVMinimumDischargePower_L2"] = EVMinimumDischargePower_L2
    if EVMinimumDischargePower_L3 is not None:
        j["EVMinimumDischargePower_L3"] = EVMinimumDischargePower_L3
    return j

def AC_ChargeParameterDiscoveryReqType(Header:dict[str, Any], *, AC_CPDReqEnergyTransferMode:dict[str, Any]|None=None, BPT_AC_CPDReqEnergyTransferMode:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header
    }
    if AC_CPDReqEnergyTransferMode is not None:
        j["AC_CPDReqEnergyTransferMode"] = AC_CPDReqEnergyTransferMode
    if BPT_AC_CPDReqEnergyTransferMode is not None:
        j["BPT_AC_CPDReqEnergyTransferMode"] = BPT_AC_CPDReqEnergyTransferMode
    return j

def BPT_AC_CPDResEnergyTransferModeType(EVSEMaximumChargePower:dict[str, Any], EVSEMinimumChargePower:dict[str, Any], EVSENominalFrequency:dict[str, Any], EVSEMaximumDischargePower:dict[str, Any], EVSEMinimumDischargePower:dict[str, Any], *, EVSEMaximumChargePower_L2:dict[str, Any]|None=None, EVSEMaximumChargePower_L3:dict[str, Any]|None=None, EVSEMinimumChargePower_L2:dict[str, Any]|None=None, EVSEMinimumChargePower_L3:dict[str, Any]|None=None, MaximumPowerAsymmetry:dict[str, Any]|None=None, EVSEPowerRampLimitation:dict[str, Any]|None=None, EVSEPresentActivePower:dict[str, Any]|None=None, EVSEPresentActivePower_L2:dict[str, Any]|None=None, EVSEPresentActivePower_L3:dict[str, Any]|None=None, EVSEMaximumDischargePower_L2:dict[str, Any]|None=None, EVSEMaximumDischargePower_L3:dict[str, Any]|None=None, EVSEMinimumDischargePower_L2:dict[str, Any]|None=None, EVSEMinimumDischargePower_L3:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVSEMaximumChargePower": EVSEMaximumChargePower,
        "EVSEMinimumChargePower": EVSEMinimumChargePower,
        "EVSENominalFrequency": EVSENominalFrequency,
        "EVSEMaximumDischargePower": EVSEMaximumDischargePower,
        "EVSEMinimumDischargePower": EVSEMinimumDischargePower
    }
    if EVSEMaximumChargePower_L2 is not None:
        j["EVSEMaximumChargePower_L2"] = EVSEMaximumChargePower_L2
    if EVSEMaximumChargePower_L3 is not None:
        j["EVSEMaximumChargePower_L3"] = EVSEMaximumChargePower_L3
    if EVSEMinimumChargePower_L2 is not None:
        j["EVSEMinimumChargePower_L2"] = EVSEMinimumChargePower_L2
    if EVSEMinimumChargePower_L3 is not None:
        j["EVSEMinimumChargePower_L3"] = EVSEMinimumChargePower_L3
    if MaximumPowerAsymmetry is not None:
        j["MaximumPowerAsymmetry"] = MaximumPowerAsymmetry
    if EVSEPowerRampLimitation is not None:
        j["EVSEPowerRampLimitation"] = EVSEPowerRampLimitation
    if EVSEPresentActivePower is not None:
        j["EVSEPresentActivePower"] = EVSEPresentActivePower
    if EVSEPresentActivePower_L2 is not None:
        j["EVSEPresentActivePower_L2"] = EVSEPresentActivePower_L2
    if EVSEPresentActivePower_L3 is not None:
        j["EVSEPresentActivePower_L3"] = EVSEPresentActivePower_L3
    if EVSEMaximumDischargePower_L2 is not None:
        j["EVSEMaximumDischargePower_L2"] = EVSEMaximumDischargePower_L2
    if EVSEMaximumDischargePower_L3 is not None:
        j["EVSEMaximumDischargePower_L3"] = EVSEMaximumDischargePower_L3
    if EVSEMinimumDischargePower_L2 is not None:
        j["EVSEMinimumDischargePower_L2"] = EVSEMinimumDischargePower_L2
    if EVSEMinimumDischargePower_L3 is not None:
        j["EVSEMinimumDischargePower_L3"] = EVSEMinimumDischargePower_L3
    return j

def AC_ChargeParameterDiscoveryResType(Header:dict[str, Any], ResponseCode:responseCodeType, *, AC_CPDResEnergyTransferMode:dict[str, Any]|None=None, BPT_AC_CPDResEnergyTransferMode:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value
    }
    if AC_CPDResEnergyTransferMode is not None:
        j["AC_CPDResEnergyTransferMode"] = AC_CPDResEnergyTransferMode
    if BPT_AC_CPDResEnergyTransferMode is not None:
        j["BPT_AC_CPDResEnergyTransferMode"] = BPT_AC_CPDResEnergyTransferMode
    return j

def BPT_Scheduled_AC_CLReqControlModeType(EVPresentActivePower:dict[str, Any], *, EVTargetEnergyRequest:dict[str, Any]|None=None, EVMaximumEnergyRequest:dict[str, Any]|None=None, EVMinimumEnergyRequest:dict[str, Any]|None=None, EVMaximumChargePower:dict[str, Any]|None=None, EVMaximumChargePower_L2:dict[str, Any]|None=None, EVMaximumChargePower_L3:dict[str, Any]|None=None, EVMinimumChargePower:dict[str, Any]|None=None, EVMinimumChargePower_L2:dict[str, Any]|None=None, EVMinimumChargePower_L3:dict[str, Any]|None=None, EVPresentActivePower_L2:dict[str, Any]|None=None, EVPresentActivePower_L3:dict[str, Any]|None=None, EVPresentReactivePower:dict[str, Any]|None=None, EVPresentReactivePower_L2:dict[str, Any]|None=None, EVPresentReactivePower_L3:dict[str, Any]|None=None, EVMaximumDischargePower:dict[str, Any]|None=None, EVMaximumDischargePower_L2:dict[str, Any]|None=None, EVMaximumDischargePower_L3:dict[str, Any]|None=None, EVMinimumDischargePower:dict[str, Any]|None=None, EVMinimumDischargePower_L2:dict[str, Any]|None=None, EVMinimumDischargePower_L3:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVPresentActivePower": EVPresentActivePower
    }
    if EVTargetEnergyRequest is not None:
        j["EVTargetEnergyRequest"] = EVTargetEnergyRequest
    if EVMaximumEnergyRequest is not None:
        j["EVMaximumEnergyRequest"] = EVMaximumEnergyRequest
    if EVMinimumEnergyRequest is not None:
        j["EVMinimumEnergyRequest"] = EVMinimumEnergyRequest
    if EVMaximumChargePower is not None:
        j["EVMaximumChargePower"] = EVMaximumChargePower
    if EVMaximumChargePower_L2 is not None:
        j["EVMaximumChargePower_L2"] = EVMaximumChargePower_L2
    if EVMaximumChargePower_L3 is not None:
        j["EVMaximumChargePower_L3"] = EVMaximumChargePower_L3
    if EVMinimumChargePower is not None:
        j["EVMinimumChargePower"] = EVMinimumChargePower
    if EVMinimumChargePower_L2 is not None:
        j["EVMinimumChargePower_L2"] = EVMinimumChargePower_L2
    if EVMinimumChargePower_L3 is not None:
        j["EVMinimumChargePower_L3"] = EVMinimumChargePower_L3
    if EVPresentActivePower_L2 is not None:
        j["EVPresentActivePower_L2"] = EVPresentActivePower_L2
    if EVPresentActivePower_L3 is not None:
        j["EVPresentActivePower_L3"] = EVPresentActivePower_L3
    if EVPresentReactivePower is not None:
        j["EVPresentReactivePower"] = EVPresentReactivePower
    if EVPresentReactivePower_L2 is not None:
        j["EVPresentReactivePower_L2"] = EVPresentReactivePower_L2
    if EVPresentReactivePower_L3 is not None:
        j["EVPresentReactivePower_L3"] = EVPresentReactivePower_L3
    if EVMaximumDischargePower is not None:
        j["EVMaximumDischargePower"] = EVMaximumDischargePower
    if EVMaximumDischargePower_L2 is not None:
        j["EVMaximumDischargePower_L2"] = EVMaximumDischargePower_L2
    if EVMaximumDischargePower_L3 is not None:
        j["EVMaximumDischargePower_L3"] = EVMaximumDischargePower_L3
    if EVMinimumDischargePower is not None:
        j["EVMinimumDischargePower"] = EVMinimumDischargePower
    if EVMinimumDischargePower_L2 is not None:
        j["EVMinimumDischargePower_L2"] = EVMinimumDischargePower_L2
    if EVMinimumDischargePower_L3 is not None:
        j["EVMinimumDischargePower_L3"] = EVMinimumDischargePower_L3
    return j

def BPT_Scheduled_AC_CLResControlModeType(*, EVSETargetActivePower:dict[str, Any]|None=None, EVSETargetActivePower_L2:dict[str, Any]|None=None, EVSETargetActivePower_L3:dict[str, Any]|None=None, EVSETargetReactivePower:dict[str, Any]|None=None, EVSETargetReactivePower_L2:dict[str, Any]|None=None, EVSETargetReactivePower_L3:dict[str, Any]|None=None, EVSEPresentActivePower:dict[str, Any]|None=None, EVSEPresentActivePower_L2:dict[str, Any]|None=None, EVSEPresentActivePower_L3:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if EVSETargetActivePower is not None:
        j["EVSETargetActivePower"] = EVSETargetActivePower
    if EVSETargetActivePower_L2 is not None:
        j["EVSETargetActivePower_L2"] = EVSETargetActivePower_L2
    if EVSETargetActivePower_L3 is not None:
        j["EVSETargetActivePower_L3"] = EVSETargetActivePower_L3
    if EVSETargetReactivePower is not None:
        j["EVSETargetReactivePower"] = EVSETargetReactivePower
    if EVSETargetReactivePower_L2 is not None:
        j["EVSETargetReactivePower_L2"] = EVSETargetReactivePower_L2
    if EVSETargetReactivePower_L3 is not None:
        j["EVSETargetReactivePower_L3"] = EVSETargetReactivePower_L3
    if EVSEPresentActivePower is not None:
        j["EVSEPresentActivePower"] = EVSEPresentActivePower
    if EVSEPresentActivePower_L2 is not None:
        j["EVSEPresentActivePower_L2"] = EVSEPresentActivePower_L2
    if EVSEPresentActivePower_L3 is not None:
        j["EVSEPresentActivePower_L3"] = EVSEPresentActivePower_L3
    return j

def BPT_Dynamic_AC_CLReqControlModeType(EVTargetEnergyRequest:dict[str, Any], EVMaximumEnergyRequest:dict[str, Any], EVMinimumEnergyRequest:dict[str, Any], EVMaximumChargePower:dict[str, Any], EVMinimumChargePower:dict[str, Any], EVPresentActivePower:dict[str, Any], EVPresentReactivePower:dict[str, Any], EVMaximumDischargePower:dict[str, Any], EVMinimumDischargePower:dict[str, Any], *, DepartureTime:int|None=None, EVMaximumChargePower_L2:dict[str, Any]|None=None, EVMaximumChargePower_L3:dict[str, Any]|None=None, EVMinimumChargePower_L2:dict[str, Any]|None=None, EVMinimumChargePower_L3:dict[str, Any]|None=None, EVPresentActivePower_L2:dict[str, Any]|None=None, EVPresentActivePower_L3:dict[str, Any]|None=None, EVPresentReactivePower_L2:dict[str, Any]|None=None, EVPresentReactivePower_L3:dict[str, Any]|None=None, EVMaximumDischargePower_L2:dict[str, Any]|None=None, EVMaximumDischargePower_L3:dict[str, Any]|None=None, EVMinimumDischargePower_L2:dict[str, Any]|None=None, EVMinimumDischargePower_L3:dict[str, Any]|None=None, EVMaximumV2XEnergyRequest:dict[str, Any]|None=None, EVMinimumV2XEnergyRequest:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVTargetEnergyRequest": EVTargetEnergyRequest,
        "EVMaximumEnergyRequest": EVMaximumEnergyRequest,
        "EVMinimumEnergyRequest": EVMinimumEnergyRequest,
        "EVMaximumChargePower": EVMaximumChargePower,
        "EVMinimumChargePower": EVMinimumChargePower,
        "EVPresentActivePower": EVPresentActivePower,
        "EVPresentReactivePower": EVPresentReactivePower,
        "EVMaximumDischargePower": EVMaximumDischargePower,
        "EVMinimumDischargePower": EVMinimumDischargePower
    }
    if DepartureTime is not None:
        j["DepartureTime"] = DepartureTime
    if EVMaximumChargePower_L2 is not None:
        j["EVMaximumChargePower_L2"] = EVMaximumChargePower_L2
    if EVMaximumChargePower_L3 is not None:
        j["EVMaximumChargePower_L3"] = EVMaximumChargePower_L3
    if EVMinimumChargePower_L2 is not None:
        j["EVMinimumChargePower_L2"] = EVMinimumChargePower_L2
    if EVMinimumChargePower_L3 is not None:
        j["EVMinimumChargePower_L3"] = EVMinimumChargePower_L3
    if EVPresentActivePower_L2 is not None:
        j["EVPresentActivePower_L2"] = EVPresentActivePower_L2
    if EVPresentActivePower_L3 is not None:
        j["EVPresentActivePower_L3"] = EVPresentActivePower_L3
    if EVPresentReactivePower_L2 is not None:
        j["EVPresentReactivePower_L2"] = EVPresentReactivePower_L2
    if EVPresentReactivePower_L3 is not None:
        j["EVPresentReactivePower_L3"] = EVPresentReactivePower_L3
    if EVMaximumDischargePower_L2 is not None:
        j["EVMaximumDischargePower_L2"] = EVMaximumDischargePower_L2
    if EVMaximumDischargePower_L3 is not None:
        j["EVMaximumDischargePower_L3"] = EVMaximumDischargePower_L3
    if EVMinimumDischargePower_L2 is not None:
        j["EVMinimumDischargePower_L2"] = EVMinimumDischargePower_L2
    if EVMinimumDischargePower_L3 is not None:
        j["EVMinimumDischargePower_L3"] = EVMinimumDischargePower_L3
    if EVMaximumV2XEnergyRequest is not None:
        j["EVMaximumV2XEnergyRequest"] = EVMaximumV2XEnergyRequest
    if EVMinimumV2XEnergyRequest is not None:
        j["EVMinimumV2XEnergyRequest"] = EVMinimumV2XEnergyRequest
    return j

def AC_ChargeLoopReqType(Header:dict[str, Any], MeterInfoRequested:int, *, DisplayParameters:dict[str, Any]|None=None, BPT_Dynamic_AC_CLReqControlMode:dict[str, Any]|None=None, BPT_Scheduled_AC_CLReqControlMode:dict[str, Any]|None=None, CLReqControlMode:dict[str, Any]|None=None, Dynamic_AC_CLReqControlMode:dict[str, Any]|None=None, Scheduled_AC_CLReqControlMode:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "MeterInfoRequested": MeterInfoRequested
    }
    if DisplayParameters is not None:
        j["DisplayParameters"] = DisplayParameters
    if BPT_Dynamic_AC_CLReqControlMode is not None:
        j["BPT_Dynamic_AC_CLReqControlMode"] = BPT_Dynamic_AC_CLReqControlMode
    if BPT_Scheduled_AC_CLReqControlMode is not None:
        j["BPT_Scheduled_AC_CLReqControlMode"] = BPT_Scheduled_AC_CLReqControlMode
    if CLReqControlMode is not None:
        j["CLReqControlMode"] = CLReqControlMode
    if Dynamic_AC_CLReqControlMode is not None:
        j["Dynamic_AC_CLReqControlMode"] = Dynamic_AC_CLReqControlMode
    if Scheduled_AC_CLReqControlMode is not None:
        j["Scheduled_AC_CLReqControlMode"] = Scheduled_AC_CLReqControlMode
    return j

def BPT_Dynamic_AC_CLResControlModeType(EVSETargetActivePower:dict[str, Any], *, DepartureTime:int|None=None, MinimumSOC:int|None=None, TargetSOC:int|None=None, AckMaxDelay:int|None=None, EVSETargetActivePower_L2:dict[str, Any]|None=None, EVSETargetActivePower_L3:dict[str, Any]|None=None, EVSETargetReactivePower:dict[str, Any]|None=None, EVSETargetReactivePower_L2:dict[str, Any]|None=None, EVSETargetReactivePower_L3:dict[str, Any]|None=None, EVSEPresentActivePower:dict[str, Any]|None=None, EVSEPresentActivePower_L2:dict[str, Any]|None=None, EVSEPresentActivePower_L3:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "EVSETargetActivePower": EVSETargetActivePower
    }
    if DepartureTime is not None:
        j["DepartureTime"] = DepartureTime
    if MinimumSOC is not None:
        j["MinimumSOC"] = MinimumSOC
    if TargetSOC is not None:
        j["TargetSOC"] = TargetSOC
    if AckMaxDelay is not None:
        j["AckMaxDelay"] = AckMaxDelay
    if EVSETargetActivePower_L2 is not None:
        j["EVSETargetActivePower_L2"] = EVSETargetActivePower_L2
    if EVSETargetActivePower_L3 is not None:
        j["EVSETargetActivePower_L3"] = EVSETargetActivePower_L3
    if EVSETargetReactivePower is not None:
        j["EVSETargetReactivePower"] = EVSETargetReactivePower
    if EVSETargetReactivePower_L2 is not None:
        j["EVSETargetReactivePower_L2"] = EVSETargetReactivePower_L2
    if EVSETargetReactivePower_L3 is not None:
        j["EVSETargetReactivePower_L3"] = EVSETargetReactivePower_L3
    if EVSEPresentActivePower is not None:
        j["EVSEPresentActivePower"] = EVSEPresentActivePower
    if EVSEPresentActivePower_L2 is not None:
        j["EVSEPresentActivePower_L2"] = EVSEPresentActivePower_L2
    if EVSEPresentActivePower_L3 is not None:
        j["EVSEPresentActivePower_L3"] = EVSEPresentActivePower_L3
    return j

def AC_ChargeLoopResType(Header:dict[str, Any], ResponseCode:responseCodeType, *, EVSEStatus:dict[str, Any]|None=None, MeterInfo:dict[str, Any]|None=None, Receipt:dict[str, Any]|None=None, EVSETargetFrequency:dict[str, Any]|None=None, BPT_Dynamic_AC_CLResControlMode:dict[str, Any]|None=None, BPT_Scheduled_AC_CLResControlMode:dict[str, Any]|None=None, CLResControlMode:dict[str, Any]|None=None, Dynamic_AC_CLResControlMode:dict[str, Any]|None=None, Scheduled_AC_CLResControlMode:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value
    }
    if EVSEStatus is not None:
        j["EVSEStatus"] = EVSEStatus
    if MeterInfo is not None:
        j["MeterInfo"] = MeterInfo
    if Receipt is not None:
        j["Receipt"] = Receipt
    if EVSETargetFrequency is not None:
        j["EVSETargetFrequency"] = EVSETargetFrequency
    if BPT_Dynamic_AC_CLResControlMode is not None:
        j["BPT_Dynamic_AC_CLResControlMode"] = BPT_Dynamic_AC_CLResControlMode
    if BPT_Scheduled_AC_CLResControlMode is not None:
        j["BPT_Scheduled_AC_CLResControlMode"] = BPT_Scheduled_AC_CLResControlMode
    if CLResControlMode is not None:
        j["CLResControlMode"] = CLResControlMode
    if Dynamic_AC_CLResControlMode is not None:
        j["Dynamic_AC_CLResControlMode"] = Dynamic_AC_CLResControlMode
    if Scheduled_AC_CLResControlMode is not None:
        j["Scheduled_AC_CLResControlMode"] = Scheduled_AC_CLResControlMode
    return j

def ManifestType(Reference:list[dict[str, Any]], *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Reference": {"arrayLen": len(Reference), "array": Reference}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def SignaturePropertiesType(SignatureProperty:dict[str, Any], *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SignatureProperty": SignatureProperty
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def exiFragment(*, AC_ChargeParameterDiscoveryRes:dict[str, Any]|None=None, SignedInfo:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if AC_ChargeParameterDiscoveryRes is not None:
        j["AC_ChargeParameterDiscoveryRes"] = AC_ChargeParameterDiscoveryRes
    if SignedInfo is not None:
        j["SignedInfo"] = SignedInfo
    return j

def xmldsigFragment(*, CanonicalizationMethod:dict[str, Any]|None=None, DSAKeyValue:dict[str, Any]|None=None, DigestMethod:dict[str, Any]|None=None, KeyInfo:dict[str, Any]|None=None, KeyValue:dict[str, Any]|None=None, Manifest:dict[str, Any]|None=None, Object:dict[str, Any]|None=None, PGPData:dict[str, Any]|None=None, RSAKeyValue:dict[str, Any]|None=None, Reference:dict[str, Any]|None=None, RetrievalMethod:dict[str, Any]|None=None, SPKIData:dict[str, Any]|None=None, Signature:dict[str, Any]|None=None, SignatureMethod:dict[str, Any]|None=None, SignatureProperties:dict[str, Any]|None=None, SignatureProperty:dict[str, Any]|None=None, SignatureValue:dict[str, Any]|None=None, SignedInfo:dict[str, Any]|None=None, Transform:dict[str, Any]|None=None, Transforms:dict[str, Any]|None=None, X509Data:dict[str, Any]|None=None, X509IssuerSerial:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if CanonicalizationMethod is not None:
        j["CanonicalizationMethod"] = CanonicalizationMethod
    if DSAKeyValue is not None:
        j["DSAKeyValue"] = DSAKeyValue
    if DigestMethod is not None:
        j["DigestMethod"] = DigestMethod
    if KeyInfo is not None:
        j["KeyInfo"] = KeyInfo
    if KeyValue is not None:
        j["KeyValue"] = KeyValue
    if Manifest is not None:
        j["Manifest"] = Manifest
    if Object is not None:
        j["Object"] = Object
    if PGPData is not None:
        j["PGPData"] = PGPData
    if RSAKeyValue is not None:
        j["RSAKeyValue"] = RSAKeyValue
    if Reference is not None:
        j["Reference"] = Reference
    if RetrievalMethod is not None:
        j["RetrievalMethod"] = RetrievalMethod
    if SPKIData is not None:
        j["SPKIData"] = SPKIData
    if Signature is not None:
        j["Signature"] = Signature
    if SignatureMethod is not None:
        j["SignatureMethod"] = SignatureMethod
    if SignatureProperties is not None:
        j["SignatureProperties"] = SignatureProperties
    if SignatureProperty is not None:
        j["SignatureProperty"] = SignatureProperty
    if SignatureValue is not None:
        j["SignatureValue"] = SignatureValue
    if SignedInfo is not None:
        j["SignedInfo"] = SignedInfo
    if Transform is not None:
        j["Transform"] = Transform
    if Transforms is not None:
        j["Transforms"] = Transforms
    if X509Data is not None:
        j["X509Data"] = X509Data
    if X509IssuerSerial is not None:
        j["X509IssuerSerial"] = X509IssuerSerial
    return j
