"""
Constructors and enum tables for the ISO 15118-20 WPT Namespace.

Auto-generated by tools/codegen/v2gjson_emitter.py. DO NOT EDIT.
"""

from enum import Enum
from typing import Any


# skipped iso20_wpt_generatedFunctionNumbersType: enum iso20_wpt_generatedFunctionNumbersType member 'iso20_wpt_CLReqControlMode' does not start with expected prefix 'iso20_wpt_generatedFunctionNumbersType_'

class WPT_FinePositioningMethodType(Enum):
    Manual = 0
    LF_TxEV = 1
    LF_TxPrimaryDevice = 2
    LPE = 3
    Proprietary = 4


class WPT_PairingMethodType(Enum):
    External_confirmation = 0
    LPE = 1
    LF_TxEV = 2
    LF_TxPrimaryDevice = 3
    Optical = 4
    Proprietary = 5


class WPT_AlignmentCheckMethodType(Enum):
    PowerCheck = 0
    LPE = 1
    Proprietary = 2


class evseNotificationType(Enum):
    Pause = 0
    ExitStandby = 1
    Terminate = 2
    ScheduleRenegotiation = 3
    ServiceRenegotiation = 4
    MeteringConfirmation = 5


class processingType(Enum):
    Finished = 0
    Ongoing = 1
    Ongoing_WaitingForCustomerInteraction = 2


class responseCodeType(Enum):
    OK = 0
    OK_CertificateExpiresSoon = 1
    OK_NewSessionEstablished = 2
    OK_OldSessionJoined = 3
    OK_PowerToleranceConfirmed = 4
    WARNING_AuthorizationSelectionInvalid = 5
    WARNING_CertificateExpired = 6
    WARNING_CertificateNotYetValid = 7
    WARNING_CertificateRevoked = 8
    WARNING_CertificateValidationError = 9
    WARNING_ChallengeInvalid = 10
    WARNING_EIMAuthorizationFailure = 11
    WARNING_eMSPUnknown = 12
    WARNING_EVPowerProfileViolation = 13
    WARNING_GeneralPnCAuthorizationError = 14
    WARNING_NoCertificateAvailable = 15
    WARNING_NoContractMatchingPCIDFound = 16
    WARNING_PowerToleranceNotConfirmed = 17
    WARNING_ScheduleRenegotiationFailed = 18
    WARNING_StandbyNotAllowed = 19
    WARNING_WPT = 20
    FAILED = 21
    FAILED_AssociationError = 22
    FAILED_ContactorError = 23
    FAILED_EVPowerProfileInvalid = 24
    FAILED_EVPowerProfileViolation = 25
    FAILED_MeteringSignatureNotValid = 26
    FAILED_NoEnergyTransferServiceSelected = 27
    FAILED_NoServiceRenegotiationSupported = 28
    FAILED_PauseNotAllowed = 29
    FAILED_PowerDeliveryNotApplied = 30
    FAILED_PowerToleranceNotConfirmed = 31
    FAILED_ScheduleRenegotiation = 32
    FAILED_ScheduleSelectionInvalid = 33
    FAILED_SequenceError = 34
    FAILED_ServiceIDInvalid = 35
    FAILED_ServiceSelectionInvalid = 36
    FAILED_SignatureError = 37
    FAILED_UnknownSession = 38
    FAILED_WrongChargeParameter = 39


class WPT_EVResultType(Enum):
    EVResultUnknown = 0
    EVResultSuccess = 1
    EVResultFailed = 2


class WPT_PowerClassType(Enum):
    MF_WPT1 = 0
    MF_WPT2 = 1
    MF_WPT3 = 2
    MF_WPT4 = 3


class WPT_EVPCChargeDiagnosticsType(Enum):
    EVPCNoIssue = 0
    EVPCTempOverheatDetected = 1
    EVPCPowerTransferAnomalyDetected = 2
    EVPCAnomalyDetected = 3


class WPT_SPCChargeDiagnosticsType(Enum):
    SPCNoIssue = 0
    SPCFODDetected = 1
    SPCLOPDetected = 2
    SPCTempOverheatDetected = 3
    SPCPowerTransferAnomalyDetected = 4
    SPCAnomalyDetected = 5


def TransformType(Algorithm:str, *, ANY:bytearray|None=None, XPath:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    if XPath is not None:
        j["XPath"] = {"characters": [ord(c) for c in XPath], "charactersLen": len(XPath)}
    return j

def TransformsType(Transform:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "Transform": Transform
    }
    return j

def DSAKeyValueType(Y:bytearray, *, P:bytearray|None=None, Q:bytearray|None=None, G:bytearray|None=None, J:bytearray|None=None, Seed:bytearray|None=None, PgenCounter:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Y": {"bytes": list(Y), "bytesLen": len(Y)}
    }
    if P is not None:
        j["P"] = {"bytes": list(P), "bytesLen": len(P)}
    if Q is not None:
        j["Q"] = {"bytes": list(Q), "bytesLen": len(Q)}
    if G is not None:
        j["G"] = {"bytes": list(G), "bytesLen": len(G)}
    if J is not None:
        j["J"] = {"bytes": list(J), "bytesLen": len(J)}
    if Seed is not None:
        j["Seed"] = {"bytes": list(Seed), "bytesLen": len(Seed)}
    if PgenCounter is not None:
        j["PgenCounter"] = {"bytes": list(PgenCounter), "bytesLen": len(PgenCounter)}
    return j

def X509IssuerSerialType(X509IssuerName:str, X509SerialNumber:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "X509IssuerName": {"characters": [ord(c) for c in X509IssuerName], "charactersLen": len(X509IssuerName)},
        "X509SerialNumber": X509SerialNumber
    }
    return j

def DigestMethodType(Algorithm:str, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def RSAKeyValueType(Modulus:bytearray, Exponent:bytearray)->dict[str, Any]:
    j:dict[str, Any] = {
        "Modulus": {"bytes": list(Modulus), "bytesLen": len(Modulus)},
        "Exponent": {"bytes": list(Exponent), "bytesLen": len(Exponent)}
    }
    return j

def CanonicalizationMethodType(Algorithm:str, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def WPT_TxRxPulseOrderType(IndexNumber:int, TxRxIdentifier:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "IndexNumber": IndexNumber,
        "TxRxIdentifier": TxRxIdentifier
    }
    return j

def SignatureMethodType(Algorithm:str, *, HMACOutputLength:dict[str, Any]|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Algorithm": {"characters": [ord(c) for c in Algorithm], "charactersLen": len(Algorithm)}
    }
    if HMACOutputLength is not None:
        j["HMACOutputLength"] = HMACOutputLength
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def KeyValueType(*, DSAKeyValue:dict[str, Any]|None=None, RSAKeyValue:dict[str, Any]|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if DSAKeyValue is not None:
        j["DSAKeyValue"] = DSAKeyValue
    if RSAKeyValue is not None:
        j["RSAKeyValue"] = RSAKeyValue
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def WPT_CoordinateXYZType(Coord_X:int, Coord_Y:int, Coord_Z:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Coord_X": Coord_X,
        "Coord_Y": Coord_Y,
        "Coord_Z": Coord_Z
    }
    return j

def ReferenceType(DigestMethod:dict[str, Any], DigestValue:bytearray, *, Id:str|None=None, Type:str|None=None, URI:str|None=None, Transforms:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "DigestMethod": DigestMethod,
        "DigestValue": {"bytes": list(DigestValue), "bytesLen": len(DigestValue)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if Type is not None:
        j["Type"] = {"characters": [ord(c) for c in Type], "charactersLen": len(Type)}
    if URI is not None:
        j["URI"] = {"characters": [ord(c) for c in URI], "charactersLen": len(URI)}
    if Transforms is not None:
        j["Transforms"] = Transforms
    return j

def RetrievalMethodType(*, Type:str|None=None, URI:str|None=None, Transforms:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Type is not None:
        j["Type"] = {"characters": [ord(c) for c in Type], "charactersLen": len(Type)}
    if URI is not None:
        j["URI"] = {"characters": [ord(c) for c in URI], "charactersLen": len(URI)}
    if Transforms is not None:
        j["Transforms"] = Transforms
    return j

def X509DataType(*, X509IssuerSerial:dict[str, Any]|None=None, X509SKI:bytearray|None=None, X509SubjectName:str|None=None, X509Certificate:bytearray|None=None, X509CRL:bytearray|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if X509IssuerSerial is not None:
        j["X509IssuerSerial"] = X509IssuerSerial
    if X509SKI is not None:
        j["X509SKI"] = {"bytes": list(X509SKI), "bytesLen": len(X509SKI)}
    if X509SubjectName is not None:
        j["X509SubjectName"] = {"characters": [ord(c) for c in X509SubjectName], "charactersLen": len(X509SubjectName)}
    if X509Certificate is not None:
        j["X509Certificate"] = {"bytes": list(X509Certificate), "bytesLen": len(X509Certificate)}
    if X509CRL is not None:
        j["X509CRL"] = {"bytes": list(X509CRL), "bytesLen": len(X509CRL)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def PGPDataType(*, choice_1:int|None=None, choice_2:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if choice_1 is not None:
        j["choice_1"] = choice_1
    if choice_2 is not None:
        j["choice_2"] = choice_2
    return j

def SPKIDataType(SPKISexp:bytearray, *, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SPKISexp": {"bytes": list(SPKISexp), "bytesLen": len(SPKISexp)}
    }
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def SignedInfoType(CanonicalizationMethod:dict[str, Any], SignatureMethod:dict[str, Any], Reference:list[dict[str, Any]], *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "CanonicalizationMethod": CanonicalizationMethod,
        "SignatureMethod": SignatureMethod,
        "Reference": {"arrayLen": len(Reference), "array": Reference}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def SignatureValueType(CONTENT:bytearray, *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "CONTENT": {"bytes": list(CONTENT), "bytesLen": len(CONTENT)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def RationalNumberType(Exponent:int, Value:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "Exponent": Exponent,
        "Value": Value
    }
    return j

def WPT_LF_RxRSSIType(TxIdentifier:int, RSSI:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "TxIdentifier": TxIdentifier,
        "RSSI": RSSI
    }
    return j

def WPT_LF_RxRSSIListType(RSSIDataList:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "RSSIDataList": RSSIDataList
    }
    return j

def WPT_LF_TxDataType(TxIdentifier:int, EIRP:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "TxIdentifier": TxIdentifier,
        "EIRP": EIRP
    }
    return j

def WPT_LF_RxDataType(RxIdentifier:int, RSSIData:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "RxIdentifier": RxIdentifier,
        "RSSIData": RSSIData
    }
    return j

def WPT_LF_TxDataListType(WPT_LF_TxDataList:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "WPT_LF_TxDataList": WPT_LF_TxDataList
    }
    return j

def KeyInfoType(*, Id:str|None=None, KeyName:str|None=None, KeyValue:dict[str, Any]|None=None, RetrievalMethod:dict[str, Any]|None=None, X509Data:dict[str, Any]|None=None, PGPData:dict[str, Any]|None=None, SPKIData:dict[str, Any]|None=None, MgmtData:str|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if KeyName is not None:
        j["KeyName"] = {"characters": [ord(c) for c in KeyName], "charactersLen": len(KeyName)}
    if KeyValue is not None:
        j["KeyValue"] = KeyValue
    if RetrievalMethod is not None:
        j["RetrievalMethod"] = RetrievalMethod
    if X509Data is not None:
        j["X509Data"] = X509Data
    if PGPData is not None:
        j["PGPData"] = PGPData
    if SPKIData is not None:
        j["SPKIData"] = SPKIData
    if MgmtData is not None:
        j["MgmtData"] = {"characters": [ord(c) for c in MgmtData], "charactersLen": len(MgmtData)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def WPT_TxRxSpecDataType(TxRxIdentifier:int, TxRxPosition:dict[str, Any], TxRxOrientation:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "TxRxIdentifier": TxRxIdentifier,
        "TxRxPosition": TxRxPosition,
        "TxRxOrientation": TxRxOrientation
    }
    return j

def WPT_LF_RxDataListType(WPT_LF_RxDataList:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "WPT_LF_RxDataList": WPT_LF_RxDataList
    }
    return j

def ObjectType(*, Encoding:str|None=None, Id:str|None=None, MimeType:str|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if Encoding is not None:
        j["Encoding"] = {"characters": [ord(c) for c in Encoding], "charactersLen": len(Encoding)}
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if MimeType is not None:
        j["MimeType"] = {"characters": [ord(c) for c in MimeType], "charactersLen": len(MimeType)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def WPT_TxRxPackageSpecDataType(PulseSequenceOrder:list[dict[str, Any]], PulseSeparationTime:int, PulseDuration:int, PackageSeparationTime:int)->dict[str, Any]:
    j:dict[str, Any] = {
        "PulseSequenceOrder": {"arrayLen": len(PulseSequenceOrder), "array": PulseSequenceOrder},
        "PulseSeparationTime": PulseSeparationTime,
        "PulseDuration": PulseDuration,
        "PackageSeparationTime": PackageSeparationTime
    }
    return j

def WPT_LF_TransmitterDataType(NumberOfTransmitters:int, SignalFrequency:dict[str, Any], TxSpecData:list[dict[str, Any]], *, TxPackageSpecData:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "NumberOfTransmitters": NumberOfTransmitters,
        "SignalFrequency": SignalFrequency,
        "TxSpecData": {"arrayLen": len(TxSpecData), "array": TxSpecData}
    }
    if TxPackageSpecData is not None:
        j["TxPackageSpecData"] = TxPackageSpecData
    return j

def AlternativeSECCType(*, SSID:str|None=None, BSSID:str|None=None, IPAddress:str|None=None, Port:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if SSID is not None:
        j["SSID"] = {"characters": [ord(c) for c in SSID], "charactersLen": len(SSID)}
    if BSSID is not None:
        j["BSSID"] = {"characters": [ord(c) for c in BSSID], "charactersLen": len(BSSID)}
    if IPAddress is not None:
        j["IPAddress"] = {"characters": [ord(c) for c in IPAddress], "charactersLen": len(IPAddress)}
    if Port is not None:
        j["Port"] = Port
    return j

def WPT_LF_ReceiverDataType(NumberOfReceivers:int, RxSpecData:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "NumberOfReceivers": NumberOfReceivers,
        "RxSpecData": {"arrayLen": len(RxSpecData), "array": RxSpecData}
    }
    return j

def WPT_LF_DataPackageType(PackageIndex:int, *, LF_TxData:dict[str, Any]|None=None, LF_RxData:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "PackageIndex": PackageIndex
    }
    if LF_TxData is not None:
        j["LF_TxData"] = LF_TxData
    if LF_RxData is not None:
        j["LF_RxData"] = LF_RxData
    return j

def DetailedCostType(Amount:dict[str, Any], CostPerUnit:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "Amount": Amount,
        "CostPerUnit": CostPerUnit
    }
    return j

def SignatureType(SignedInfo:dict[str, Any], SignatureValue:dict[str, Any], *, Id:str|None=None, KeyInfo:dict[str, Any]|None=None, Object:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SignedInfo": SignedInfo,
        "SignatureValue": SignatureValue
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if KeyInfo is not None:
        j["KeyInfo"] = KeyInfo
    if Object is not None:
        j["Object"] = Object
    return j

def DetailedTaxType(TaxRuleID:int, Amount:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "TaxRuleID": TaxRuleID,
        "Amount": Amount
    }
    return j

def MessageHeaderType(SessionID:bytearray, TimeStamp:int, *, Signature:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SessionID": {"bytes": list(SessionID), "bytesLen": len(SessionID)},
        "TimeStamp": TimeStamp
    }
    if Signature is not None:
        j["Signature"] = Signature
    return j

def SignaturePropertyType(Target:str, *, Id:str|None=None, ANY:bytearray|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Target": {"characters": [ord(c) for c in Target], "charactersLen": len(Target)}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    if ANY is not None:
        j["ANY"] = {"bytes": list(ANY), "bytesLen": len(ANY)}
    return j

def DisplayParametersType(*, PresentSOC:int|None=None, MinimumSOC:int|None=None, TargetSOC:int|None=None, MaximumSOC:int|None=None, RemainingTimeToMinimumSOC:int|None=None, RemainingTimeToTargetSOC:int|None=None, RemainingTimeToMaximumSOC:int|None=None, ChargingComplete:int|None=None, BatteryEnergyCapacity:dict[str, Any]|None=None, InletHot:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if PresentSOC is not None:
        j["PresentSOC"] = PresentSOC
    if MinimumSOC is not None:
        j["MinimumSOC"] = MinimumSOC
    if TargetSOC is not None:
        j["TargetSOC"] = TargetSOC
    if MaximumSOC is not None:
        j["MaximumSOC"] = MaximumSOC
    if RemainingTimeToMinimumSOC is not None:
        j["RemainingTimeToMinimumSOC"] = RemainingTimeToMinimumSOC
    if RemainingTimeToTargetSOC is not None:
        j["RemainingTimeToTargetSOC"] = RemainingTimeToTargetSOC
    if RemainingTimeToMaximumSOC is not None:
        j["RemainingTimeToMaximumSOC"] = RemainingTimeToMaximumSOC
    if ChargingComplete is not None:
        j["ChargingComplete"] = ChargingComplete
    if BatteryEnergyCapacity is not None:
        j["BatteryEnergyCapacity"] = BatteryEnergyCapacity
    if InletHot is not None:
        j["InletHot"] = InletHot
    return j

def WPT_FinePositioningMethodListType(WPT_FinePositioningMethod:list[WPT_FinePositioningMethodType])->dict[str, Any]:
    j:dict[str, Any] = {
        "WPT_FinePositioningMethod": {"arrayLen": len(WPT_FinePositioningMethod), "array": [_v.value for _v in WPT_FinePositioningMethod]}
    }
    return j

def EVSEStatusType(NotificationMaxDelay:int, EVSENotification:evseNotificationType)->dict[str, Any]:
    j:dict[str, Any] = {
        "NotificationMaxDelay": NotificationMaxDelay,
        "EVSENotification": EVSENotification.value
    }
    return j

def WPT_PairingMethodListType(WPT_PairingMethod:list[WPT_PairingMethodType])->dict[str, Any]:
    j:dict[str, Any] = {
        "WPT_PairingMethod": {"arrayLen": len(WPT_PairingMethod), "array": [_v.value for _v in WPT_PairingMethod]}
    }
    return j

def MeterInfoType(MeterID:str, ChargedEnergyReadingWh:int, *, BPT_DischargedEnergyReadingWh:int|None=None, CapacitiveEnergyReadingVARh:int|None=None, BPT_InductiveEnergyReadingVARh:int|None=None, MeterSignature:bytearray|None=None, MeterStatus:int|None=None, MeterTimestamp:int|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "MeterID": {"characters": [ord(c) for c in MeterID], "charactersLen": len(MeterID)},
        "ChargedEnergyReadingWh": ChargedEnergyReadingWh
    }
    if BPT_DischargedEnergyReadingWh is not None:
        j["BPT_DischargedEnergyReadingWh"] = BPT_DischargedEnergyReadingWh
    if CapacitiveEnergyReadingVARh is not None:
        j["CapacitiveEnergyReadingVARh"] = CapacitiveEnergyReadingVARh
    if BPT_InductiveEnergyReadingVARh is not None:
        j["BPT_InductiveEnergyReadingVARh"] = BPT_InductiveEnergyReadingVARh
    if MeterSignature is not None:
        j["MeterSignature"] = {"bytes": list(MeterSignature), "bytesLen": len(MeterSignature)}
    if MeterStatus is not None:
        j["MeterStatus"] = MeterStatus
    if MeterTimestamp is not None:
        j["MeterTimestamp"] = MeterTimestamp
    return j

def WPT_AlignmentCheckMethodListType(WPT_AlignmentCheckMethod:list[WPT_AlignmentCheckMethodType])->dict[str, Any]:
    j:dict[str, Any] = {
        "WPT_AlignmentCheckMethod": {"arrayLen": len(WPT_AlignmentCheckMethod), "array": [_v.value for _v in WPT_AlignmentCheckMethod]}
    }
    return j

def WPT_LF_DataPackageListType(NumPackages:int, WPT_LF_DataPackage:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "NumPackages": NumPackages,
        "WPT_LF_DataPackage": WPT_LF_DataPackage
    }
    return j

def AlternativeSECCListType(AlternativeSECC:list[dict[str, Any]])->dict[str, Any]:
    j:dict[str, Any] = {
        "AlternativeSECC": {"arrayLen": len(AlternativeSECC), "array": AlternativeSECC}
    }
    return j

def ReceiptType(TimeAnchor:int, TaxCosts:list[dict[str, Any]], *, EnergyCosts:dict[str, Any]|None=None, OccupancyCosts:dict[str, Any]|None=None, AdditionalServicesCosts:dict[str, Any]|None=None, OverstayCosts:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "TimeAnchor": TimeAnchor,
        "TaxCosts": {"arrayLen": len(TaxCosts), "array": TaxCosts}
    }
    if EnergyCosts is not None:
        j["EnergyCosts"] = EnergyCosts
    if OccupancyCosts is not None:
        j["OccupancyCosts"] = OccupancyCosts
    if AdditionalServicesCosts is not None:
        j["AdditionalServicesCosts"] = AdditionalServicesCosts
    if OverstayCosts is not None:
        j["OverstayCosts"] = OverstayCosts
    return j

def WPT_LF_SystemSetupDataType(*, LF_TransmitterSetupData:dict[str, Any]|None=None, LF_ReceiverSetupData:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {}
    if LF_TransmitterSetupData is not None:
        j["LF_TransmitterSetupData"] = LF_TransmitterSetupData
    if LF_ReceiverSetupData is not None:
        j["LF_ReceiverSetupData"] = LF_ReceiverSetupData
    return j

def WPT_EVPCPowerControlParameterType(EVPCCoilCurrentRequest:dict[str, Any], EVPCCoilCurrentInformation:dict[str, Any], EVPCCurrentOutputInformation:dict[str, Any], EVPCVoltageOutputInformation:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "EVPCCoilCurrentRequest": EVPCCoilCurrentRequest,
        "EVPCCoilCurrentInformation": EVPCCoilCurrentInformation,
        "EVPCCurrentOutputInformation": EVPCCurrentOutputInformation,
        "EVPCVoltageOutputInformation": EVPCVoltageOutputInformation
    }
    return j

def WPT_SPCPowerControlParameterType(SPCPrimaryDeviceCoilCurrentInformation:dict[str, Any])->dict[str, Any]:
    j:dict[str, Any] = {
        "SPCPrimaryDeviceCoilCurrentInformation": SPCPrimaryDeviceCoilCurrentInformation
    }
    return j

def WPT_FinePositioningSetupReqType(Header:dict[str, Any], EVProcessing:processingType, EVDeviceFinePositioningMethodList:dict[str, Any], EVDevicePairingMethodList:dict[str, Any], EVDeviceAlignmentCheckMethodList:dict[str, Any], NaturalOffset:int, *, VendorSpecificDataContainer:list[bytearray]|None=None, LF_SystemSetupData:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "EVProcessing": EVProcessing.value,
        "EVDeviceFinePositioningMethodList": EVDeviceFinePositioningMethodList,
        "EVDevicePairingMethodList": EVDevicePairingMethodList,
        "EVDeviceAlignmentCheckMethodList": EVDeviceAlignmentCheckMethodList,
        "NaturalOffset": NaturalOffset
    }
    if VendorSpecificDataContainer is not None:
        j["VendorSpecificDataContainer"] = {"arrayLen": len(VendorSpecificDataContainer), "array": [{"bytes": list(_b), "bytesLen": len(_b)} for _b in VendorSpecificDataContainer]}
    if LF_SystemSetupData is not None:
        j["LF_SystemSetupData"] = LF_SystemSetupData
    return j

def WPT_FinePositioningSetupResType(Header:dict[str, Any], ResponseCode:responseCodeType, PrimaryDeviceFinePositioningMethodList:dict[str, Any], PrimaryDevicePairingMethodList:dict[str, Any], PrimaryDeviceAlignmentCheckMethodList:dict[str, Any], NaturalOffset:int, *, VendorSpecificDataContainer:list[bytearray]|None=None, LF_SystemSetupData:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "PrimaryDeviceFinePositioningMethodList": PrimaryDeviceFinePositioningMethodList,
        "PrimaryDevicePairingMethodList": PrimaryDevicePairingMethodList,
        "PrimaryDeviceAlignmentCheckMethodList": PrimaryDeviceAlignmentCheckMethodList,
        "NaturalOffset": NaturalOffset
    }
    if VendorSpecificDataContainer is not None:
        j["VendorSpecificDataContainer"] = {"arrayLen": len(VendorSpecificDataContainer), "array": [{"bytes": list(_b), "bytesLen": len(_b)} for _b in VendorSpecificDataContainer]}
    if LF_SystemSetupData is not None:
        j["LF_SystemSetupData"] = LF_SystemSetupData
    return j

def WPT_FinePositioningReqType(Header:dict[str, Any], EVProcessing:processingType, EVResultCode:WPT_EVResultType, *, VendorSpecificDataContainer:list[bytearray]|None=None, WPT_LF_DataPackageList:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "EVProcessing": EVProcessing.value,
        "EVResultCode": EVResultCode.value
    }
    if VendorSpecificDataContainer is not None:
        j["VendorSpecificDataContainer"] = {"arrayLen": len(VendorSpecificDataContainer), "array": [{"bytes": list(_b), "bytesLen": len(_b)} for _b in VendorSpecificDataContainer]}
    if WPT_LF_DataPackageList is not None:
        j["WPT_LF_DataPackageList"] = WPT_LF_DataPackageList
    return j

def WPT_FinePositioningResType(Header:dict[str, Any], ResponseCode:responseCodeType, EVSEProcessing:processingType, *, VendorSpecificDataContainer:list[bytearray]|None=None, WPT_LF_DataPackageList:dict[str, Any]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "EVSEProcessing": EVSEProcessing.value
    }
    if VendorSpecificDataContainer is not None:
        j["VendorSpecificDataContainer"] = {"arrayLen": len(VendorSpecificDataContainer), "array": [{"bytes": list(_b), "bytesLen": len(_b)} for _b in VendorSpecificDataContainer]}
    if WPT_LF_DataPackageList is not None:
        j["WPT_LF_DataPackageList"] = WPT_LF_DataPackageList
    return j

def WPT_PairingReqType(Header:dict[str, Any], EVProcessing:processingType, EVResultCode:WPT_EVResultType, *, ObservedIDCode:int|None=None, VendorSpecificDataContainer:list[bytearray]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "EVProcessing": EVProcessing.value,
        "EVResultCode": EVResultCode.value
    }
    if ObservedIDCode is not None:
        j["ObservedIDCode"] = ObservedIDCode
    if VendorSpecificDataContainer is not None:
        j["VendorSpecificDataContainer"] = {"arrayLen": len(VendorSpecificDataContainer), "array": [{"bytes": list(_b), "bytesLen": len(_b)} for _b in VendorSpecificDataContainer]}
    return j

def WPT_PairingResType(Header:dict[str, Any], ResponseCode:responseCodeType, EVSEProcessing:processingType, *, ObservedIDCode:int|None=None, AlternativeSECCList:dict[str, Any]|None=None, VendorSpecificDataContainer:list[bytearray]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "EVSEProcessing": EVSEProcessing.value
    }
    if ObservedIDCode is not None:
        j["ObservedIDCode"] = ObservedIDCode
    if AlternativeSECCList is not None:
        j["AlternativeSECCList"] = AlternativeSECCList
    if VendorSpecificDataContainer is not None:
        j["VendorSpecificDataContainer"] = {"arrayLen": len(VendorSpecificDataContainer), "array": [{"bytes": list(_b), "bytesLen": len(_b)} for _b in VendorSpecificDataContainer]}
    return j

def WPT_ChargeParameterDiscoveryReqType(Header:dict[str, Any], EVPCMaxReceivablePower:dict[str, Any], SDMaxGroundClearence:int, SDMinGroundClearence:int, EVPCNaturalFrequency:dict[str, Any], EVPCDeviceLocalControl:int, *, VendorSpecificDataContainer:list[bytearray]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "EVPCMaxReceivablePower": EVPCMaxReceivablePower,
        "SDMaxGroundClearence": SDMaxGroundClearence,
        "SDMinGroundClearence": SDMinGroundClearence,
        "EVPCNaturalFrequency": EVPCNaturalFrequency,
        "EVPCDeviceLocalControl": EVPCDeviceLocalControl
    }
    if VendorSpecificDataContainer is not None:
        j["VendorSpecificDataContainer"] = {"arrayLen": len(VendorSpecificDataContainer), "array": [{"bytes": list(_b), "bytesLen": len(_b)} for _b in VendorSpecificDataContainer]}
    return j

def WPT_ChargeParameterDiscoveryResType(Header:dict[str, Any], ResponseCode:responseCodeType, PDInputPowerClass:WPT_PowerClassType, SDMinOutputPower:dict[str, Any], SDMaxOutputPower:dict[str, Any], SDMaxGroundClearanceSupport:int, SDMinGroundClearanceSupport:int, PDMinCoilCurrent:dict[str, Any], PDMaxCoilCurrent:dict[str, Any], *, SDManufacturerSpecificDataContainer:list[bytearray]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "PDInputPowerClass": PDInputPowerClass.value,
        "SDMinOutputPower": SDMinOutputPower,
        "SDMaxOutputPower": SDMaxOutputPower,
        "SDMaxGroundClearanceSupport": SDMaxGroundClearanceSupport,
        "SDMinGroundClearanceSupport": SDMinGroundClearanceSupport,
        "PDMinCoilCurrent": PDMinCoilCurrent,
        "PDMaxCoilCurrent": PDMaxCoilCurrent
    }
    if SDManufacturerSpecificDataContainer is not None:
        j["SDManufacturerSpecificDataContainer"] = {"arrayLen": len(SDManufacturerSpecificDataContainer), "array": [{"bytes": list(_b), "bytesLen": len(_b)} for _b in SDManufacturerSpecificDataContainer]}
    return j

def WPT_AlignmentCheckReqType(Header:dict[str, Any], EVProcessing:processingType, EVResultCode:WPT_EVResultType, *, TargetCoilCurrent:dict[str, Any]|None=None, VendorSpecificDataContainer:list[bytearray]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "EVProcessing": EVProcessing.value,
        "EVResultCode": EVResultCode.value
    }
    if TargetCoilCurrent is not None:
        j["TargetCoilCurrent"] = TargetCoilCurrent
    if VendorSpecificDataContainer is not None:
        j["VendorSpecificDataContainer"] = {"arrayLen": len(VendorSpecificDataContainer), "array": [{"bytes": list(_b), "bytesLen": len(_b)} for _b in VendorSpecificDataContainer]}
    return j

def WPT_AlignmentCheckResType(Header:dict[str, Any], ResponseCode:responseCodeType, EVSEProcessing:processingType, *, PowerTransmitted:dict[str, Any]|None=None, SupplyDeviceCurrent:dict[str, Any]|None=None, VendorSpecificDataContainer:list[bytearray]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "EVSEProcessing": EVSEProcessing.value
    }
    if PowerTransmitted is not None:
        j["PowerTransmitted"] = PowerTransmitted
    if SupplyDeviceCurrent is not None:
        j["SupplyDeviceCurrent"] = SupplyDeviceCurrent
    if VendorSpecificDataContainer is not None:
        j["VendorSpecificDataContainer"] = {"arrayLen": len(VendorSpecificDataContainer), "array": [{"bytes": list(_b), "bytesLen": len(_b)} for _b in VendorSpecificDataContainer]}
    return j

def WPT_ChargeLoopReqType(Header:dict[str, Any], MeterInfoRequested:int, EVPCPowerRequest:dict[str, Any], EVPCPowerOutput:dict[str, Any], EVPCChargeDiagnostics:WPT_EVPCChargeDiagnosticsType, *, DisplayParameters:dict[str, Any]|None=None, EVPCOperatingFrequency:dict[str, Any]|None=None, EVPCPowerControlParameter:dict[str, Any]|None=None, ManufacturerSpecificDataContainer:list[bytearray]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "MeterInfoRequested": MeterInfoRequested,
        "EVPCPowerRequest": EVPCPowerRequest,
        "EVPCPowerOutput": EVPCPowerOutput,
        "EVPCChargeDiagnostics": EVPCChargeDiagnostics.value
    }
    if DisplayParameters is not None:
        j["DisplayParameters"] = DisplayParameters
    if EVPCOperatingFrequency is not None:
        j["EVPCOperatingFrequency"] = EVPCOperatingFrequency
    if EVPCPowerControlParameter is not None:
        j["EVPCPowerControlParameter"] = EVPCPowerControlParameter
    if ManufacturerSpecificDataContainer is not None:
        j["ManufacturerSpecificDataContainer"] = {"arrayLen": len(ManufacturerSpecificDataContainer), "array": [{"bytes": list(_b), "bytesLen": len(_b)} for _b in ManufacturerSpecificDataContainer]}
    return j

def WPT_ChargeLoopResType(Header:dict[str, Any], ResponseCode:responseCodeType, EVPCPowerRequest:dict[str, Any], SPCMaxOutputPowerLimit:dict[str, Any], SPCMinOutputPowerLimit:dict[str, Any], SPCChargeDiagnostics:WPT_SPCChargeDiagnosticsType, *, EVSEStatus:dict[str, Any]|None=None, MeterInfo:dict[str, Any]|None=None, Receipt:dict[str, Any]|None=None, SDPowerInput:dict[str, Any]|None=None, SPCOperatingFrequency:dict[str, Any]|None=None, SPCPowerControlParameter:dict[str, Any]|None=None, ManufacturerSpecificDataContainer:list[bytearray]|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Header": Header,
        "ResponseCode": ResponseCode.value,
        "EVPCPowerRequest": EVPCPowerRequest,
        "SPCMaxOutputPowerLimit": SPCMaxOutputPowerLimit,
        "SPCMinOutputPowerLimit": SPCMinOutputPowerLimit,
        "SPCChargeDiagnostics": SPCChargeDiagnostics.value
    }
    if EVSEStatus is not None:
        j["EVSEStatus"] = EVSEStatus
    if MeterInfo is not None:
        j["MeterInfo"] = MeterInfo
    if Receipt is not None:
        j["Receipt"] = Receipt
    if SDPowerInput is not None:
        j["SDPowerInput"] = SDPowerInput
    if SPCOperatingFrequency is not None:
        j["SPCOperatingFrequency"] = SPCOperatingFrequency
    if SPCPowerControlParameter is not None:
        j["SPCPowerControlParameter"] = SPCPowerControlParameter
    if ManufacturerSpecificDataContainer is not None:
        j["ManufacturerSpecificDataContainer"] = {"arrayLen": len(ManufacturerSpecificDataContainer), "array": [{"bytes": list(_b), "bytesLen": len(_b)} for _b in ManufacturerSpecificDataContainer]}
    return j

def CLReqControlModeType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def CLResControlModeType()->dict[str, Any]:
    j:dict[str, Any] = {}
    return j

def ManifestType(Reference:list[dict[str, Any]], *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "Reference": {"arrayLen": len(Reference), "array": Reference}
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j

def SignaturePropertiesType(SignatureProperty:dict[str, Any], *, Id:str|None=None)->dict[str, Any]:
    j:dict[str, Any] = {
        "SignatureProperty": SignatureProperty
    }
    if Id is not None:
        j["Id"] = {"characters": [ord(c) for c in Id], "charactersLen": len(Id)}
    return j
