"""CLI: parse a libcbv2g `*_Datatypes.h` header and emit C++ Marshaler bodies."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

from .parser import parse_header
from .emitter import emit_get_json, emit_get_doc


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--header", required=True, type=Path)
    p.add_argument("--out", required=True, type=Path)
    args = p.parse_args(argv)

    specs = parse_header(args.header.read_text())

    chunks: list[str] = [
        "// Auto-generated by tools/codegen. DO NOT EDIT.\n",
        f"// Source: {args.header.name}\n\n",
    ]
    for spec in specs:
        chunks.append(emit_get_json(spec))
        chunks.append("\n")
        chunks.append(emit_get_doc(spec))
        chunks.append("\n")

    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text("".join(chunks))
    return 0


if __name__ == "__main__":
    sys.exit(main())
