"""Emit `<Namespace>Processor_cli.generated.cpp` — a per-Namespace `main()`
that drives the matching Processor object via cxxopts.

Per ADR-0014 each CLI binary has six modes on Namespaces whose schema defines
Fragment / XmldsigFragment roots, and two modes (Document only) on SAP and DIN
whose schemas don't. The set of registered flags — and therefore the body of
`--help` — is fixed at codegen time from the same root-type detection that
drives `processor_emitter.py`. Unsupported flags are rejected with a
Namespace-specific error before cxxopts parsing so consumers don't see the
generic "unrecognised option" message.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

# Reuse the per-Namespace policy table + root detection from the Processor
# emitter so the two CLI sources for a given Namespace stay in lock-step.
from .processor_emitter import NAMESPACES, NamespacePolicy, detect_root_types


# Output filename per Namespace. Mirrors processor_hpp_filename's stem.
def _cli_cpp_filename(policy: NamespacePolicy) -> str:
    stem = policy.processor_hpp_filename.removesuffix(".generated.hpp")
    return f"{stem}_cli.generated.cpp"


_PROGRAM_NAME = "./EXIProcessor --[encode/decode]='STRING_OPTIONAL' -i FILE_INPUT -o FILE_OUTPUT"
_PROGRAM_DESC = (
    "Encode and decode V2G EXI Documents for one Namespace.\\n"
    "If no argument is given for input/output, defaults to stdin/stdout.\\n"
    "Use double quotes (\\\") and lower case true/false."
)


def emit_cli_cpp(policy: NamespacePolicy, root_types: set[str]) -> str:
    has_fragment = "exiFragment" in root_types
    has_xmldsig = "xmldsigFragment" in root_types

    # Unsupported-root gates: any flag in this list that appears in argv on a
    # binary that doesn't support its root emits the Namespace-specific error.
    gates: list[tuple[str, str]] = []
    if not has_fragment:
        gates.append(("--encode-fragment", "Fragment"))
        gates.append(("--decode-fragment", "Fragment"))
    if not has_xmldsig:
        gates.append(("--encode-xmldsig", "XmldsigFragment"))
        gates.append(("--decode-xmldsig", "XmldsigFragment"))

    parts: list[str] = []
    parts.append("// Auto-generated by tools/codegen/processor_cli_emitter.py. DO NOT EDIT.\n")
    parts.append(f"// Namespace: {policy.namespace}\n")
    parts.append("\n")
    parts.append("#include <cstddef>\n")
    parts.append("#include <cstdint>\n")
    parts.append("#include <iostream>\n")
    parts.append("#include <string>\n")
    parts.append("\n")
    parts.append("#include <cxxopts.hpp>\n")
    parts.append("\n")
    parts.append(f'#include "{policy.processor_hpp_filename}"\n')
    parts.append("#include <expy_cli_helpers.hpp>\n")
    parts.append("\n")
    parts.append("namespace {\n")
    parts.append(f'constexpr const char* NAMESPACE_NAME = "{policy.namespace}";\n')
    parts.append("}  // namespace\n")
    parts.append("\n")

    parts.append("int main(int argc, char* argv[]) {\n")

    if gates:
        parts.append(
            "    // Pre-scan argv for root flags this binary doesn't support so we\n"
            "    // emit a Namespace-specific error rather than cxxopts' generic\n"
            "    // \"unrecognised option\" parse failure (ADR-0014).\n"
        )
        parts.append("    static const struct { const char* flag; } UNSUPPORTED[] = {\n")
        for flag, _root in gates:
            parts.append(f'        {{"{flag}"}},\n')
        parts.append("    };\n")
        parts.append("    for (int i = 1; i < argc; ++i) {\n")
        parts.append("        std::string a = argv[i];\n")
        parts.append("        for (const auto& g : UNSUPPORTED) {\n")
        parts.append("            std::string f = g.flag;\n")
        parts.append("            if (a == f || a.rfind(f + \"=\", 0) == 0) {\n")
        parts.append(
            "                std::cerr << \"Error: \" << f\n"
            "                          << \" is not supported for Namespace=\"\n"
            "                          << NAMESPACE_NAME << std::endl;\n"
        )
        parts.append("                return 1;\n")
        parts.append("            }\n")
        parts.append("        }\n")
        parts.append("    }\n")
        parts.append("\n")

    parts.append("    cxxopts::Options options(\n")
    parts.append(f'        "{_PROGRAM_NAME}",\n')
    parts.append(f'        "{_PROGRAM_DESC}"\n')
    parts.append("    );\n")
    parts.append("    options.add_options()\n")
    parts.append('        ("h,help", "Show help")\n')
    parts.append(
        '        ("e,encode", "Encode EXI Document from JSON to EXI bytes",\n'
        '            cxxopts::value<std::string>()->implicit_value("cmd"))\n'
    )
    parts.append(
        '        ("d,decode", "Decode EXI Document from EXI bytes to JSON",\n'
        '            cxxopts::value<std::string>()->implicit_value("cmd"))'
    )
    if has_fragment:
        parts.append("\n")
        parts.append(
            '        ("encode-fragment", "Encode EXI Fragment from JSON to EXI bytes",\n'
            '            cxxopts::value<std::string>()->implicit_value("cmd"))\n'
        )
        parts.append(
            '        ("decode-fragment", "Decode EXI Fragment from EXI bytes to JSON",\n'
            '            cxxopts::value<std::string>()->implicit_value("cmd"))'
        )
    if has_xmldsig:
        parts.append("\n")
        parts.append(
            '        ("encode-xmldsig", "Encode EXI XmldsigFragment from JSON to EXI bytes",\n'
            '            cxxopts::value<std::string>()->implicit_value("cmd"))\n'
        )
        parts.append(
            '        ("decode-xmldsig", "Decode EXI XmldsigFragment from EXI bytes to JSON",\n'
            '            cxxopts::value<std::string>()->implicit_value("cmd"))'
        )
    parts.append("\n")
    parts.append(
        '        ("i,input", "Input file (JSON for encode, hex EXI for decode)",\n'
        '            cxxopts::value<std::string>())\n'
    )
    parts.append(
        '        ("o,output", "Output file",\n'
        '            cxxopts::value<std::string>());\n'
    )
    parts.append("\n")
    parts.append("    cxxopts::ParseResult result;\n")
    parts.append("    try {\n")
    parts.append("        result = options.parse(argc, argv);\n")
    parts.append("    } catch (const cxxopts::exceptions::exception& e) {\n")
    parts.append("        std::cerr << \"Error: \" << e.what() << std::endl;\n")
    parts.append("        return 1;\n")
    parts.append("    }\n")
    parts.append("    if (result.count(\"help\")) {\n")
    parts.append("        std::cout << options.help() << std::endl;\n")
    parts.append("        return 0;\n")
    parts.append("    }\n")
    parts.append("\n")

    # Count active mode flags. Reject 0 or >1.
    flag_names: list[str] = ["encode", "decode"]
    if has_fragment:
        flag_names += ["encode-fragment", "decode-fragment"]
    if has_xmldsig:
        flag_names += ["encode-xmldsig", "decode-xmldsig"]
    parts.append("    int mode_count = 0;\n")
    for f in flag_names:
        parts.append(f'    mode_count += result.count("{f}");\n')
    parts.append("    if (mode_count == 0) {\n")
    parts.append(
        '        std::cerr << "Error: Must specify exactly one encode/decode flag." << std::endl;\n'
    )
    parts.append("        std::cout << options.help() << std::endl;\n")
    parts.append("        return 1;\n")
    parts.append("    }\n")
    parts.append("    if (mode_count > 1) {\n")
    parts.append(
        '        std::cerr << "Error: Cannot specify multiple encode/decode flags." << std::endl;\n'
    )
    parts.append("        std::cout << options.help() << std::endl;\n")
    parts.append("        return 1;\n")
    parts.append("    }\n")
    parts.append("\n")

    # Dispatch table. Each generated branch references symbols that exist in
    # this binary's linked Processor object — codegen omits branches for roots
    # not present, so the linker never sees a dangling symbol.
    parts.append(
        '    if (result.count("encode")) {\n'
        "        return expy_cli_encode(encodeFromPythonDict, free_encoded_data,\n"
        '                               result, result["encode"].as<std::string>());\n'
        "    }\n"
        '    if (result.count("decode")) {\n'
        "        return expy_cli_decode(decodeFromPythonBytes, free_decoded_data,\n"
        '                               result, result["decode"].as<std::string>());\n'
        "    }\n"
    )
    if has_fragment:
        parts.append(
            '    if (result.count("encode-fragment")) {\n'
            "        return expy_cli_encode(encode_fragment_FromPythonDict, free_encoded_data,\n"
            '                               result, result["encode-fragment"].as<std::string>());\n'
            "    }\n"
            '    if (result.count("decode-fragment")) {\n'
            "        return expy_cli_decode(decode_fragment_FromPythonBytes, free_decoded_data,\n"
            '                               result, result["decode-fragment"].as<std::string>());\n'
            "    }\n"
        )
    if has_xmldsig:
        parts.append(
            '    if (result.count("encode-xmldsig")) {\n'
            "        return expy_cli_encode(encode_xmldsig_FromPythonDict, free_encoded_data,\n"
            '                               result, result["encode-xmldsig"].as<std::string>());\n'
            "    }\n"
            '    if (result.count("decode-xmldsig")) {\n'
            "        return expy_cli_decode(decode_xmldsig_FromPythonBytes, free_decoded_data,\n"
            '                               result, result["decode-xmldsig"].as<std::string>());\n'
            "    }\n"
        )

    parts.append("    return 1;\n")
    parts.append("}\n")
    return "".join(parts)


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--namespace", required=True, choices=sorted(NAMESPACES.keys()))
    p.add_argument("--header", required=True, type=Path,
                   help="libcbv2g *_Datatypes.h to parse for root-type detection")
    p.add_argument("--out-cpp", required=True, type=Path)
    args = p.parse_args(argv)

    from .parser import parse_header

    policy = NAMESPACES[args.namespace]
    specs = parse_header(args.header.read_text())
    root_types = detect_root_types([s.name for s in specs], policy.c_prefix)
    if not root_types:
        print(
            f"error: no root types ({policy.c_prefix}_exiDocument etc.) found in "
            f"{args.header}",
            file=sys.stderr,
        )
        return 1

    args.out_cpp.parent.mkdir(parents=True, exist_ok=True)
    args.out_cpp.write_text(emit_cli_cpp(policy, root_types))
    return 0


if __name__ == "__main__":
    sys.exit(main())
