"""Emit `V2Gjson/<namespace>.py` enum tables from libcbv2g `*_Datatypes.h`.

Per ADR-0001, V2Gjson currently mixes two roles: (1) `Enum` classes consumed
by the fixture generator via `_resolve_enum_value` (it looks up the first
enum value when seeding an enum-typed scalar), and (2) hand-written
constructor helpers callers use to build JSON payloads. This emitter covers
(1) only — the constructor helpers stay hand-written until a separate
generator targets them.

The parser is intentionally narrow: it recognises ``typedef enum { ... }
NAME;`` blocks where each member is ``<NAME>_<MEMBER> = <int>`` and emits one
Python ``Enum`` subclass per typedef, with the member names stripped of the
type prefix. Anything that does not match (e.g. enums whose members lack the
type prefix) raises rather than silently producing a wrong module.
"""

from __future__ import annotations

import re
from pathlib import Path


_TYPEDEF_ENUM_RE = re.compile(
    r"typedef\s+enum\s*\{(?P<body>[^}]*)\}\s*(?P<name>\w+)\s*;",
    re.DOTALL,
)
_MEMBER_RE = re.compile(r"(?P<name>\w+)\s*=\s*(?P<value>-?\d+)")


class EnumEmitError(Exception):
    pass


def emit(header_text: str, *, namespace_prefix: str, module_doc: str) -> str:
    """Return source text for a V2Gjson module containing one Enum per typedef.

    `namespace_prefix` is the libcbv2g type-name prefix (e.g. ``"iso20_"``).
    Class names in the emitted module strip that prefix so that
    `fixture_emitter._resolve_enum_value` finds them after applying the same
    strip — matching the hand-written `V2Gjson/iso2.py` convention.
    """
    chunks: list[str] = [
        '"""',
        module_doc,
        "",
        "Auto-generated by tools/codegen/v2gjson_emitter.py. DO NOT EDIT.",
        '"""',
        "",
        "from enum import Enum",
        "",
        "",
    ]
    for m in _TYPEDEF_ENUM_RE.finditer(header_text):
        type_name = m["name"]
        try:
            members = _extract_members(m["body"], type_name)
        except EnumEmitError as e:
            # libcbv2g exposes one internal dispatch table per Namespace
            # (`*_generatedFunctionNumbersType`) whose members are bare
            # message names, not XSD-derived enums. No marshaler field is
            # typed as it, so the fixture generator never asks for it. Skip
            # rather than raise — log a marker comment so the omission is
            # visible in the emitted module.
            chunks.append(f"# skipped {type_name}: {e}")
            chunks.append("")
            continue
        class_name = type_name
        if namespace_prefix and class_name.startswith(namespace_prefix):
            class_name = class_name[len(namespace_prefix):]
        chunks.append(f"class {class_name}(Enum):")
        if not members:
            chunks.append("    pass")
        else:
            for member_name, value in members:
                chunks.append(f"    {member_name} = {value}")
        chunks.append("")
        chunks.append("")
    return "\n".join(chunks).rstrip() + "\n"


def _extract_members(body: str, type_name: str) -> list[tuple[str, int]]:
    prefix = type_name + "_"
    out: list[tuple[str, int]] = []
    for m in _MEMBER_RE.finditer(body):
        raw = m["name"]
        if not raw.startswith(prefix):
            raise EnumEmitError(
                f"enum {type_name} member {raw!r} does not start with expected prefix {prefix!r}"
            )
        short = raw[len(prefix):]
        # Python keyword guard: append a trailing underscore. `None` is the
        # only realistic collision in the libcbv2g headers (e.g.
        # `EVSENotificationType.None`), and the existing hand-written
        # `V2Gjson/iso2.py` uses `None_ = 0` for the same reason — match.
        if short == "None":
            short = "None_"
        out.append((short, int(m["value"])))
    return out


def main(argv: list[str] | None = None) -> int:
    import argparse

    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--header", required=True, type=Path)
    p.add_argument("--out", required=True, type=Path)
    p.add_argument("--module-doc", required=True, help="One-line module docstring")
    p.add_argument(
        "--namespace-prefix",
        required=True,
        help='libcbv2g type-name prefix to strip from class names (e.g. "iso20_")',
    )
    args = p.parse_args(argv)

    text = emit(
        args.header.read_text(),
        namespace_prefix=args.namespace_prefix,
        module_doc=args.module_doc,
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    return 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
