"""Emit `V2Gjson/<namespace>.py` modules from libcbv2g `*_Datatypes.h`.

Output covers both surfaces consumers need:

* ``Enum`` subclasses — one per ``typedef enum { ... } NAME;`` block. The
  fixture generator's ``_resolve_enum_value`` looks these up via
  ``c_type[len(prefix):]``, matching the hand-written V2Gjson convention.

* Constructor functions — one per ``struct <prefix><Name> { ... }``. Each
  builds the JSON dict shape libcbv2g's Processor accepts (per ADR-0012),
  wrapping ``bytearray`` and ``str`` inputs into the
  ``{"bytes"/"characters": [...], "...Len": N}`` envelope. The
  ``<prefix>exiDocument`` struct is intentionally skipped — ADR-0012's flat
  top-level Document shape makes that wrapper vestigial.
"""

from __future__ import annotations

import re
from pathlib import Path

from .parser import Field, TypeSpec, parse_header


_TYPEDEF_ENUM_RE = re.compile(
    r"typedef\s+enum\s*\{(?P<body>[^}]*)\}\s*(?P<name>\w+)\s*;",
    re.DOTALL,
)
_MEMBER_RE = re.compile(r"(?P<name>\w+)\s*=\s*(?P<value>-?\d+)")


class EnumEmitError(Exception):
    pass


def emit(header_text: str, *, namespace_prefix: str, module_doc: str) -> str:
    """Return source text for a V2Gjson module containing one Enum per typedef.

    `namespace_prefix` is the libcbv2g type-name prefix (e.g. ``"iso20_"``).
    Class names in the emitted module strip that prefix so that
    `fixture_emitter._resolve_enum_value` finds them after applying the same
    strip — matching the hand-written `V2Gjson/iso2.py` convention.
    """
    chunks: list[str] = [
        '"""',
        module_doc,
        "",
        "Auto-generated by tools/codegen/v2gjson_emitter.py. DO NOT EDIT.",
        '"""',
        "",
        "from enum import Enum",
        "from typing import Any",
        "",
        "",
    ]
    enum_names: set[str] = set()
    for m in _TYPEDEF_ENUM_RE.finditer(header_text):
        enum_names.add(m["name"])
        type_name = m["name"]
        try:
            members = _extract_members(m["body"], type_name)
        except EnumEmitError as e:
            # libcbv2g exposes one internal dispatch table per Namespace
            # (`*_generatedFunctionNumbersType`) whose members are bare
            # message names, not XSD-derived enums. No marshaler field is
            # typed as it, so the fixture generator never asks for it. Skip
            # rather than raise — log a marker comment so the omission is
            # visible in the emitted module.
            chunks.append(f"# skipped {type_name}: {e}")
            chunks.append("")
            continue
        class_name = type_name
        if namespace_prefix and class_name.startswith(namespace_prefix):
            class_name = class_name[len(namespace_prefix):]
        chunks.append(f"class {class_name}(Enum):")
        if not members:
            chunks.append("    pass")
        else:
            for member_name, value in members:
                chunks.append(f"    {member_name} = {value}")
        chunks.append("")
        chunks.append("")

    for spec in parse_header(header_text):
        ctor = _emit_constructor(
            spec, namespace_prefix=namespace_prefix, enum_names=enum_names
        )
        if ctor is None:
            continue
        chunks.append(ctor)
        chunks.append("")

    return "\n".join(chunks).rstrip() + "\n"


def _emit_constructor(
    spec: TypeSpec, *, namespace_prefix: str, enum_names: set[str]
) -> str | None:
    """Return constructor source text for `spec`, or None if it should be skipped.

    The prefix-stripped function name preserves libcbv2g's verbatim casing
    so that top-level element constructors stay lowercase
    (`appHand_supportedAppProtocolReq` → `supportedAppProtocolReq`).
    Per ADR-0012, the `exiDocument` wrapper struct is skipped — the flat
    Document shape consumers build directly does not need it.
    """
    if namespace_prefix and spec.name.startswith(namespace_prefix):
        fn_name = spec.name[len(namespace_prefix):]
    else:
        fn_name = spec.name
    if fn_name == "exiDocument":
        return None

    required = [f for f in spec.fields if not f.optional]
    optional = [f for f in spec.fields if f.optional]

    pieces = [
        f"{f.name}:{_param_type(f, namespace_prefix, enum_names)}"
        for f in required
    ]
    if optional:
        pieces.append("*")
        pieces.extend(
            f"{f.name}:{_param_type(f, namespace_prefix, enum_names)}|None=None"
            for f in optional
        )
    sig = f"def {fn_name}({', '.join(pieces)})->dict[str, Any]:"

    lines: list[str] = []
    if required:
        lines.append("    j:dict[str, Any] = {")
        for i, f in enumerate(required):
            comma = "," if i < len(required) - 1 else ""
            lines.append(f'        "{f.name}": {_value_expr(f, enum_names)}{comma}')
        lines.append("    }")
    else:
        lines.append("    j:dict[str, Any] = {}")
    for f in optional:
        lines.append(f"    if {f.name} is not None:")
        lines.append(f'        j["{f.name}"] = {_value_expr(f, enum_names)}')
    lines.append("    return j")
    return "\n".join([sig, *lines])


def _param_type(field: Field, namespace_prefix: str, enum_names: set[str]) -> str:
    if field.kind == "bytes":
        return "bytearray"
    if field.kind == "characters":
        return "str"
    if field.kind == "scalar" and field.c_type in enum_names:
        cls = field.c_type
        if namespace_prefix and cls.startswith(namespace_prefix):
            cls = cls[len(namespace_prefix):]
        return cls
    if field.kind == "array":
        return "list[dict[str, Any]]"
    if field.kind == "scalar_array":
        if field.c_type in enum_names:
            cls = field.c_type
            if namespace_prefix and cls.startswith(namespace_prefix):
                cls = cls[len(namespace_prefix):]
            return f"list[{cls}]"
        return "list[int]"
    if field.kind == "bytes_array":
        return "list[bytearray]"
    if field.kind == "chars_array":
        return "list[str]"
    return "int"


def _value_expr(field: Field, enum_names: set[str]) -> str:
    """Python expression producing the JSON value for `field.name` at runtime."""
    if field.kind == "bytes":
        return (
            f'{{"bytes": list({field.name}), '
            f'"bytesLen": len({field.name})}}'
        )
    if field.kind == "characters":
        return (
            f'{{"characters": [ord(c) for c in {field.name}], '
            f'"charactersLen": len({field.name})}}'
        )
    if field.kind == "scalar" and field.c_type in enum_names:
        return f"{field.name}.value"
    if field.kind == "array":
        return (
            f'{{"arrayLen": len({field.name}), '
            f'"array": {field.name}}}'
        )
    if field.kind == "scalar_array":
        if field.c_type in enum_names:
            return (
                f'{{"arrayLen": len({field.name}), '
                f'"array": [_v.value for _v in {field.name}]}}'
            )
        return (
            f'{{"arrayLen": len({field.name}), '
            f'"array": list({field.name})}}'
        )
    if field.kind == "bytes_array":
        return (
            f'{{"arrayLen": len({field.name}), '
            f'"array": [{{"bytes": list(_b), "bytesLen": len(_b)}} '
            f'for _b in {field.name}]}}'
        )
    if field.kind == "chars_array":
        return (
            f'{{"arrayLen": len({field.name}), '
            f'"array": [{{"characters": [ord(_c) for _c in _s], '
            f'"charactersLen": len(_s)}} for _s in {field.name}]}}'
        )
    return field.name


def _extract_members(body: str, type_name: str) -> list[tuple[str, int]]:
    prefix = type_name + "_"
    out: list[tuple[str, int]] = []
    for m in _MEMBER_RE.finditer(body):
        raw = m["name"]
        if not raw.startswith(prefix):
            raise EnumEmitError(
                f"enum {type_name} member {raw!r} does not start with expected prefix {prefix!r}"
            )
        short = raw[len(prefix):]
        # Python keyword guard: append a trailing underscore. `None` is the
        # only realistic collision in the libcbv2g headers (e.g.
        # `EVSENotificationType.None`), and the existing hand-written
        # `V2Gjson/iso2.py` uses `None_ = 0` for the same reason — match.
        if short == "None":
            short = "None_"
        out.append((short, int(m["value"])))
    return out


def main(argv: list[str] | None = None) -> int:
    import argparse

    p = argparse.ArgumentParser(description=__doc__)
    p.add_argument("--header", required=True, type=Path)
    p.add_argument("--out", required=True, type=Path)
    p.add_argument("--module-doc", required=True, help="One-line module docstring")
    p.add_argument(
        "--namespace-prefix",
        required=True,
        help='libcbv2g type-name prefix to strip from class names (e.g. "iso20_")',
    )
    args = p.parse_args(argv)

    text = emit(
        args.header.read_text(),
        namespace_prefix=args.namespace_prefix,
        module_doc=args.module_doc,
    )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(text)
    return 0


if __name__ == "__main__":
    import sys

    sys.exit(main())
