/*
    Copyright 2025, Battelle Energy Alliance, LLC All Rights Reserved
*/

#include <cstddef>
#include <cstdint>
#include <cstring>
#include <string>

#include <cbv2g/iso_20/iso20_AC_Datatypes.h>
#include <cbv2g/iso_20/iso20_AC_Decoder.h>
#include <cbv2g/iso_20/iso20_AC_Encoder.h>

#include <common.hpp>
#include "ISO20ACProcessor.hpp"

#include <nlohmann/json.hpp>
using json = nlohmann::json;

using namespace std;


// Marshalers — generated by tools/codegen from iso20_AC_Datatypes.h.
#include "generated/ISO20AC_marshalers.generated.cpp"


extern "C" {

    decoded_data* decodeFromPythonBytes(const uint8_t* data, size_t size) {
        try {
            iso20_ac_exiDocument outDoc;
            exi_bitstream_t inEXI;

            exi_bitstream_init(&inEXI, const_cast<uint8_t*>(data), size, 0, nullptr);
            int rc = decode_iso20_ac_exiDocument(&inEXI, &outDoc);

            decoded_data* result = new decoded_data{nullptr, rc};
            if (rc != 0) {
                return result;
            }

            json outJson = getJson_ac_exiDocument(outDoc);

            static string jsonString;
            jsonString = outJson.dump(4);

            result->json = jsonString.c_str();
            return result;
        } catch (...) {
            return new decoded_data{nullptr, EXPY_ERROR__MARSHALER_INPUT};
        }
    }

    encoded_data* encodeFromPythonDict(const char* inString) {
        try {
            json inJson = json::parse(inString);

            iso20_ac_exiDocument inDoc;
            inDoc = getDoc_ac_exiDocument(inJson);

            uint8_t* stream = new uint8_t[256];
            exi_bitstream_t outEXI;
            size_t pos1 = 0;

            exi_bitstream_init(&outEXI, stream, 256, pos1, nullptr);
            int rc = encode_iso20_ac_exiDocument(&outEXI, &inDoc);

            encoded_data* result = new encoded_data;
            result->status = rc;
            result->size = exi_bitstream_get_length(&outEXI);
            result->buffer = new uint8_t[result->size];
            memcpy(result->buffer, stream, result->size);

            delete[] stream;
            return result;
        } catch (...) {
            encoded_data* result = new encoded_data;
            result->status = EXPY_ERROR__MARSHALER_INPUT;
            result->size = 0;
            result->buffer = nullptr;
            return result;
        }
    }

    decoded_data* decode_fragment_FromPythonBytes(const uint8_t* data, size_t size) {
        try {
            iso20_ac_exiFragment outDoc;
            exi_bitstream_t inEXI;

            exi_bitstream_init(&inEXI, const_cast<uint8_t*>(data), size, 0, nullptr);
            int rc = decode_iso20_ac_exiFragment(&inEXI, &outDoc);

            decoded_data* result = new decoded_data{nullptr, rc};
            if (rc != 0) {
                return result;
            }

            json outJson = getJson_ac_exiFragment(outDoc);

            static string jsonString;
            jsonString = outJson.dump(4);

            result->json = jsonString.c_str();
            return result;
        } catch (...) {
            return new decoded_data{nullptr, EXPY_ERROR__MARSHALER_INPUT};
        }
    }

    encoded_data* encode_fragment_FromPythonDict(const char* inString) {
        try {
            json inJson = json::parse(inString);

            iso20_ac_exiFragment inDoc;
            inDoc = getDoc_ac_exiFragment(inJson);

            uint8_t* stream = new uint8_t[256];
            exi_bitstream_t outEXI;
            size_t pos1 = 0;

            exi_bitstream_init(&outEXI, stream, 256, pos1, nullptr);
            int rc = encode_iso20_ac_exiFragment(&outEXI, &inDoc);

            encoded_data* result = new encoded_data;
            result->status = rc;
            result->size = exi_bitstream_get_length(&outEXI);
            result->buffer = new uint8_t[result->size];
            memcpy(result->buffer, stream, result->size);

            delete[] stream;
            return result;
        } catch (...) {
            encoded_data* result = new encoded_data;
            result->status = EXPY_ERROR__MARSHALER_INPUT;
            result->size = 0;
            result->buffer = nullptr;
            return result;
        }
    }

    decoded_data* decode_xmldsig_FromPythonBytes(const uint8_t* data, size_t size) {
        try {
            iso20_ac_xmldsigFragment outDoc;
            exi_bitstream_t inEXI;

            exi_bitstream_init(&inEXI, const_cast<uint8_t*>(data), size, 0, nullptr);
            int rc = decode_iso20_ac_xmldsigFragment(&inEXI, &outDoc);

            decoded_data* result = new decoded_data{nullptr, rc};
            if (rc != 0) {
                return result;
            }

            json outJson = getJson_ac_xmldsigFragment(outDoc);

            static string jsonString;
            jsonString = outJson.dump(4);

            result->json = jsonString.c_str();
            return result;
        } catch (...) {
            return new decoded_data{nullptr, EXPY_ERROR__MARSHALER_INPUT};
        }
    }

    encoded_data* encode_xmldsig_FromPythonDict(const char* inString) {
        try {
            json inJson = json::parse(inString);

            iso20_ac_xmldsigFragment inDoc;
            inDoc = getDoc_ac_xmldsigFragment(inJson);

            uint8_t* stream = new uint8_t[256];
            exi_bitstream_t outEXI;
            size_t pos1 = 0;

            exi_bitstream_init(&outEXI, stream, 256, pos1, nullptr);
            int rc = encode_iso20_ac_xmldsigFragment(&outEXI, &inDoc);

            encoded_data* result = new encoded_data;
            result->status = rc;
            result->size = exi_bitstream_get_length(&outEXI);
            result->buffer = new uint8_t[result->size];
            memcpy(result->buffer, stream, result->size);

            delete[] stream;
            return result;
        } catch (...) {
            encoded_data* result = new encoded_data;
            result->status = EXPY_ERROR__MARSHALER_INPUT;
            result->size = 0;
            result->buffer = nullptr;
            return result;
        }
    }

    void free_encoded_data(encoded_data* data) {
        if (data) {
            delete[] data->buffer;
            delete data;
        }
    }

    void free_decoded_data(decoded_data* data) {
        // The JSON payload itself lives in a function-static string; only the
        // wrapper struct is heap-allocated.
        if (data) {
            delete data;
        }
    }
}
