/*
    Copyright 2025, Battelle Energy Alliance, LLC All Rights Reserved
*/

#include <cstddef>
#include <cstdint>
#include <string>
#include <vector>
#include <memory>
#include <new>

#include <cbv2g/app_handshake/appHand_Decoder.h>
#include <cbv2g/app_handshake/appHand_Encoder.h>
#include <cbv2g/app_handshake/appHand_Datatypes.h>

#include <common.hpp>

#include <nlohmann/json.hpp>
using json = nlohmann::json;

#include <cxxopts.hpp>

#include <iostream>
#include <fstream>
using namespace std;



// Marshalers — generated by tools/codegen from appHand_Datatypes.h.
#include "generated/SAP_marshalers.generated.cpp"


extern "C" {
    struct decoded_data {
        const char* json;
        int status;
    };

    struct encoded_data {
        uint8_t* buffer;
        size_t size;
        int status;
    };

    decoded_data* decodeFromPythonBytes(const uint8_t* data, size_t size) {
        try {
            appHand_exiDocument outDoc;
            exi_bitstream_t inEXI;

            exi_bitstream_init(&inEXI, const_cast<uint8_t*>(data), size, 0, nullptr);
            int rc = decode_appHand_exiDocument(&inEXI, &outDoc);

            decoded_data* result = new decoded_data{nullptr, rc};
            if (rc != 0) {
                return result;
            }

            json outJson = getJson_exiDocument(outDoc);

            static string jsonString;
            jsonString = outJson.dump(4);

            result->json = jsonString.c_str();
            return result;
        } catch (...) {
            // Marshaler / nlohmann::json exception path. Surface as the C++ -side
            // sentinel rc; Python raises DecodeError. Distinct from libcbv2g rc.
            return new decoded_data{nullptr, EXPY_ERROR__MARSHALER_INPUT};
        }
    }

    encoded_data* encodeFromPythonDict(const char* inString) {
        try {
            json inJson = json::parse(inString);

            appHand_exiDocument inDoc;
            inDoc = getDoc_exiDocument(inJson);

            uint8_t* stream = new uint8_t[256];
            exi_bitstream_t outEXI;
            size_t pos1 = 0;

            exi_bitstream_init(&outEXI, stream, 256, pos1, nullptr);
            int rc = encode_appHand_exiDocument(&outEXI, &inDoc);

            encoded_data* result = new encoded_data;
            result->status = rc;
            result->size = exi_bitstream_get_length(&outEXI);
            result->buffer = new uint8_t[result->size];
            memcpy(result->buffer, stream, result->size);

            delete[] stream;
            return result;
        } catch (...) {
            // json::parse or marshaler-side accessor threw. Surface as sentinel
            // rc so Python raises EncodeError instead of the runtime aborting.
            encoded_data* result = new encoded_data;
            result->status = EXPY_ERROR__MARSHALER_INPUT;
            result->size = 0;
            result->buffer = nullptr;
            return result;
        }
    }

    void free_encoded_data(encoded_data* data) {
        if (data) {
            delete[] data->buffer;
            delete data;
        }
    }

    void free_decoded_data(decoded_data* data) {
        // The JSON payload itself lives in a function-static string; only the
        // wrapper struct is heap-allocated.
        if (data) {
            delete data;
        }
    }
}

int main(int argc, char* argv[]) {
    cxxopts::Options options("./SupportedAppProtocolProcessor --[encode/decode]='STRING_OPTIONAL' -i FILE_INPUT -o FILE_OUTPUT\n  ./SupportedAppProtocolProcessor --decode='80400040'\n  ./SupportedAppProtocolProcessor -e -i input.json -o output.txt\n  ./SupportedAppProtocolProcessor", "Encode and decode Supported App Protocol (SAP) EXI messages\nIf no argument specified for input/outfile, will default to stdin/stdout\nMUST use double quotes (\") and lower case true/false");
    options.add_options()
        ("h,help", "Show help")
        ("e,encode", "Encode EXI message from JSON to EXI bytes", cxxopts::value<std::string>()->implicit_value("cmd"))
        ("d,decode", "Decode EXI message from EXI bytes to JSON", cxxopts::value<std::string>()->implicit_value("cmd"))
        ("i,input", "Input file to read JSON or EXI bytes from", cxxopts::value<std::string>())
        ("o,output", "Output file to write JSON or EXI bytes to", cxxopts::value<std::string>());

    auto result = options.parse(argc, argv);
    if (result.count("help")) {
        std::cout << options.help() << std::endl;
        return 0;
    }

    // Error handling
    if (result.count("encode") == 0 && result.count("decode") == 0) {
        std::cerr << "Error: Must specify either encode or decode option." << std::endl;
        std::cout << options.help() << std::endl;
        return 1;
    }

    if (result.count("encode") && result.count("decode")) {
        std::cerr << "Error: Cannot specify both encode and decode options." << std::endl;
        std::cout << options.help() << std::endl;
        return 1;
    }

    if (result.count("encode")) {
        if (result["encode"].as<std::string>() != "cmd" && result.count("input")) {
            std::cerr << "Error: Cannot encode string input with file input option." << std::endl;
            std::cout << options.help() << std::endl;
            return 1;
        }

        string inString;
        if (result.count("input")) {
            ifstream inputFile(result["input"].as<std::string>());
            if (inputFile.is_open()) {
                stringstream buffer;
                buffer << inputFile.rdbuf();
                inString = buffer.str();
                inputFile.close();
            } else {
                std::cerr << "Error: Could not open input file." << std::endl;
                return 1;
            }

        } else {
            inString = result["encode"].as<std::string>();
        }

        bool isValid = json::accept(inString);
        if (!isValid) {
            std::cerr << "Error: Invalid JSON input." << std::endl;
            return 1;
        }

        encoded_data* encodedResult = encodeFromPythonDict(inString.c_str());
        if (result.count("output")) {
            ofstream outputFile(result["output"].as<std::string>());
            if (outputFile.is_open()) {
                // Convert bytes to hex string
                stringstream hexStream;
                for (size_t i = 0; i < encodedResult->size; ++i) {
                    hexStream << std::hex << std::setw(2) << std::setfill('0') << (int)encodedResult->buffer[i];
                }
                outputFile << hexStream.str();
                outputFile.close();
            } else {
                std::cerr << "Error: Could not open output file." << std::endl;
                free_encoded_data(encodedResult);
                return 1;
            }
        } else {
            for (size_t i = 0; i < encodedResult->size; ++i) {
                cout << std::hex << std::setw(2) << std::setfill('0') << (int)encodedResult->buffer[i];
            }
            cout << endl;
        }

    }

    if (result.count("decode")) {
        if (result["decode"].as<std::string>() != "cmd" && result.count("input")) {
            std::cerr << "Error: Cannot decode string input with file input option." << std::endl;
            std::cout << options.help() << std::endl;
            return 1;
        }

        string hexString;
        if (result.count("input")) {
            ifstream inputFile(result["input"].as<std::string>());
            if (inputFile.is_open()) {
                stringstream buffer;
                buffer << inputFile.rdbuf();
                hexString = buffer.str();
                inputFile.close();
            } else {
                std::cerr << "Error: Could not open input file." << std::endl;
                return 1;
            }
        } else {
            hexString = result["decode"].as<std::string>();
        }

        // Convert hex string to bytes
        if (hexString.length() % 2 != 0) {
            std::cerr << "Error: Invalid hex string length." << std::endl;
            return 1;
        }

        vector<uint8_t> bytes;
        for (size_t i = 0; i < hexString.length(); i += 2) {
            string byteString = hexString.substr(i, 2);
            try {
                uint8_t byte = static_cast<uint8_t>(stoi(byteString, nullptr, 16));
                bytes.push_back(byte);
            } catch (const std::exception& e) {
                std::cerr << "Error: Invalid hex string format." << std::endl;
                return 1;
            }
        }

        decoded_data* decoded = decodeFromPythonBytes(bytes.data(), bytes.size());
        if (decoded->status != 0) {
            std::cerr << "Error: libcbv2g decode failed (rc=" << decoded->status << ")." << std::endl;
            free_decoded_data(decoded);
            return 1;
        }
        const char* jsonString = decoded->json;
        if (result.count("output")) {
            ofstream outputFile(result["output"].as<std::string>());
            if (outputFile.is_open()) {
                // Try to parse and pretty print JSON
                try {
                    json j = json::parse(jsonString);
                    outputFile << j.dump(4);
                    outputFile.close();
                } catch (const json::parse_error& e) {
                    std::cerr << "Error: Failed to parse JSON output." << std::endl;
                    free_decoded_data(decoded);
                    return 1;
                }
            } else {
                std::cerr << "Error: Could not open output file." << std::endl;
                free_decoded_data(decoded);
                return 1;
            }
        } else {
            try {
                json j = json::parse(jsonString);
                cout << j.dump(4) << endl;
            } catch (const json::parse_error& e) {
                std::cerr << "Error: Failed to parse JSON output." << std::endl;
                free_decoded_data(decoded);
                return 1;
            }
        }
        free_decoded_data(decoded);
    }
    return 0;
}
